/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NotFoundRouteImport } from './routes/$not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTerminationRouteImport } from './routes/_auth/termination'
import { Route as AuthSearchIndexRouteImport } from './routes/_auth/search/index'
import { Route as AuthSearchAgentIdRouteImport } from './routes/_auth/search/$agentId'
import { Route as AuthDashboardTerminationRouteImport } from './routes/_auth/dashboard/termination'
import { Route as AuthDashboardCreateBulkRouteImport } from './routes/_auth/dashboard/create-bulk'
import { Route as AuthDashboardCertificationUpdateRouteImport } from './routes/_auth/dashboard/certification-update'
import { Route as AuthDashboardNotFoundRouteImport } from './routes/_auth/dashboard/$not-found'
import { Route as AuthCommissionTerminationRouteImport } from './routes/_auth/commission/termination'
import { Route as AuthCommissionCreateBulkRouteImport } from './routes/_auth/commission/create-bulk'
import { Route as AuthCommissionCertificationUpdateRouteImport } from './routes/_auth/commission/certification-update'
import { Route as AuthCommissionNotFoundRouteImport } from './routes/_auth/commission/$not-found'
import { Route as AuthSearchDashboardTerminationRouteImport } from './routes/_auth/search/dashboard/termination'
import { Route as AuthSearchDashboardCreateBulkRouteImport } from './routes/_auth/search/dashboard/create-bulk'
import { Route as AuthSearchDashboardCertificationUpdateRouteImport } from './routes/_auth/search/dashboard/certification-update'
import { Route as AuthDashboardCodeMovementBulkActionRouteImport } from './routes/_auth/dashboard/code-movement/bulk-action'
import { Route as AuthCommissionProcesscommissionBulkActionRouteImport } from './routes/_auth/commission/processcommission/bulk-action'
import { Route as AuthSearchDashboardCodeMovementBulkActionRouteImport } from './routes/_auth/search/dashboard/code-movement/bulk-action'

const LoginLazyRouteImport = createFileRoute('/login')()
const AuthUserInboxLazyRouteImport = createFileRoute('/_auth/user-inbox')()
const AuthRolesManagementIndexLazyRouteImport = createFileRoute(
  '/_auth/roles-management/',
)()
const AuthDashboardIndexLazyRouteImport = createFileRoute('/_auth/dashboard/')()
const AuthCommissionIndexLazyRouteImport =
  createFileRoute('/_auth/commission/')()
const AuthSearchDashboardIndexLazyRouteImport = createFileRoute(
  '/_auth/search/dashboard/',
)()
const AuthSearchCommissionIndexLazyRouteImport = createFileRoute(
  '/_auth/search/commission/',
)()
const AuthDashboardCodeMovementIndexLazyRouteImport = createFileRoute(
  '/_auth/dashboard/code-movement/',
)()
const AuthCommissionProcesscommissionIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/processcommission/',
)()
const AuthCommissionConfigcommissionListIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/configcommission-list/',
)()
const AuthCommissionConfigcomissionIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/configcomission/',
)()
const AuthCommissionConfigcommissionListNewCommissionCreationLazyRouteImport =
  createFileRoute(
    '/_auth/commission/configcommission-list/new-commission-creation',
  )()
const AuthCommissionConfigcommissionListHistoryLazyRouteImport =
  createFileRoute('/_auth/commission/configcommission-list/history')()
const AuthSearchDashboardCodeMovementIndexLazyRouteImport = createFileRoute(
  '/_auth/search/dashboard/code-movement/',
)()
const AuthSearchCommissionProcesscommissionIndexLazyRouteImport =
  createFileRoute('/_auth/search/commission/processcommission/')()
const AuthSearchCommissionConfigcommissionListIndexLazyRouteImport =
  createFileRoute('/_auth/search/commission/configcommission-list/')()
const AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRouteImport =
  createFileRoute(
    '/_auth/search/commission/configcommission-list/new-commission-creation',
  )()
const AuthSearchCommissionConfigcommissionListHistoryLazyRouteImport =
  createFileRoute('/_auth/search/commission/configcommission-list/history')()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserInboxLazyRoute = AuthUserInboxLazyRouteImport.update({
  id: '/user-inbox',
  path: '/user-inbox',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/user-inbox.lazy').then((d) => d.Route),
)
const AuthTerminationRoute = AuthTerminationRouteImport.update({
  id: '/termination',
  path: '/termination',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesManagementIndexLazyRoute =
  AuthRolesManagementIndexLazyRouteImport.update({
    id: '/roles-management/',
    path: '/roles-management/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/roles-management/index.lazy').then((d) => d.Route),
  )
const AuthDashboardIndexLazyRoute = AuthDashboardIndexLazyRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/dashboard/index.lazy').then((d) => d.Route),
)
const AuthCommissionIndexLazyRoute = AuthCommissionIndexLazyRouteImport.update({
  id: '/commission/',
  path: '/commission/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/commission/index.lazy').then((d) => d.Route),
)
const AuthSearchIndexRoute = AuthSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchAgentIdRoute = AuthSearchAgentIdRouteImport.update({
  id: '/search/$agentId',
  path: '/search/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardTerminationRoute =
  AuthDashboardTerminationRouteImport.update({
    id: '/dashboard/termination',
    path: '/dashboard/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardCreateBulkRoute = AuthDashboardCreateBulkRouteImport.update({
  id: '/dashboard/create-bulk',
  path: '/dashboard/create-bulk',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCertificationUpdateRoute =
  AuthDashboardCertificationUpdateRouteImport.update({
    id: '/dashboard/certification-update',
    path: '/dashboard/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardNotFoundRoute = AuthDashboardNotFoundRouteImport.update({
  id: '/dashboard/$not-found',
  path: '/dashboard/$not-found',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionTerminationRoute =
  AuthCommissionTerminationRouteImport.update({
    id: '/commission/termination',
    path: '/commission/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionCreateBulkRoute =
  AuthCommissionCreateBulkRouteImport.update({
    id: '/commission/create-bulk',
    path: '/commission/create-bulk',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionCertificationUpdateRoute =
  AuthCommissionCertificationUpdateRouteImport.update({
    id: '/commission/certification-update',
    path: '/commission/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionNotFoundRoute = AuthCommissionNotFoundRouteImport.update({
  id: '/commission/$not-found',
  path: '/commission/$not-found',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchDashboardIndexLazyRoute =
  AuthSearchDashboardIndexLazyRouteImport.update({
    id: '/search/dashboard/',
    path: '/search/dashboard/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/search/dashboard/index.lazy').then((d) => d.Route),
  )
const AuthSearchCommissionIndexLazyRoute =
  AuthSearchCommissionIndexLazyRouteImport.update({
    id: '/search/commission/',
    path: '/search/commission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/search/commission/index.lazy').then((d) => d.Route),
  )
const AuthDashboardCodeMovementIndexLazyRoute =
  AuthDashboardCodeMovementIndexLazyRouteImport.update({
    id: '/dashboard/code-movement/',
    path: '/dashboard/code-movement/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/dashboard/code-movement/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionProcesscommissionIndexLazyRoute =
  AuthCommissionProcesscommissionIndexLazyRouteImport.update({
    id: '/commission/processcommission/',
    path: '/commission/processcommission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/processcommission/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionConfigcommissionListIndexLazyRoute =
  AuthCommissionConfigcommissionListIndexLazyRouteImport.update({
    id: '/commission/configcommission-list/',
    path: '/commission/configcommission-list/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/configcommission-list/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionConfigcomissionIndexLazyRoute =
  AuthCommissionConfigcomissionIndexLazyRouteImport.update({
    id: '/commission/configcomission/',
    path: '/commission/configcomission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/configcomission/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute =
  AuthCommissionConfigcommissionListNewCommissionCreationLazyRouteImport.update(
    {
      id: '/commission/configcommission-list/new-commission-creation',
      path: '/commission/configcommission-list/new-commission-creation',
      getParentRoute: () => AuthRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_auth/commission/configcommission-list/new-commission-creation.lazy'
    ).then((d) => d.Route),
  )
const AuthCommissionConfigcommissionListHistoryLazyRoute =
  AuthCommissionConfigcommissionListHistoryLazyRouteImport.update({
    id: '/commission/configcommission-list/history',
    path: '/commission/configcommission-list/history',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/configcommission-list/history.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthSearchDashboardTerminationRoute =
  AuthSearchDashboardTerminationRouteImport.update({
    id: '/search/dashboard/termination',
    path: '/search/dashboard/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSearchDashboardCreateBulkRoute =
  AuthSearchDashboardCreateBulkRouteImport.update({
    id: '/search/dashboard/create-bulk',
    path: '/search/dashboard/create-bulk',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSearchDashboardCertificationUpdateRoute =
  AuthSearchDashboardCertificationUpdateRouteImport.update({
    id: '/search/dashboard/certification-update',
    path: '/search/dashboard/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardCodeMovementBulkActionRoute =
  AuthDashboardCodeMovementBulkActionRouteImport.update({
    id: '/dashboard/code-movement/bulk-action',
    path: '/dashboard/code-movement/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionProcesscommissionBulkActionRoute =
  AuthCommissionProcesscommissionBulkActionRouteImport.update({
    id: '/commission/processcommission/bulk-action',
    path: '/commission/processcommission/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSearchDashboardCodeMovementIndexLazyRoute =
  AuthSearchDashboardCodeMovementIndexLazyRouteImport.update({
    id: '/search/dashboard/code-movement/',
    path: '/search/dashboard/code-movement/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/search/dashboard/code-movement/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthSearchCommissionProcesscommissionIndexLazyRoute =
  AuthSearchCommissionProcesscommissionIndexLazyRouteImport.update({
    id: '/search/commission/processcommission/',
    path: '/search/commission/processcommission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth/search/commission/processcommission/index.lazy'
    ).then((d) => d.Route),
  )
const AuthSearchCommissionConfigcommissionListIndexLazyRoute =
  AuthSearchCommissionConfigcommissionListIndexLazyRouteImport.update({
    id: '/search/commission/configcommission-list/',
    path: '/search/commission/configcommission-list/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth/search/commission/configcommission-list/index.lazy'
    ).then((d) => d.Route),
  )
const AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute =
  AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRouteImport.update(
    {
      id: '/search/commission/configcommission-list/new-commission-creation',
      path: '/search/commission/configcommission-list/new-commission-creation',
      getParentRoute: () => AuthRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_auth/search/commission/configcommission-list/new-commission-creation.lazy'
    ).then((d) => d.Route),
  )
const AuthSearchCommissionConfigcommissionListHistoryLazyRoute =
  AuthSearchCommissionConfigcommissionListHistoryLazyRouteImport.update({
    id: '/search/commission/configcommission-list/history',
    path: '/search/commission/configcommission-list/history',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import(
      './routes/_auth/search/commission/configcommission-list/history.lazy'
    ).then((d) => d.Route),
  )
const AuthSearchDashboardCodeMovementBulkActionRoute =
  AuthSearchDashboardCodeMovementBulkActionRouteImport.update({
    id: '/search/dashboard/code-movement/bulk-action',
    path: '/search/dashboard/code-movement/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/termination': typeof AuthTerminationRoute
  '/user-inbox': typeof AuthUserInboxLazyRoute
  '/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/commission/termination': typeof AuthCommissionTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/search/$agentId': typeof AuthSearchAgentIdRoute
  '/search': typeof AuthSearchIndexRoute
  '/commission': typeof AuthCommissionIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/roles-management': typeof AuthRolesManagementIndexLazyRoute
  '/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/search/dashboard/certification-update': typeof AuthSearchDashboardCertificationUpdateRoute
  '/search/dashboard/create-bulk': typeof AuthSearchDashboardCreateBulkRoute
  '/search/dashboard/termination': typeof AuthSearchDashboardTerminationRoute
  '/commission/configcommission-list/history': typeof AuthCommissionConfigcommissionListHistoryLazyRoute
  '/commission/configcommission-list/new-commission-creation': typeof AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/commission/configcomission': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/commission/configcommission-list': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/commission/processcommission': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
  '/search/commission': typeof AuthSearchCommissionIndexLazyRoute
  '/search/dashboard': typeof AuthSearchDashboardIndexLazyRoute
  '/search/dashboard/code-movement/bulk-action': typeof AuthSearchDashboardCodeMovementBulkActionRoute
  '/search/commission/configcommission-list/history': typeof AuthSearchCommissionConfigcommissionListHistoryLazyRoute
  '/search/commission/configcommission-list/new-commission-creation': typeof AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/search/commission/configcommission-list': typeof AuthSearchCommissionConfigcommissionListIndexLazyRoute
  '/search/commission/processcommission': typeof AuthSearchCommissionProcesscommissionIndexLazyRoute
  '/search/dashboard/code-movement': typeof AuthSearchDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/termination': typeof AuthTerminationRoute
  '/user-inbox': typeof AuthUserInboxLazyRoute
  '/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/commission/termination': typeof AuthCommissionTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/search/$agentId': typeof AuthSearchAgentIdRoute
  '/search': typeof AuthSearchIndexRoute
  '/commission': typeof AuthCommissionIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/roles-management': typeof AuthRolesManagementIndexLazyRoute
  '/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/search/dashboard/certification-update': typeof AuthSearchDashboardCertificationUpdateRoute
  '/search/dashboard/create-bulk': typeof AuthSearchDashboardCreateBulkRoute
  '/search/dashboard/termination': typeof AuthSearchDashboardTerminationRoute
  '/commission/configcommission-list/history': typeof AuthCommissionConfigcommissionListHistoryLazyRoute
  '/commission/configcommission-list/new-commission-creation': typeof AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/commission/configcomission': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/commission/configcommission-list': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/commission/processcommission': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
  '/search/commission': typeof AuthSearchCommissionIndexLazyRoute
  '/search/dashboard': typeof AuthSearchDashboardIndexLazyRoute
  '/search/dashboard/code-movement/bulk-action': typeof AuthSearchDashboardCodeMovementBulkActionRoute
  '/search/commission/configcommission-list/history': typeof AuthSearchCommissionConfigcommissionListHistoryLazyRoute
  '/search/commission/configcommission-list/new-commission-creation': typeof AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/search/commission/configcommission-list': typeof AuthSearchCommissionConfigcommissionListIndexLazyRoute
  '/search/commission/processcommission': typeof AuthSearchCommissionProcesscommissionIndexLazyRoute
  '/search/dashboard/code-movement': typeof AuthSearchDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_auth/termination': typeof AuthTerminationRoute
  '/_auth/user-inbox': typeof AuthUserInboxLazyRoute
  '/_auth/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/_auth/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/_auth/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/_auth/commission/termination': typeof AuthCommissionTerminationRoute
  '/_auth/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/_auth/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/_auth/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/_auth/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/_auth/search/$agentId': typeof AuthSearchAgentIdRoute
  '/_auth/search/': typeof AuthSearchIndexRoute
  '/_auth/commission/': typeof AuthCommissionIndexLazyRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexLazyRoute
  '/_auth/roles-management/': typeof AuthRolesManagementIndexLazyRoute
  '/_auth/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/_auth/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/_auth/search/dashboard/certification-update': typeof AuthSearchDashboardCertificationUpdateRoute
  '/_auth/search/dashboard/create-bulk': typeof AuthSearchDashboardCreateBulkRoute
  '/_auth/search/dashboard/termination': typeof AuthSearchDashboardTerminationRoute
  '/_auth/commission/configcommission-list/history': typeof AuthCommissionConfigcommissionListHistoryLazyRoute
  '/_auth/commission/configcommission-list/new-commission-creation': typeof AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/_auth/commission/configcomission/': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/_auth/commission/configcommission-list/': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/_auth/commission/processcommission/': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/_auth/dashboard/code-movement/': typeof AuthDashboardCodeMovementIndexLazyRoute
  '/_auth/search/commission/': typeof AuthSearchCommissionIndexLazyRoute
  '/_auth/search/dashboard/': typeof AuthSearchDashboardIndexLazyRoute
  '/_auth/search/dashboard/code-movement/bulk-action': typeof AuthSearchDashboardCodeMovementBulkActionRoute
  '/_auth/search/commission/configcommission-list/history': typeof AuthSearchCommissionConfigcommissionListHistoryLazyRoute
  '/_auth/search/commission/configcommission-list/new-commission-creation': typeof AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute
  '/_auth/search/commission/configcommission-list/': typeof AuthSearchCommissionConfigcommissionListIndexLazyRoute
  '/_auth/search/commission/processcommission/': typeof AuthSearchCommissionProcesscommissionIndexLazyRoute
  '/_auth/search/dashboard/code-movement/': typeof AuthSearchDashboardCodeMovementIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$not-found'
    | '/login'
    | '/termination'
    | '/user-inbox'
    | '/commission/$not-found'
    | '/commission/certification-update'
    | '/commission/create-bulk'
    | '/commission/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/create-bulk'
    | '/dashboard/termination'
    | '/search/$agentId'
    | '/search'
    | '/commission'
    | '/dashboard'
    | '/roles-management'
    | '/commission/processcommission/bulk-action'
    | '/dashboard/code-movement/bulk-action'
    | '/search/dashboard/certification-update'
    | '/search/dashboard/create-bulk'
    | '/search/dashboard/termination'
    | '/commission/configcommission-list/history'
    | '/commission/configcommission-list/new-commission-creation'
    | '/commission/configcomission'
    | '/commission/configcommission-list'
    | '/commission/processcommission'
    | '/dashboard/code-movement'
    | '/search/commission'
    | '/search/dashboard'
    | '/search/dashboard/code-movement/bulk-action'
    | '/search/commission/configcommission-list/history'
    | '/search/commission/configcommission-list/new-commission-creation'
    | '/search/commission/configcommission-list'
    | '/search/commission/processcommission'
    | '/search/dashboard/code-movement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$not-found'
    | '/login'
    | '/termination'
    | '/user-inbox'
    | '/commission/$not-found'
    | '/commission/certification-update'
    | '/commission/create-bulk'
    | '/commission/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/create-bulk'
    | '/dashboard/termination'
    | '/search/$agentId'
    | '/search'
    | '/commission'
    | '/dashboard'
    | '/roles-management'
    | '/commission/processcommission/bulk-action'
    | '/dashboard/code-movement/bulk-action'
    | '/search/dashboard/certification-update'
    | '/search/dashboard/create-bulk'
    | '/search/dashboard/termination'
    | '/commission/configcommission-list/history'
    | '/commission/configcommission-list/new-commission-creation'
    | '/commission/configcomission'
    | '/commission/configcommission-list'
    | '/commission/processcommission'
    | '/dashboard/code-movement'
    | '/search/commission'
    | '/search/dashboard'
    | '/search/dashboard/code-movement/bulk-action'
    | '/search/commission/configcommission-list/history'
    | '/search/commission/configcommission-list/new-commission-creation'
    | '/search/commission/configcommission-list'
    | '/search/commission/processcommission'
    | '/search/dashboard/code-movement'
  id:
    | '__root__'
    | '/'
    | '/$not-found'
    | '/_auth'
    | '/login'
    | '/_auth/termination'
    | '/_auth/user-inbox'
    | '/_auth/commission/$not-found'
    | '/_auth/commission/certification-update'
    | '/_auth/commission/create-bulk'
    | '/_auth/commission/termination'
    | '/_auth/dashboard/$not-found'
    | '/_auth/dashboard/certification-update'
    | '/_auth/dashboard/create-bulk'
    | '/_auth/dashboard/termination'
    | '/_auth/search/$agentId'
    | '/_auth/search/'
    | '/_auth/commission/'
    | '/_auth/dashboard/'
    | '/_auth/roles-management/'
    | '/_auth/commission/processcommission/bulk-action'
    | '/_auth/dashboard/code-movement/bulk-action'
    | '/_auth/search/dashboard/certification-update'
    | '/_auth/search/dashboard/create-bulk'
    | '/_auth/search/dashboard/termination'
    | '/_auth/commission/configcommission-list/history'
    | '/_auth/commission/configcommission-list/new-commission-creation'
    | '/_auth/commission/configcomission/'
    | '/_auth/commission/configcommission-list/'
    | '/_auth/commission/processcommission/'
    | '/_auth/dashboard/code-movement/'
    | '/_auth/search/commission/'
    | '/_auth/search/dashboard/'
    | '/_auth/search/dashboard/code-movement/bulk-action'
    | '/_auth/search/commission/configcommission-list/history'
    | '/_auth/search/commission/configcommission-list/new-commission-creation'
    | '/_auth/search/commission/configcommission-list/'
    | '/_auth/search/commission/processcommission/'
    | '/_auth/search/dashboard/code-movement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/user-inbox': {
      id: '/_auth/user-inbox'
      path: '/user-inbox'
      fullPath: '/user-inbox'
      preLoaderRoute: typeof AuthUserInboxLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/termination': {
      id: '/_auth/termination'
      path: '/termination'
      fullPath: '/termination'
      preLoaderRoute: typeof AuthTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles-management/': {
      id: '/_auth/roles-management/'
      path: '/roles-management'
      fullPath: '/roles-management'
      preLoaderRoute: typeof AuthRolesManagementIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/': {
      id: '/_auth/commission/'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof AuthCommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/': {
      id: '/_auth/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/$agentId': {
      id: '/_auth/search/$agentId'
      path: '/search/$agentId'
      fullPath: '/search/$agentId'
      preLoaderRoute: typeof AuthSearchAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/termination': {
      id: '/_auth/dashboard/termination'
      path: '/dashboard/termination'
      fullPath: '/dashboard/termination'
      preLoaderRoute: typeof AuthDashboardTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/create-bulk': {
      id: '/_auth/dashboard/create-bulk'
      path: '/dashboard/create-bulk'
      fullPath: '/dashboard/create-bulk'
      preLoaderRoute: typeof AuthDashboardCreateBulkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/certification-update': {
      id: '/_auth/dashboard/certification-update'
      path: '/dashboard/certification-update'
      fullPath: '/dashboard/certification-update'
      preLoaderRoute: typeof AuthDashboardCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/$not-found': {
      id: '/_auth/dashboard/$not-found'
      path: '/dashboard/$not-found'
      fullPath: '/dashboard/$not-found'
      preLoaderRoute: typeof AuthDashboardNotFoundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/termination': {
      id: '/_auth/commission/termination'
      path: '/commission/termination'
      fullPath: '/commission/termination'
      preLoaderRoute: typeof AuthCommissionTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/create-bulk': {
      id: '/_auth/commission/create-bulk'
      path: '/commission/create-bulk'
      fullPath: '/commission/create-bulk'
      preLoaderRoute: typeof AuthCommissionCreateBulkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/certification-update': {
      id: '/_auth/commission/certification-update'
      path: '/commission/certification-update'
      fullPath: '/commission/certification-update'
      preLoaderRoute: typeof AuthCommissionCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/$not-found': {
      id: '/_auth/commission/$not-found'
      path: '/commission/$not-found'
      fullPath: '/commission/$not-found'
      preLoaderRoute: typeof AuthCommissionNotFoundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/': {
      id: '/_auth/search/dashboard/'
      path: '/search/dashboard'
      fullPath: '/search/dashboard'
      preLoaderRoute: typeof AuthSearchDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/commission/': {
      id: '/_auth/search/commission/'
      path: '/search/commission'
      fullPath: '/search/commission'
      preLoaderRoute: typeof AuthSearchCommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/': {
      id: '/_auth/dashboard/code-movement/'
      path: '/dashboard/code-movement'
      fullPath: '/dashboard/code-movement'
      preLoaderRoute: typeof AuthDashboardCodeMovementIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/processcommission/': {
      id: '/_auth/commission/processcommission/'
      path: '/commission/processcommission'
      fullPath: '/commission/processcommission'
      preLoaderRoute: typeof AuthCommissionProcesscommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcommission-list/': {
      id: '/_auth/commission/configcommission-list/'
      path: '/commission/configcommission-list'
      fullPath: '/commission/configcommission-list'
      preLoaderRoute: typeof AuthCommissionConfigcommissionListIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcomission/': {
      id: '/_auth/commission/configcomission/'
      path: '/commission/configcomission'
      fullPath: '/commission/configcomission'
      preLoaderRoute: typeof AuthCommissionConfigcomissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcommission-list/new-commission-creation': {
      id: '/_auth/commission/configcommission-list/new-commission-creation'
      path: '/commission/configcommission-list/new-commission-creation'
      fullPath: '/commission/configcommission-list/new-commission-creation'
      preLoaderRoute: typeof AuthCommissionConfigcommissionListNewCommissionCreationLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcommission-list/history': {
      id: '/_auth/commission/configcommission-list/history'
      path: '/commission/configcommission-list/history'
      fullPath: '/commission/configcommission-list/history'
      preLoaderRoute: typeof AuthCommissionConfigcommissionListHistoryLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/termination': {
      id: '/_auth/search/dashboard/termination'
      path: '/search/dashboard/termination'
      fullPath: '/search/dashboard/termination'
      preLoaderRoute: typeof AuthSearchDashboardTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/create-bulk': {
      id: '/_auth/search/dashboard/create-bulk'
      path: '/search/dashboard/create-bulk'
      fullPath: '/search/dashboard/create-bulk'
      preLoaderRoute: typeof AuthSearchDashboardCreateBulkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/certification-update': {
      id: '/_auth/search/dashboard/certification-update'
      path: '/search/dashboard/certification-update'
      fullPath: '/search/dashboard/certification-update'
      preLoaderRoute: typeof AuthSearchDashboardCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/bulk-action': {
      id: '/_auth/dashboard/code-movement/bulk-action'
      path: '/dashboard/code-movement/bulk-action'
      fullPath: '/dashboard/code-movement/bulk-action'
      preLoaderRoute: typeof AuthDashboardCodeMovementBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/processcommission/bulk-action': {
      id: '/_auth/commission/processcommission/bulk-action'
      path: '/commission/processcommission/bulk-action'
      fullPath: '/commission/processcommission/bulk-action'
      preLoaderRoute: typeof AuthCommissionProcesscommissionBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/code-movement/': {
      id: '/_auth/search/dashboard/code-movement/'
      path: '/search/dashboard/code-movement'
      fullPath: '/search/dashboard/code-movement'
      preLoaderRoute: typeof AuthSearchDashboardCodeMovementIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/commission/processcommission/': {
      id: '/_auth/search/commission/processcommission/'
      path: '/search/commission/processcommission'
      fullPath: '/search/commission/processcommission'
      preLoaderRoute: typeof AuthSearchCommissionProcesscommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/commission/configcommission-list/': {
      id: '/_auth/search/commission/configcommission-list/'
      path: '/search/commission/configcommission-list'
      fullPath: '/search/commission/configcommission-list'
      preLoaderRoute: typeof AuthSearchCommissionConfigcommissionListIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/commission/configcommission-list/new-commission-creation': {
      id: '/_auth/search/commission/configcommission-list/new-commission-creation'
      path: '/search/commission/configcommission-list/new-commission-creation'
      fullPath: '/search/commission/configcommission-list/new-commission-creation'
      preLoaderRoute: typeof AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/commission/configcommission-list/history': {
      id: '/_auth/search/commission/configcommission-list/history'
      path: '/search/commission/configcommission-list/history'
      fullPath: '/search/commission/configcommission-list/history'
      preLoaderRoute: typeof AuthSearchCommissionConfigcommissionListHistoryLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/dashboard/code-movement/bulk-action': {
      id: '/_auth/search/dashboard/code-movement/bulk-action'
      path: '/search/dashboard/code-movement/bulk-action'
      fullPath: '/search/dashboard/code-movement/bulk-action'
      preLoaderRoute: typeof AuthSearchDashboardCodeMovementBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthTerminationRoute: typeof AuthTerminationRoute
  AuthUserInboxLazyRoute: typeof AuthUserInboxLazyRoute
  AuthCommissionNotFoundRoute: typeof AuthCommissionNotFoundRoute
  AuthCommissionCertificationUpdateRoute: typeof AuthCommissionCertificationUpdateRoute
  AuthCommissionCreateBulkRoute: typeof AuthCommissionCreateBulkRoute
  AuthCommissionTerminationRoute: typeof AuthCommissionTerminationRoute
  AuthDashboardNotFoundRoute: typeof AuthDashboardNotFoundRoute
  AuthDashboardCertificationUpdateRoute: typeof AuthDashboardCertificationUpdateRoute
  AuthDashboardCreateBulkRoute: typeof AuthDashboardCreateBulkRoute
  AuthDashboardTerminationRoute: typeof AuthDashboardTerminationRoute
  AuthSearchAgentIdRoute: typeof AuthSearchAgentIdRoute
  AuthSearchIndexRoute: typeof AuthSearchIndexRoute
  AuthCommissionIndexLazyRoute: typeof AuthCommissionIndexLazyRoute
  AuthDashboardIndexLazyRoute: typeof AuthDashboardIndexLazyRoute
  AuthRolesManagementIndexLazyRoute: typeof AuthRolesManagementIndexLazyRoute
  AuthCommissionProcesscommissionBulkActionRoute: typeof AuthCommissionProcesscommissionBulkActionRoute
  AuthDashboardCodeMovementBulkActionRoute: typeof AuthDashboardCodeMovementBulkActionRoute
  AuthSearchDashboardCertificationUpdateRoute: typeof AuthSearchDashboardCertificationUpdateRoute
  AuthSearchDashboardCreateBulkRoute: typeof AuthSearchDashboardCreateBulkRoute
  AuthSearchDashboardTerminationRoute: typeof AuthSearchDashboardTerminationRoute
  AuthCommissionConfigcommissionListHistoryLazyRoute: typeof AuthCommissionConfigcommissionListHistoryLazyRoute
  AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute: typeof AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute
  AuthCommissionConfigcomissionIndexLazyRoute: typeof AuthCommissionConfigcomissionIndexLazyRoute
  AuthCommissionConfigcommissionListIndexLazyRoute: typeof AuthCommissionConfigcommissionListIndexLazyRoute
  AuthCommissionProcesscommissionIndexLazyRoute: typeof AuthCommissionProcesscommissionIndexLazyRoute
  AuthDashboardCodeMovementIndexLazyRoute: typeof AuthDashboardCodeMovementIndexLazyRoute
  AuthSearchCommissionIndexLazyRoute: typeof AuthSearchCommissionIndexLazyRoute
  AuthSearchDashboardIndexLazyRoute: typeof AuthSearchDashboardIndexLazyRoute
  AuthSearchDashboardCodeMovementBulkActionRoute: typeof AuthSearchDashboardCodeMovementBulkActionRoute
  AuthSearchCommissionConfigcommissionListHistoryLazyRoute: typeof AuthSearchCommissionConfigcommissionListHistoryLazyRoute
  AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute: typeof AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute
  AuthSearchCommissionConfigcommissionListIndexLazyRoute: typeof AuthSearchCommissionConfigcommissionListIndexLazyRoute
  AuthSearchCommissionProcesscommissionIndexLazyRoute: typeof AuthSearchCommissionProcesscommissionIndexLazyRoute
  AuthSearchDashboardCodeMovementIndexLazyRoute: typeof AuthSearchDashboardCodeMovementIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTerminationRoute: AuthTerminationRoute,
  AuthUserInboxLazyRoute: AuthUserInboxLazyRoute,
  AuthCommissionNotFoundRoute: AuthCommissionNotFoundRoute,
  AuthCommissionCertificationUpdateRoute:
    AuthCommissionCertificationUpdateRoute,
  AuthCommissionCreateBulkRoute: AuthCommissionCreateBulkRoute,
  AuthCommissionTerminationRoute: AuthCommissionTerminationRoute,
  AuthDashboardNotFoundRoute: AuthDashboardNotFoundRoute,
  AuthDashboardCertificationUpdateRoute: AuthDashboardCertificationUpdateRoute,
  AuthDashboardCreateBulkRoute: AuthDashboardCreateBulkRoute,
  AuthDashboardTerminationRoute: AuthDashboardTerminationRoute,
  AuthSearchAgentIdRoute: AuthSearchAgentIdRoute,
  AuthSearchIndexRoute: AuthSearchIndexRoute,
  AuthCommissionIndexLazyRoute: AuthCommissionIndexLazyRoute,
  AuthDashboardIndexLazyRoute: AuthDashboardIndexLazyRoute,
  AuthRolesManagementIndexLazyRoute: AuthRolesManagementIndexLazyRoute,
  AuthCommissionProcesscommissionBulkActionRoute:
    AuthCommissionProcesscommissionBulkActionRoute,
  AuthDashboardCodeMovementBulkActionRoute:
    AuthDashboardCodeMovementBulkActionRoute,
  AuthSearchDashboardCertificationUpdateRoute:
    AuthSearchDashboardCertificationUpdateRoute,
  AuthSearchDashboardCreateBulkRoute: AuthSearchDashboardCreateBulkRoute,
  AuthSearchDashboardTerminationRoute: AuthSearchDashboardTerminationRoute,
  AuthCommissionConfigcommissionListHistoryLazyRoute:
    AuthCommissionConfigcommissionListHistoryLazyRoute,
  AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute:
    AuthCommissionConfigcommissionListNewCommissionCreationLazyRoute,
  AuthCommissionConfigcomissionIndexLazyRoute:
    AuthCommissionConfigcomissionIndexLazyRoute,
  AuthCommissionConfigcommissionListIndexLazyRoute:
    AuthCommissionConfigcommissionListIndexLazyRoute,
  AuthCommissionProcesscommissionIndexLazyRoute:
    AuthCommissionProcesscommissionIndexLazyRoute,
  AuthDashboardCodeMovementIndexLazyRoute:
    AuthDashboardCodeMovementIndexLazyRoute,
  AuthSearchCommissionIndexLazyRoute: AuthSearchCommissionIndexLazyRoute,
  AuthSearchDashboardIndexLazyRoute: AuthSearchDashboardIndexLazyRoute,
  AuthSearchDashboardCodeMovementBulkActionRoute:
    AuthSearchDashboardCodeMovementBulkActionRoute,
  AuthSearchCommissionConfigcommissionListHistoryLazyRoute:
    AuthSearchCommissionConfigcommissionListHistoryLazyRoute,
  AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute:
    AuthSearchCommissionConfigcommissionListNewCommissionCreationLazyRoute,
  AuthSearchCommissionConfigcommissionListIndexLazyRoute:
    AuthSearchCommissionConfigcommissionListIndexLazyRoute,
  AuthSearchCommissionProcesscommissionIndexLazyRoute:
    AuthSearchCommissionProcesscommissionIndexLazyRoute,
  AuthSearchDashboardCodeMovementIndexLazyRoute:
    AuthSearchDashboardCodeMovementIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
