/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NotFoundRouteImport } from './routes/$not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTerminationRouteImport } from './routes/_auth/termination'
import { Route as AuthSearchIndexRouteImport } from './routes/_auth/search/index'
import { Route as AuthSearchAgentIdRouteImport } from './routes/_auth/search/$agentId'
import { Route as AuthDashboardTerminationRouteImport } from './routes/_auth/dashboard/termination'
import { Route as AuthDashboardCreateBulkRouteImport } from './routes/_auth/dashboard/create-bulk'
import { Route as AuthDashboardCertificationUpdateRouteImport } from './routes/_auth/dashboard/certification-update'
import { Route as AuthDashboardNotFoundRouteImport } from './routes/_auth/dashboard/$not-found'
import { Route as AuthCommissionTerminationRouteImport } from './routes/_auth/commission/termination'
import { Route as AuthCommissionCreateBulkRouteImport } from './routes/_auth/commission/create-bulk'
import { Route as AuthCommissionCertificationUpdateRouteImport } from './routes/_auth/commission/certification-update'
import { Route as AuthCommissionNotFoundRouteImport } from './routes/_auth/commission/$not-found'
import { Route as AuthDashboardCodeMovementBulkActionRouteImport } from './routes/_auth/dashboard/code-movement/bulk-action'
import { Route as AuthCommissionProcesscommissionBulkActionRouteImport } from './routes/_auth/commission/processcommission/bulk-action'

const LoginLazyRouteImport = createFileRoute('/login')()
const AuthDashboardIndexLazyRouteImport = createFileRoute('/_auth/dashboard/')()
const AuthCommissionIndexLazyRouteImport =
  createFileRoute('/_auth/commission/')()
const AuthDashboardCodeMovementIndexLazyRouteImport = createFileRoute(
  '/_auth/dashboard/code-movement/',
)()
const AuthCommissionProcesscommissionIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/processcommission/',
)()
const AuthCommissionConfigcommissionListIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/configcommission-list/',
)()
const AuthCommissionConfigcomissionIndexLazyRouteImport = createFileRoute(
  '/_auth/commission/configcomission/',
)()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTerminationRoute = AuthTerminationRouteImport.update({
  id: '/termination',
  path: '/termination',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexLazyRoute = AuthDashboardIndexLazyRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/dashboard/index.lazy').then((d) => d.Route),
)
const AuthCommissionIndexLazyRoute = AuthCommissionIndexLazyRouteImport.update({
  id: '/commission/',
  path: '/commission/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/commission/index.lazy').then((d) => d.Route),
)
const AuthSearchIndexRoute = AuthSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchAgentIdRoute = AuthSearchAgentIdRouteImport.update({
  id: '/search/$agentId',
  path: '/search/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardTerminationRoute =
  AuthDashboardTerminationRouteImport.update({
    id: '/dashboard/termination',
    path: '/dashboard/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardCreateBulkRoute = AuthDashboardCreateBulkRouteImport.update({
  id: '/dashboard/create-bulk',
  path: '/dashboard/create-bulk',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCertificationUpdateRoute =
  AuthDashboardCertificationUpdateRouteImport.update({
    id: '/dashboard/certification-update',
    path: '/dashboard/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardNotFoundRoute = AuthDashboardNotFoundRouteImport.update({
  id: '/dashboard/$not-found',
  path: '/dashboard/$not-found',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommissionTerminationRoute =
  AuthCommissionTerminationRouteImport.update({
    id: '/commission/termination',
    path: '/commission/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionCreateBulkRoute =
  AuthCommissionCreateBulkRouteImport.update({
    id: '/commission/create-bulk',
    path: '/commission/create-bulk',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionCertificationUpdateRoute =
  AuthCommissionCertificationUpdateRouteImport.update({
    id: '/commission/certification-update',
    path: '/commission/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionNotFoundRoute = AuthCommissionNotFoundRouteImport.update({
  id: '/commission/$not-found',
  path: '/commission/$not-found',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCodeMovementIndexLazyRoute =
  AuthDashboardCodeMovementIndexLazyRouteImport.update({
    id: '/dashboard/code-movement/',
    path: '/dashboard/code-movement/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/dashboard/code-movement/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionProcesscommissionIndexLazyRoute =
  AuthCommissionProcesscommissionIndexLazyRouteImport.update({
    id: '/commission/processcommission/',
    path: '/commission/processcommission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/processcommission/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionConfigcommissionListIndexLazyRoute =
  AuthCommissionConfigcommissionListIndexLazyRouteImport.update({
    id: '/commission/configcommission-list/',
    path: '/commission/configcommission-list/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/configcommission-list/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthCommissionConfigcomissionIndexLazyRoute =
  AuthCommissionConfigcomissionIndexLazyRouteImport.update({
    id: '/commission/configcomission/',
    path: '/commission/configcomission/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/commission/configcomission/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthDashboardCodeMovementBulkActionRoute =
  AuthDashboardCodeMovementBulkActionRouteImport.update({
    id: '/dashboard/code-movement/bulk-action',
    path: '/dashboard/code-movement/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCommissionProcesscommissionBulkActionRoute =
  AuthCommissionProcesscommissionBulkActionRouteImport.update({
    id: '/commission/processcommission/bulk-action',
    path: '/commission/processcommission/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/termination': typeof AuthTerminationRoute
  '/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/commission/termination': typeof AuthCommissionTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/search/$agentId': typeof AuthSearchAgentIdRoute
  '/search': typeof AuthSearchIndexRoute
  '/commission': typeof AuthCommissionIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/commission/configcomission': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/commission/configcommission-list': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/commission/processcommission': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/termination': typeof AuthTerminationRoute
  '/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/commission/termination': typeof AuthCommissionTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/search/$agentId': typeof AuthSearchAgentIdRoute
  '/search': typeof AuthSearchIndexRoute
  '/commission': typeof AuthCommissionIndexLazyRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/commission/configcomission': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/commission/configcommission-list': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/commission/processcommission': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$not-found': typeof NotFoundRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_auth/termination': typeof AuthTerminationRoute
  '/_auth/commission/$not-found': typeof AuthCommissionNotFoundRoute
  '/_auth/commission/certification-update': typeof AuthCommissionCertificationUpdateRoute
  '/_auth/commission/create-bulk': typeof AuthCommissionCreateBulkRoute
  '/_auth/commission/termination': typeof AuthCommissionTerminationRoute
  '/_auth/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/_auth/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/_auth/dashboard/create-bulk': typeof AuthDashboardCreateBulkRoute
  '/_auth/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/_auth/search/$agentId': typeof AuthSearchAgentIdRoute
  '/_auth/search/': typeof AuthSearchIndexRoute
  '/_auth/commission/': typeof AuthCommissionIndexLazyRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexLazyRoute
  '/_auth/commission/processcommission/bulk-action': typeof AuthCommissionProcesscommissionBulkActionRoute
  '/_auth/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/_auth/commission/configcomission/': typeof AuthCommissionConfigcomissionIndexLazyRoute
  '/_auth/commission/configcommission-list/': typeof AuthCommissionConfigcommissionListIndexLazyRoute
  '/_auth/commission/processcommission/': typeof AuthCommissionProcesscommissionIndexLazyRoute
  '/_auth/dashboard/code-movement/': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$not-found'
    | '/login'
    | '/termination'
    | '/commission/$not-found'
    | '/commission/certification-update'
    | '/commission/create-bulk'
    | '/commission/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/create-bulk'
    | '/dashboard/termination'
    | '/search/$agentId'
    | '/search'
    | '/commission'
    | '/dashboard'
    | '/commission/processcommission/bulk-action'
    | '/dashboard/code-movement/bulk-action'
    | '/commission/configcomission'
    | '/commission/configcommission-list'
    | '/commission/processcommission'
    | '/dashboard/code-movement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$not-found'
    | '/login'
    | '/termination'
    | '/commission/$not-found'
    | '/commission/certification-update'
    | '/commission/create-bulk'
    | '/commission/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/create-bulk'
    | '/dashboard/termination'
    | '/search/$agentId'
    | '/search'
    | '/commission'
    | '/dashboard'
    | '/commission/processcommission/bulk-action'
    | '/dashboard/code-movement/bulk-action'
    | '/commission/configcomission'
    | '/commission/configcommission-list'
    | '/commission/processcommission'
    | '/dashboard/code-movement'
  id:
    | '__root__'
    | '/'
    | '/$not-found'
    | '/_auth'
    | '/login'
    | '/_auth/termination'
    | '/_auth/commission/$not-found'
    | '/_auth/commission/certification-update'
    | '/_auth/commission/create-bulk'
    | '/_auth/commission/termination'
    | '/_auth/dashboard/$not-found'
    | '/_auth/dashboard/certification-update'
    | '/_auth/dashboard/create-bulk'
    | '/_auth/dashboard/termination'
    | '/_auth/search/$agentId'
    | '/_auth/search/'
    | '/_auth/commission/'
    | '/_auth/dashboard/'
    | '/_auth/commission/processcommission/bulk-action'
    | '/_auth/dashboard/code-movement/bulk-action'
    | '/_auth/commission/configcomission/'
    | '/_auth/commission/configcommission-list/'
    | '/_auth/commission/processcommission/'
    | '/_auth/dashboard/code-movement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotFoundRoute: typeof NotFoundRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/termination': {
      id: '/_auth/termination'
      path: '/termination'
      fullPath: '/termination'
      preLoaderRoute: typeof AuthTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/': {
      id: '/_auth/commission/'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof AuthCommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/': {
      id: '/_auth/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search/$agentId': {
      id: '/_auth/search/$agentId'
      path: '/search/$agentId'
      fullPath: '/search/$agentId'
      preLoaderRoute: typeof AuthSearchAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/termination': {
      id: '/_auth/dashboard/termination'
      path: '/dashboard/termination'
      fullPath: '/dashboard/termination'
      preLoaderRoute: typeof AuthDashboardTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/create-bulk': {
      id: '/_auth/dashboard/create-bulk'
      path: '/dashboard/create-bulk'
      fullPath: '/dashboard/create-bulk'
      preLoaderRoute: typeof AuthDashboardCreateBulkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/certification-update': {
      id: '/_auth/dashboard/certification-update'
      path: '/dashboard/certification-update'
      fullPath: '/dashboard/certification-update'
      preLoaderRoute: typeof AuthDashboardCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/$not-found': {
      id: '/_auth/dashboard/$not-found'
      path: '/dashboard/$not-found'
      fullPath: '/dashboard/$not-found'
      preLoaderRoute: typeof AuthDashboardNotFoundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/termination': {
      id: '/_auth/commission/termination'
      path: '/commission/termination'
      fullPath: '/commission/termination'
      preLoaderRoute: typeof AuthCommissionTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/create-bulk': {
      id: '/_auth/commission/create-bulk'
      path: '/commission/create-bulk'
      fullPath: '/commission/create-bulk'
      preLoaderRoute: typeof AuthCommissionCreateBulkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/certification-update': {
      id: '/_auth/commission/certification-update'
      path: '/commission/certification-update'
      fullPath: '/commission/certification-update'
      preLoaderRoute: typeof AuthCommissionCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/$not-found': {
      id: '/_auth/commission/$not-found'
      path: '/commission/$not-found'
      fullPath: '/commission/$not-found'
      preLoaderRoute: typeof AuthCommissionNotFoundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/': {
      id: '/_auth/dashboard/code-movement/'
      path: '/dashboard/code-movement'
      fullPath: '/dashboard/code-movement'
      preLoaderRoute: typeof AuthDashboardCodeMovementIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/processcommission/': {
      id: '/_auth/commission/processcommission/'
      path: '/commission/processcommission'
      fullPath: '/commission/processcommission'
      preLoaderRoute: typeof AuthCommissionProcesscommissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcommission-list/': {
      id: '/_auth/commission/configcommission-list/'
      path: '/commission/configcommission-list'
      fullPath: '/commission/configcommission-list'
      preLoaderRoute: typeof AuthCommissionConfigcommissionListIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/configcomission/': {
      id: '/_auth/commission/configcomission/'
      path: '/commission/configcomission'
      fullPath: '/commission/configcomission'
      preLoaderRoute: typeof AuthCommissionConfigcomissionIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/bulk-action': {
      id: '/_auth/dashboard/code-movement/bulk-action'
      path: '/dashboard/code-movement/bulk-action'
      fullPath: '/dashboard/code-movement/bulk-action'
      preLoaderRoute: typeof AuthDashboardCodeMovementBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/commission/processcommission/bulk-action': {
      id: '/_auth/commission/processcommission/bulk-action'
      path: '/commission/processcommission/bulk-action'
      fullPath: '/commission/processcommission/bulk-action'
      preLoaderRoute: typeof AuthCommissionProcesscommissionBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthTerminationRoute: typeof AuthTerminationRoute
  AuthCommissionNotFoundRoute: typeof AuthCommissionNotFoundRoute
  AuthCommissionCertificationUpdateRoute: typeof AuthCommissionCertificationUpdateRoute
  AuthCommissionCreateBulkRoute: typeof AuthCommissionCreateBulkRoute
  AuthCommissionTerminationRoute: typeof AuthCommissionTerminationRoute
  AuthDashboardNotFoundRoute: typeof AuthDashboardNotFoundRoute
  AuthDashboardCertificationUpdateRoute: typeof AuthDashboardCertificationUpdateRoute
  AuthDashboardCreateBulkRoute: typeof AuthDashboardCreateBulkRoute
  AuthDashboardTerminationRoute: typeof AuthDashboardTerminationRoute
  AuthSearchAgentIdRoute: typeof AuthSearchAgentIdRoute
  AuthSearchIndexRoute: typeof AuthSearchIndexRoute
  AuthCommissionIndexLazyRoute: typeof AuthCommissionIndexLazyRoute
  AuthDashboardIndexLazyRoute: typeof AuthDashboardIndexLazyRoute
  AuthCommissionProcesscommissionBulkActionRoute: typeof AuthCommissionProcesscommissionBulkActionRoute
  AuthDashboardCodeMovementBulkActionRoute: typeof AuthDashboardCodeMovementBulkActionRoute
  AuthCommissionConfigcomissionIndexLazyRoute: typeof AuthCommissionConfigcomissionIndexLazyRoute
  AuthCommissionConfigcommissionListIndexLazyRoute: typeof AuthCommissionConfigcommissionListIndexLazyRoute
  AuthCommissionProcesscommissionIndexLazyRoute: typeof AuthCommissionProcesscommissionIndexLazyRoute
  AuthDashboardCodeMovementIndexLazyRoute: typeof AuthDashboardCodeMovementIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTerminationRoute: AuthTerminationRoute,
  AuthCommissionNotFoundRoute: AuthCommissionNotFoundRoute,
  AuthCommissionCertificationUpdateRoute:
    AuthCommissionCertificationUpdateRoute,
  AuthCommissionCreateBulkRoute: AuthCommissionCreateBulkRoute,
  AuthCommissionTerminationRoute: AuthCommissionTerminationRoute,
  AuthDashboardNotFoundRoute: AuthDashboardNotFoundRoute,
  AuthDashboardCertificationUpdateRoute: AuthDashboardCertificationUpdateRoute,
  AuthDashboardCreateBulkRoute: AuthDashboardCreateBulkRoute,
  AuthDashboardTerminationRoute: AuthDashboardTerminationRoute,
  AuthSearchAgentIdRoute: AuthSearchAgentIdRoute,
  AuthSearchIndexRoute: AuthSearchIndexRoute,
  AuthCommissionIndexLazyRoute: AuthCommissionIndexLazyRoute,
  AuthDashboardIndexLazyRoute: AuthDashboardIndexLazyRoute,
  AuthCommissionProcesscommissionBulkActionRoute:
    AuthCommissionProcesscommissionBulkActionRoute,
  AuthDashboardCodeMovementBulkActionRoute:
    AuthDashboardCodeMovementBulkActionRoute,
  AuthCommissionConfigcomissionIndexLazyRoute:
    AuthCommissionConfigcomissionIndexLazyRoute,
  AuthCommissionConfigcommissionListIndexLazyRoute:
    AuthCommissionConfigcommissionListIndexLazyRoute,
  AuthCommissionProcesscommissionIndexLazyRoute:
    AuthCommissionProcesscommissionIndexLazyRoute,
  AuthDashboardCodeMovementIndexLazyRoute:
    AuthDashboardCodeMovementIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotFoundRoute: NotFoundRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
