/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as NotFoundRouteImport } from './routes/$not-found'
import { Route as AuthTerminationRouteImport } from './routes/_auth/termination'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthDashboardTerminationRouteImport } from './routes/_auth/dashboard/termination'
import { Route as AuthDashboardCertificationUpdateRouteImport } from './routes/_auth/dashboard/certification-update'
import { Route as AuthDashboardNotFoundRouteImport } from './routes/_auth/dashboard/$not-found'
import { Route as AuthDashboardCodeMovementBulkActionRouteImport } from './routes/_auth/dashboard/code-movement/bulk-action'

const LoginLazyRouteImport = createFileRoute('/login')()
const AuthDashboardIndexLazyRouteImport = createFileRoute('/_auth/dashboard/')()
const AuthDashboardCodeMovementIndexLazyRouteImport = createFileRoute(
  '/_auth/dashboard/code-movement/',
)()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/$not-found',
  path: '/$not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTerminationRoute = AuthTerminationRouteImport.update({
  id: '/termination',
  path: '/termination',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexLazyRoute = AuthDashboardIndexLazyRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/dashboard/index.lazy').then((d) => d.Route),
)
const AuthDashboardTerminationRoute =
  AuthDashboardTerminationRouteImport.update({
    id: '/dashboard/termination',
    path: '/dashboard/termination',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardCertificationUpdateRoute =
  AuthDashboardCertificationUpdateRouteImport.update({
    id: '/dashboard/certification-update',
    path: '/dashboard/certification-update',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardNotFoundRoute = AuthDashboardNotFoundRouteImport.update({
  id: '/dashboard/$not-found',
  path: '/dashboard/$not-found',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardCodeMovementIndexLazyRoute =
  AuthDashboardCodeMovementIndexLazyRouteImport.update({
    id: '/dashboard/code-movement/',
    path: '/dashboard/code-movement/',
    getParentRoute: () => AuthRoute,
  } as any).lazy(() =>
    import('./routes/_auth/dashboard/code-movement/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthDashboardCodeMovementBulkActionRoute =
  AuthDashboardCodeMovementBulkActionRouteImport.update({
    id: '/dashboard/code-movement/bulk-action',
    path: '/dashboard/code-movement/bulk-action',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/search': typeof AuthSearchRoute
  '/termination': typeof AuthTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesByTo {
  '/$not-found': typeof NotFoundRoute
  '/login': typeof LoginLazyRoute
  '/search': typeof AuthSearchRoute
  '/termination': typeof AuthTerminationRoute
  '/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/dashboard': typeof AuthDashboardIndexLazyRoute
  '/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/dashboard/code-movement': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$not-found': typeof NotFoundRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/termination': typeof AuthTerminationRoute
  '/_auth/dashboard/$not-found': typeof AuthDashboardNotFoundRoute
  '/_auth/dashboard/certification-update': typeof AuthDashboardCertificationUpdateRoute
  '/_auth/dashboard/termination': typeof AuthDashboardTerminationRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexLazyRoute
  '/_auth/dashboard/code-movement/bulk-action': typeof AuthDashboardCodeMovementBulkActionRoute
  '/_auth/dashboard/code-movement/': typeof AuthDashboardCodeMovementIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$not-found'
    | '/login'
    | '/search'
    | '/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/termination'
    | '/dashboard'
    | '/dashboard/code-movement/bulk-action'
    | '/dashboard/code-movement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$not-found'
    | '/login'
    | '/search'
    | '/termination'
    | '/dashboard/$not-found'
    | '/dashboard/certification-update'
    | '/dashboard/termination'
    | '/dashboard'
    | '/dashboard/code-movement/bulk-action'
    | '/dashboard/code-movement'
  id:
    | '__root__'
    | '/$not-found'
    | '/_auth'
    | '/login'
    | '/_auth/search'
    | '/_auth/termination'
    | '/_auth/dashboard/$not-found'
    | '/_auth/dashboard/certification-update'
    | '/_auth/dashboard/termination'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/code-movement/bulk-action'
    | '/_auth/dashboard/code-movement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NotFoundRoute: typeof NotFoundRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$not-found': {
      id: '/$not-found'
      path: '/$not-found'
      fullPath: '/$not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/termination': {
      id: '/_auth/termination'
      path: '/termination'
      fullPath: '/termination'
      preLoaderRoute: typeof AuthTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/termination': {
      id: '/_auth/dashboard/termination'
      path: '/dashboard/termination'
      fullPath: '/dashboard/termination'
      preLoaderRoute: typeof AuthDashboardTerminationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/certification-update': {
      id: '/_auth/dashboard/certification-update'
      path: '/dashboard/certification-update'
      fullPath: '/dashboard/certification-update'
      preLoaderRoute: typeof AuthDashboardCertificationUpdateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/$not-found': {
      id: '/_auth/dashboard/$not-found'
      path: '/dashboard/$not-found'
      fullPath: '/dashboard/$not-found'
      preLoaderRoute: typeof AuthDashboardNotFoundRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/': {
      id: '/_auth/dashboard/code-movement/'
      path: '/dashboard/code-movement'
      fullPath: '/dashboard/code-movement'
      preLoaderRoute: typeof AuthDashboardCodeMovementIndexLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/code-movement/bulk-action': {
      id: '/_auth/dashboard/code-movement/bulk-action'
      path: '/dashboard/code-movement/bulk-action'
      fullPath: '/dashboard/code-movement/bulk-action'
      preLoaderRoute: typeof AuthDashboardCodeMovementBulkActionRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSearchRoute: typeof AuthSearchRoute
  AuthTerminationRoute: typeof AuthTerminationRoute
  AuthDashboardNotFoundRoute: typeof AuthDashboardNotFoundRoute
  AuthDashboardCertificationUpdateRoute: typeof AuthDashboardCertificationUpdateRoute
  AuthDashboardTerminationRoute: typeof AuthDashboardTerminationRoute
  AuthDashboardIndexLazyRoute: typeof AuthDashboardIndexLazyRoute
  AuthDashboardCodeMovementBulkActionRoute: typeof AuthDashboardCodeMovementBulkActionRoute
  AuthDashboardCodeMovementIndexLazyRoute: typeof AuthDashboardCodeMovementIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSearchRoute: AuthSearchRoute,
  AuthTerminationRoute: AuthTerminationRoute,
  AuthDashboardNotFoundRoute: AuthDashboardNotFoundRoute,
  AuthDashboardCertificationUpdateRoute: AuthDashboardCertificationUpdateRoute,
  AuthDashboardTerminationRoute: AuthDashboardTerminationRoute,
  AuthDashboardIndexLazyRoute: AuthDashboardIndexLazyRoute,
  AuthDashboardCodeMovementBulkActionRoute:
    AuthDashboardCodeMovementBulkActionRoute,
  AuthDashboardCodeMovementIndexLazyRoute:
    AuthDashboardCodeMovementIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NotFoundRoute: NotFoundRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
