const APIRoutes = {
  LOGIN: "/api/Auth/Login",
  AGENTSEARCH: "/api/Agent/Search",
  AGENTBYCODE: "/api/Agent/AgentByCode",
  AGENTBYID: "/api/Agent/AgentByid",
  GETMASTERS: "/api/AppMasters/get",
  GETCOMMISSION: "/api/CommissionMgmt/Dashboard",
  PROCESSCOMMISSION: "/api/CommissionMgmt/ProcessCommissions",
  HOLDCOMMISSION: "/api/CommissionMgmt/HoldCommission",
  ADJUSTCOMMISSION: "/api/CommissionMgmt/AdjustCommission",
  APPROVECOMMISSION: "/api/CommissionMgmt/ApproveCommission",
  CONFIGCOMMISSION: "/api/CommissionConfig/CreateCommission",
  UPDATECONDITIONCONFIG: "/api/CommissionConfig/UpdateCommissionFormula",
  CONFIGLIST: "/api/CommissionConfig/CommissionJobConfigPaginatedList",
  UPDATECRON: "/api/CommissionConfig/UpdateCronSetting",
  UPDATESTATUS: "/api/CommissionConfig/EnableDisableJob",
  COMMISSIONSEARCHFIELDS: "/api/MetaData/Fetch",
  EXECUTIVEHISTORYLIST: "/api/CommissionConfig/JobExecutionHistory",
  EDITAGENT: "/api/Agent/UpdateAgent",
  UPDATECOMMISSIONBYID: "/api/CommissionConfig/GetCommissionById",
  DOWNLOADRECORD: "/api/CommissionMgmt/DownloadCommissionExcel",
  GEOHIERARCHY: "/api/Agent/GeoHierarchy",
  GEOHIERARCHYTABLE: "/api/Agent/GeoChildren",
  HMSDASHBOARD: "/api/HMSDashboard/GetHMSDashboard",
  CHANNELSTATS: "/api/HMSDashboard/channel-stats",
  UPLOADFILELIST: "/uploaded-file-list",
  DOWNLOADREPORT: "/download-report",
  GETMASTERS: "/api/AppMasters/get",
  UPLOADFILES: "/api/file",
  GETROLES: "/api/Access/Role/List",
  DELETEROLES: "/api/Access/Role/Delete",
  FETCHMENU: "/api/Access/Role/MenuAccess/",
  USERLIST:"/api/Access/Role/UserList/",
  GRANTMENU:"/api/Access/Role/MenuAccess/Grant",
  REVOKEMENU:"/api/Access/Role/MenuAccess/Revoke",
  REMOVEUSER:"/api/Access/Role/RemoveUser",
  CREATEROLE:"/api/Access/Role/Create",
  ADDUSER:"/api/Access/Role/AddUser",
  GETHIERARCHY:"/api/Access/Role/UI/Control/AccessList",
  FIELDUPDATE:"/api/Access/Role/UI/Control/UpdateAccess",
  CHANNELLIST:"api/AppMasters/Channel/Fetch",
  SUBCHANNELLIST:"api/AppMasters",
};

module.exports = { APIRoutes };
