ALTER TABLE hms."user"
ADD COLUMN "FailedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "LockoutEndTime" TIMESTAMP WITH TIME ZONE;
-- 1. Add IS_ACTIVE
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE;

-- 2. Add APPROVED_BY
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "APPROVED_BY" VARCHAR(100);

-- 3. Add APPROVED_DATE
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "APPROVED_DATE" TIMESTAMP;

-- 4. Add REJECTED_BY
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "REJECTED_BY" VARCHAR(100);

-- 5. Add REJECTED_DATE
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "REJECTED_DATE" TIMESTAMP;

-- 6. Add STATUS
ALTER TABLE hms."agent_movement_history"
ADD COLUMN "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending';

ALTER TABLE hms."agent" ADD COLUMN "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE hms.AGENT DROP CONSTRAINT fk_supervisor;
ALTER TABLE hms.AGENT DROP COLUMN SUPERVISOR_CODE;
ALTER TABLE hms.AGENT ADD COLUMN SUPERVISOR_ID INTEGER;

ALTER TABLE hms.AGENT ADD CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE SET NULL;

alter table hms.agent drop column "IS_ACTIVE";
alter table hms.agent add column "is_active"  bool DEFAULT true NOT NULL;
ALTER TABLE hms.agent ALTER COLUMN agent_id DROP DEFAULT;

-- Attach identity (auto-increment) to existing column
ALTER TABLE hms.agent ALTER COLUMN agent_id ADD GENERATED ALWAYS AS IDENTITY;