CREATE SCHEMA IF NOT EXISTS hms;
CREATE TABLE hms.permissions (
    permission_id   VARCHAR(30) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,
    PRIMARY KEY (permission_id)
);

DROP TABLE hms.permissions;

CREATE TABLE hms.permissions (
    permission_id   INTEGER NOT NULL PRIMARY KEY, -- numeric, not auto-generated
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms.roles (
    role_id         INTEGER NOT NULL PRIMARY KEY,
    role_name       VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    is_system_role  BOOLEAN NOT NULL,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms."user" (
    user_id         SERIAL PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    email_id        VARCHAR(150) NOT NULL,
    mobile_number   VARCHAR(20),
    password        VARCHAR(255) NOT NULL,
    is_active       BOOLEAN NOT NULL,
    is_locked       BOOLEAN NOT NULL,
    last_login_date TIMESTAMP,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);

CREATE TABLE hms.user_role_mapping (
    mapping_id      BIGINT NOT NULL PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    role_id         INTEGER NOT NULL,
    is_primary      BOOLEAN NOT NULL,
    effective_from  DATE NOT NULL,
    effective_to    DATE,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,

    CONSTRAINT fk_user
      FOREIGN KEY (user_id) REFERENCES hms.user(user_id),

    CONSTRAINT fk_role
      FOREIGN KEY (role_id) REFERENCES hms.roles(role_id)
);

CREATE TABLE hms.MENU_MASTER (
    MENU_ID          INTEGER PRIMARY KEY,
    MENU_NAME        VARCHAR(100) NOT NULL,
    PARENT_MENU_ID   INTEGER,  -- Self-referencing FK
    ROUTE_PATH       VARCHAR(255),
    DISPLAY_ORDER    INTEGER,
    IS_ACTIVE        BOOLEAN NOT NULL,
    IS_INTERNAL      BOOLEAN,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER,

    CONSTRAINT fk_parent_menu
        FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE SET NULL
);

CREATE TABLE hms.ROLE_MENU_MAPPING (
    MAPPING_ID     INTEGER PRIMARY KEY,
    ROLE_ID        INTEGER NOT NULL,
    MENU_ID        INTEGER NOT NULL,
    IS_VISIBLE     BOOLEAN NOT NULL,
    IS_ENABLED     BOOLEAN NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_menu
        FOREIGN KEY (MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.PERMISSION_MASTER (
    PERMISSION_ID    INTEGER PRIMARY KEY,
    PERMISSION_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    MODULE_NAME      VARCHAR(50),
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.ROLE_PERMISSION_MAPPING (
    ROLE_ID         INTEGER NOT NULL,
    PERMISSION_ID   INTEGER NOT NULL,
    IS_ALLOWED      BOOLEAN NOT NULL,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_permission
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES hms.PERMISSION_MASTER (PERMISSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_TYPE (
    HIERARCHY_TYPE_ID    INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION          VARCHAR(255),
    IS_ACTIVE            BOOLEAN NOT NULL,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER
);

CREATE TABLE hms.HIERARCHY_NODE (
    NODE_ID           INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID INTEGER NOT NULL,
    NODE_CODE         VARCHAR(50) NOT NULL UNIQUE,
    NODE_NAME         VARCHAR(150) NOT NULL,
    LEVEL             INTEGER,
    LOCATION_CODE     VARCHAR(20),
    BRANCH_CODE       VARCHAR(20),
    PARENT_NODE_ID    INTEGER,
    CHANNEL_CODE      VARCHAR(20),
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL

    -- Optional FKs:
    -- Add these only if LOCATION_MASTER, BRANCH_MASTER, CHANNEL_MASTER exist
    -- and their keys match the types defined below.
    
    -- , CONSTRAINT fk_location
    --     FOREIGN KEY (LOCATION_CODE)
    --     REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)

    -- , CONSTRAINT fk_branch
    --     FOREIGN KEY (BRANCH_CODE)
    --     REFERENCES hms.BRANCH_MASTER (BRANCH_CODE)

    -- , CONSTRAINT fk_channel
    --     FOREIGN KEY (CHANNEL_CODE)
    --     REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.HIERARCHY_STRUCTURE (
    STRUCTURE_ID         INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID    INTEGER NOT NULL,
    PARENT_NODE_ID       INTEGER NOT NULL,
    CHILD_NODE_ID        INTEGER NOT NULL,
    RELATIONSHIP_TYPE    VARCHAR(50),
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM       DATE NOT NULL,
    EFFECTIVE_TO         DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_child_node
        FOREIGN KEY (CHILD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_HIERARCHY_ASSIGNMENT (
    ASSIGNMENT_ID      INTEGER PRIMARY KEY,
    AGENT_ID           VARCHAR(50) NOT NULL,
    NODE_ID            INTEGER NOT NULL,
    HIERARCHY_TYPE_ID  INTEGER NOT NULL,
    IS_PRIMARY         BOOLEAN NOT NULL,
    EFFECTIVE_FROM     DATE NOT NULL,
    EFFECTIVE_TO       DATE,
    REMARKS            VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE

    -- Optional FK: Uncomment if AGENT table and AGENT_ID type match
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_HISTORY (
    HISTORY_ID            INTEGER PRIMARY KEY,
    AGENT_ID              VARCHAR(50) NOT NULL,
    HIERARCHY_TYPE_ID     INTEGER NOT NULL,
    OLD_NODE_ID           INTEGER,
    NEW_NODE_ID           INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANGE_REASON         VARCHAR(100),
    CHANGED_BY            VARCHAR(100) NOT NULL,
    CHANGED_DATE          TIMESTAMP NOT NULL,
    REMARKS               TEXT,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_node
        FOREIGN KEY (OLD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_node
        FOREIGN KEY (NEW_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE

    -- Optional: Uncomment if AGENT table exists
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.AGENT (
    AGENT_ID             INTEGER PRIMARY KEY,
    AGENT_CODE           VARCHAR(50) NOT NULL UNIQUE,
    AGENT_TYPE_CODE      VARCHAR(20),
    AGENT_SUB_TYPE_CODE  VARCHAR(20),
    AGENT_NAME           VARCHAR(150),
    BUSINESS_NAME        VARCHAR(300),
    FIRST_NAME           VARCHAR(150),
    MIDDLE_NAME          VARCHAR(150),
    LAST_NAME            VARCHAR(150),
    PREFIX               VARCHAR(20),
    SUFFIX               VARCHAR(20),
    GENDER               VARCHAR(10),
    DOB                  DATE,
    NATIONALITY          VARCHAR(40),
    MARITAL_STATUS_CODE  VARCHAR(20),
    PREFERRED_LANGUAGE   VARCHAR(22),
    CHANNEL_CODE         VARCHAR(20),
    SUB_CHANNEL_CODE     VARCHAR(20),
    DESIGNATION_CODE     VARCHAR(20),
    AGENT_LEVEL          VARCHAR(20),
    LOCATION_CODE        VARCHAR(20),
    STAFF_CODE           VARCHAR(20),
    SUPERVISOR_CODE      VARCHAR(50),
    CONTRACTED_DATE      DATE,
    AGENT_STATUS_CODE    VARCHAR(20),
    STATUS_DATE          DATE,
    IS_LICENSED          BOOLEAN NOT NULL,
    PAN_NUMBER           VARCHAR(40),
    AADHAAR_NUMBER       VARCHAR(40),
    IRDA_LICENSE_NUMBER  VARCHAR(40),
    GST_NUMBER           VARCHAR(100),
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE SET NULL

    -- Add other foreign keys as needed, for example:
    -- CONSTRAINT fk_gender FOREIGN KEY (GENDER) REFERENCES hms.GENDER_MASTER(GENDER_CODE),
    -- CONSTRAINT fk_agent_type FOREIGN KEY (AGENT_TYPE_CODE) REFERENCES hms.AGENT_TYPE_MASTER(AGENT_TYPE_CODE),
    -- etc.
);

CREATE TABLE hms.AGENT_CONTACT (
    AGENT_CONTACT_ID     INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    ADDRESS_TYPE_CODE     VARCHAR(20),
    IS_PRIMARY           BOOLEAN NOT NULL,
    ADDRESS1             VARCHAR(150),
    ADDRESS2             VARCHAR(150),
    ADDRESS3             VARCHAR(150),
    CITY                 VARCHAR(100),
    STATE_CODE           VARCHAR(20),
    PINCODE              VARCHAR(30),
    WEBSITE              VARCHAR(150),
    EMAIL_TYPE_CODE      VARCHAR(20),
    EMAIL_ID             VARCHAR(100),
    PHONE_TYPE_CODE      VARCHAR(20),
    PHONE_NO             VARCHAR(30),
    EXTENSION            VARCHAR(10),
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add foreign keys for *_CODE fields as needed, for example:
    -- , CONSTRAINT fk_address_type FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES hms.ADDRESS_TYPE_MASTER(ADDRESS_TYPE_CODE),
    -- , CONSTRAINT fk_state FOREIGN KEY (STATE_CODE) REFERENCES hms.STATE_MASTER(STATE_CODE),
    -- , CONSTRAINT fk_email_type FOREIGN KEY (EMAIL_TYPE_CODE) REFERENCES hms.EMAIL_TYPE_MASTER(EMAIL_TYPE_CODE),
    -- , CONSTRAINT fk_phone_type FOREIGN KEY (PHONE_TYPE_CODE) REFERENCES hms.PHONE_TYPE_MASTER(PHONE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_DOCUMENT (
    DOCUMENT_ID          SERIAL PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    DOCUMENT_TYPE_CODE   VARCHAR(20) NOT NULL,
    DOCUMENT_NAME        VARCHAR(255) NOT NULL,
    DOCUMENT_PATH        VARCHAR(500),
    ISSUING_AUTHORITY    VARCHAR(100),
    DOCUMENT_NUMBER      VARCHAR(100),
    ISSUE_DATE           DATE,
    EXPIRY_DATE          DATE,
    IS_VERIFIED          BOOLEAN NOT NULL,
    VERIFIED_BY          VARCHAR(50),
    VERIFIED_DATE        TIMESTAMP,
    IS_MANDATORY         BOOLEAN NOT NULL,
    UPLOAD_DATE          TIMESTAMP,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for DOCUMENT_TYPE_CODE if DOCUMENT_TYPE_MASTER exists
    -- , CONSTRAINT fk_document_type FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES hms.DOCUMENT_TYPE_MASTER (DOCUMENT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_LICENSE (
    ID                    BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    LICENSE_NO            VARCHAR(60) NOT NULL,
    LICENSE_TYPE_CODE     VARCHAR(20) NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    LICENSE_STATUS        VARCHAR(40),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for LICENSE_TYPE_CODE if LICENSE_TYPE_MASTER exists
    -- , CONSTRAINT fk_license_type FOREIGN KEY (LICENSE_TYPE_CODE) REFERENCES hms.LICENSE_TYPE_MASTER(LICENSE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_BANK_DETAILS (
    AGENT_BANK_DETAILS_ID INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    BANK_NAME            VARCHAR(100) NOT NULL,
    ACCOUNT_HOLDER_NAME  VARCHAR(100) NOT NULL,
    ACCOUNT_NUMBER       VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE         VARCHAR(20),
    IFSC_CODE            VARCHAR(20),
    BRANCH_NAME          VARCHAR(100),
    MICR_CODE            VARCHAR(20),
    IS_PREFERRED         BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Uncomment and add these foreign keys if master tables exist:
    -- , CONSTRAINT fk_account_type FOREIGN KEY (ACCOUNT_TYPE) REFERENCES hms.ACCOUNT_TYPE_MASTER(ACCOUNT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_STATUS_HISTORY (
    STATUS_HISTORY_ID  INTEGER PRIMARY KEY,
    AGENT_ID          INTEGER NOT NULL,
    STATUS_CODE       VARCHAR(20) NOT NULL,
    REASON_CODE       VARCHAR(20),
    EFFECTIVE_DATE    DATE NOT NULL,
    END_DATE          DATE,
    CHANGED_BY        VARCHAR(50) NOT NULL,
    CHANGED_DATE      TIMESTAMP NOT NULL,
    REMARKS           VARCHAR(1000),
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_status
    --    FOREIGN KEY (STATUS_CODE)
    --    REFERENCES hms.AGENT_STATUS_MASTER (STATUS_CODE),

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.STATUS_REASON_MASTER (REASON_CODE)
);

CREATE TABLE hms.AGENT_MOVEMENT_HISTORY (
    MOVEMENT_ID           BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    OLD_SUPERVISOR_CODE   INTEGER,
    NEW_SUPERVISOR_CODE   INTEGER NOT NULL,
    OLD_DESIGNATION_CODE  INTEGER,
    NEW_DESIGNATION_CODE  INTEGER NOT NULL,
    MOVEMENT_TYPE         VARCHAR(50) NOT NULL,
    REASON_CODE           VARCHAR(20),
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    REMARKS               VARCHAR(1000),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_supervisor
        FOREIGN KEY (OLD_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_supervisor
        FOREIGN KEY (NEW_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_old_designation
    --    FOREIGN KEY (OLD_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE SET NULL,

    --CONSTRAINT fk_new_designation
    --    FOREIGN KEY (NEW_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE CASCADE,

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.MOVEMENT_REASON_MASTER (REASON_CODE)
);


CREATE TABLE hms.AGENT_PAYMENT_METHOD (
    ID                   BIGINT PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    PAYMENT_MODE_CODE    VARCHAR(20) NOT NULL,
    BANK_DETAIL_ID       BIGINT,
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_payment_mode
    --    FOREIGN KEY (PAYMENT_MODE_CODE)
    --    REFERENCES hms.PAYMENT_MODE_MASTER (PAYMENT_MODE_CODE),

    --CONSTRAINT fk_bank_detail
    --    FOREIGN KEY (BANK_DETAIL_ID)
    --    REFERENCES hms.AGENT_BANK_DETAILS (ID)
    --    ON DELETE SET NULL
);

CREATE TABLE hms.AGENT_HIERARCHY (
    HIERARCHY_ID          BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    SUPERVISOR_CODE       INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANNEL_CODE          VARCHAR(20),
    DESIGNATION_CODE      VARCHAR(20),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE CASCADE,

    CONSTRAINT fk_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE),

    CONSTRAINT fk_designation
        FOREIGN KEY (DESIGNATION_CODE)
        REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)*/
);

CREATE TABLE hms.AGENT_RECRUITMENT (
    RECRUITMENT_ID     BIGINT PRIMARY KEY,
    RECRUITER_ID       INTEGER NOT NULL,
    RECRUIT_ID         INTEGER NOT NULL,
    RECRUITMENT_DATE   DATE NOT NULL,
    SOURCE_CHANNEL     VARCHAR(20),
    COMMENTS           VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_recruiter
        FOREIGN KEY (RECRUITER_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_recruit
        FOREIGN KEY (RECRUIT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_source_channel
        FOREIGN KEY (SOURCE_CHANNEL)
        REFERENCES hms.SOURCE_CHANNEL_MASTER (SOURCE_CHANNEL_CODE)*/
);


CREATE TABLE hms.AGENT_TRAINING_HISTORY (
    LEARNING_ID         BIGINT PRIMARY KEY,
    AGENT_ID            INTEGER NOT NULL,
    LEARNING_TYPE       VARCHAR(20) NOT NULL,
    LEARNING_CODE       VARCHAR(50) NOT NULL,
    LEARNING_NAME       VARCHAR(255) NOT NULL,
    ISSUING_AUTHORITY   VARCHAR(100),
    START_DATE          DATE,
    COMPLETION_DATE     DATE,
    EXPIRY_DATE         DATE,
    SCORE               NUMERIC(5,2),
    STATUS_CODE         VARCHAR(20) NOT NULL,
    DOCUMENT_ID         BIGINT,
    CREATED_BY          VARCHAR(100) NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL,
    MODIFIED_BY         VARCHAR(100),
    MODIFIED_DATE       TIMESTAMP,
    ROWVERSION          INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_learning_code
        FOREIGN KEY (LEARNING_CODE)
        REFERENCES hms.LEARNING_CATALOG_MASTER (LEARNING_CODE),

    CONSTRAINT fk_status_code
        FOREIGN KEY (STATUS_CODE)
        REFERENCES hms.TRAINING_STATUS_MASTER (STATUS_CODE),

    CONSTRAINT fk_document
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES hms.AGENT_DOCUMENT (DOCUMENT_ID)
        ON DELETE SET NULL*/
);

CREATE TABLE hms.AGENT_AUDIT_TRAIL (
    AUDIT_ID       BIGINT PRIMARY KEY,
    AGENT_ID       INTEGER NOT NULL,
    FIELD_NAME     VARCHAR(100) NOT NULL,
    OLD_VALUE      VARCHAR(255),
    NEW_VALUE      VARCHAR(255),
    CHANGED_BY     VARCHAR(100) NOT NULL,
    CHANGED_DATE   TIMESTAMP NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_LOCATION_MAPPING (
    MAPPING_ID      BIGINT PRIMARY KEY,
    AGENT_ID        INTEGER NOT NULL,
    BRANCH_CODE     VARCHAR(20),
    LOCATION_CODE   VARCHAR(20),
    IS_PRIMARY      BOOLEAN NOT NULL,
    EFFECTIVE_DATE  DATE,
    END_DATE        DATE,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_branch
        FOREIGN KEY (BRANCH_CODE)
        REFERENCES hms.BRANCH_MASTER (BRANCH_CODE),

    CONSTRAINT fk_location
        FOREIGN KEY (LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)*/
);

CREATE TABLE hms.ORG_USER_MAPPING (
    MAPPING_ID         BIGINT PRIMARY KEY,
    USER_ID            INTEGER NOT NULL,
    NODE_ID            INTEGER NOT NULL,
    HIERARCHY_TYPE_ID  INTEGER NOT NULL,
    IS_PRIMARY         BOOLEAN NOT NULL,
    EFFECTIVE_FROM     DATE,
    EFFECTIVE_TO       DATE,
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
        REFERENCES hms.USER (USER_ID),

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID),

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
);

CREATE TABLE hms.USER_ACCESS_LOG (
    LOG_ID            BIGINT PRIMARY KEY,
    USER_ID           INTEGER NOT NULL,
    LOGIN_TIMESTAMP   TIMESTAMP NOT NULL,
    LOGOUT_TIMESTAMP  TIMESTAMP,
    IP_ADDRESS        VARCHAR(50),
    DEVICE_INFO       VARCHAR(255),
    SESSION_ID        VARCHAR(100),
    STATUS            VARCHAR(20) NOT NULL, -- Expected values: 'SUCCESS', 'FAILURE'
    FAILURE_REASON    VARCHAR(255),
    CREATED_DATE      TIMESTAMP NOT NULL,

    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
        REFERENCES hms.USER (USER_ID)
);

CREATE TABLE hms.HIERARCHY_ORG_UNIT (
    ORG_UNIT_ID     BIGINT PRIMARY KEY,
    NODE_ID         BIGINT NOT NULL,
    REGION_CODE     VARCHAR(20),
    ZONE_CODE       VARCHAR(20),
    BRANCH_CODE     VARCHAR(20),
    LOCATION_CODE   VARCHAR(20),
    IS_ACTIVE       BOOLEAN NOT NULL,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)

    /*CONSTRAINT fk_region
        FOREIGN KEY (REGION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE),

    CONSTRAINT fk_zone
        FOREIGN KEY (ZONE_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE),

    CONSTRAINT fk_branch
        FOREIGN KEY (BRANCH_CODE)
        REFERENCES hms.BRANCH_MASTER (BRANCH_CODE),

    CONSTRAINT fk_location
        FOREIGN KEY (LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)*/
);

CREATE TABLE hms.CHANNEL_MASTER (
    CHANNEL_CODE     VARCHAR(20) PRIMARY KEY,
    CHANNEL_NAME     VARCHAR(100) NOT NULL,
    DESCRIPTION      TEXT,
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.SUBCHANNEL_MASTER (
    SUBCHANNEL_CODE   VARCHAR(20) PRIMARY KEY,
    CHANNEL_CODE      VARCHAR(20) NOT NULL,
    SUBCHANNEL_NAME   VARCHAR(100) NOT NULL,
    DESCRIPTION       TEXT,
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_channel_code
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.DESIGNATION_MASTER (
    DESIGNATION_CODE   VARCHAR(20) PRIMARY KEY,
    DESIGNATION_NAME   VARCHAR(100) NOT NULL,
    CHANNEL_CODE       VARCHAR(20),
    LEVEL              INTEGER,
    IS_ACTIVE          BOOLEAN NOT NULL,
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_channel_code
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.ROLE_MASTER (
    ROLE_ID          INTEGER PRIMARY KEY,
    ROLE_NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION      TEXT,
    IS_SYSTEM_ROLE   BOOLEAN NOT NULL,
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.AGENT_TYPE_MASTER (
    AGENT_TYPE_CODE         VARCHAR(20) PRIMARY KEY,
    AGENT_TYPE_NAME         VARCHAR(100) NOT NULL,
    CHANNEL_CODE            VARCHAR(20),
    REGULATORY_CLASS        VARCHAR(50),
    IS_DISTRIBUTION_PARTNER BOOLEAN NOT NULL,
    IS_ACTIVE               BOOLEAN NOT NULL,
    CREATED_BY              VARCHAR(100) NOT NULL,
    CREATED_DATE            TIMESTAMP NOT NULL,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DATE           TIMESTAMP,
    ROWVERSION              INTEGER,

    CONSTRAINT fk_agent_type_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.AGENT_SUB_TYPE_MASTER (
    AGENT_SUB_TYPE_CODE   VARCHAR(20) PRIMARY KEY,
    AGENT_SUB_TYPE_NAME   VARCHAR(100) NOT NULL,
    AGENT_TYPE_CODE       VARCHAR(20),
    IS_ACTIVE             BOOLEAN NOT NULL,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent_sub_type_to_type
        FOREIGN KEY (AGENT_TYPE_CODE)
        REFERENCES hms.AGENT_TYPE_MASTER (AGENT_TYPE_CODE)
);

CREATE TABLE hms.LOCATION_MASTER (
    LOCATION_CODE          VARCHAR(20) PRIMARY KEY,
    LOCATION_NAME          VARCHAR(100) NOT NULL,
    LOCATION_TYPE          VARCHAR(20) NOT NULL,
    PARENT_LOCATION_CODE   VARCHAR(20),
    IS_ACTIVE              BOOLEAN NOT NULL,
    CREATED_BY             VARCHAR(100) NOT NULL,
    CREATED_DATE           TIMESTAMP NOT NULL,
    MODIFIED_BY            VARCHAR(100),
    MODIFIED_DATE          TIMESTAMP,
    ROWVERSION             INTEGER,

    CONSTRAINT fk_location_parent
        FOREIGN KEY (PARENT_LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)
);

CREATE TABLE hms.BRANCH_MASTER (
    BRANCH_CODE       VARCHAR(20) PRIMARY KEY,
    BRANCH_NAME       VARCHAR(100) NOT NULL,
    REGION            VARCHAR(50),
    CHANNEL_CODE      VARCHAR(20),
    HEAD_AGENT_ID     VARCHAR(50),
    ADDRESS           TEXT,
    PHONE_NUMBER      VARCHAR(20),
    EMAIL_ID          VARCHAR(100),
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_branch_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE),

    CONSTRAINT fk_branch_head_agent
        FOREIGN KEY (HEAD_AGENT_ID)
        REFERENCES hms.AGENT (AGENT_CODE)
);

CREATE TABLE hms.DOCUMENT_TYPE_MASTER (
    DOCUMENT_TYPE_ID        BIGINT PRIMARY KEY,
    DOCUMENT_TYPE_CODE      VARCHAR(20),
    DOCUMENT_TYPE_NAME      VARCHAR(100),
    IS_MANDATORY            BOOLEAN,
    APPLICABLE_AGENT_TYPE   VARCHAR(50),
    STATUS                  VARCHAR(10),
    CREATED_BY              VARCHAR(100),
    CREATED_DATE            TIMESTAMP,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DATE           TIMESTAMP,
    ROWVERSION              INTEGER,

    CONSTRAINT fk_document_agent_type
        FOREIGN KEY (APPLICABLE_AGENT_TYPE)
        REFERENCES hms.AGENT_TYPE_MASTER (AGENT_TYPE_CODE)
);

CREATE TABLE hms.LEARNING_CATALOG_MASTER (
    LEARNING_CODE      VARCHAR(50) PRIMARY KEY,
    LEARNING_NAME      VARCHAR(255) NOT NULL,
    LEARNING_TYPE      VARCHAR(20) NOT NULL, -- TRAINING / CERTIFICATION
    DURATION           NUMERIC(4,1),          -- e.g., 2.5 hours
    IS_MANDATORY       BOOLEAN NOT NULL,
    STATUS             VARCHAR(10) NOT NULL,  -- Active / Inactive
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER                -- Versioning control
);

CREATE TABLE hms.AGENT_STATUS_MASTER (
    STATUS_CODE     VARCHAR(20) PRIMARY KEY,         -- e.g., ACTIVE, TERMINATED
    STATUS_NAME     VARCHAR(100) NOT NULL,           -- e.g., "Active", "Terminated"
    IS_ACTIVE       BOOLEAN NOT NULL,                -- Indicates if status is in use
    CREATED_BY      VARCHAR(100) NOT NULL,           -- Audit field
    CREATED_DATE    TIMESTAMP NOT NULL,              -- Audit timestamp
    MODIFIED_BY     VARCHAR(100),                    -- Optional modifier
    MODIFIED_DATE   TIMESTAMP,                       -- Optional timestamp
    ROWVERSION      INTEGER                          -- Optional versioning field
);

CREATE TABLE hms.STATUS_REASON_MASTER (
    REASON_CODE     VARCHAR(20) PRIMARY KEY,           -- e.g., RESIGNATION, DECEASED
    REASON_NAME     VARCHAR(100) NOT NULL,             -- Descriptive label
    STATUS_CODE     VARCHAR(20),                       -- FK to AGENT_STATUS_MASTER.STATUS_CODE
    IS_ACTIVE       BOOLEAN NOT NULL,                  -- Indicates if active
    CREATED_BY      VARCHAR(100) NOT NULL,             -- Audit: creator
    CREATED_DATE    TIMESTAMP NOT NULL,                -- Audit: creation timestamp
    MODIFIED_BY     VARCHAR(100),                      -- Audit: who last modified
    MODIFIED_DATE   TIMESTAMP,                         -- Audit: last modification timestamp
    ROWVERSION      INTEGER,                           -- For version control
    CONSTRAINT fk_status_code
        FOREIGN KEY (STATUS_CODE)
        REFERENCES hms.AGENT_STATUS_MASTER (STATUS_CODE)
);

CREATE TABLE hms.MOVEMENT_REASON_MASTER (
    REASON_CODE     VARCHAR(20) PRIMARY KEY,       -- e.g., PROMOTION, TRANSFER
    REASON_NAME     VARCHAR(100) NOT NULL,         -- Descriptive label
    IS_ACTIVE       BOOLEAN NOT NULL,              -- Usage flag
    CREATED_BY      VARCHAR(100) NOT NULL,         -- Audit – creator
    CREATED_DATE    TIMESTAMP NOT NULL,            -- Audit – creation time
    MODIFIED_BY     VARCHAR(100),                  -- Audit – last modified by
    MODIFIED_DATE   TIMESTAMP,                     -- Audit – last modified timestamp
    ROWVERSION      INTEGER                        -- Version control
);

CREATE TABLE hms.MARITAL_STATUS_MASTER (
    MARITAL_STATUS_CODE   VARCHAR(20) PRIMARY KEY,      -- e.g., SINGLE, MARRIED
    MARITAL_STATUS_NAME   VARCHAR(50) NOT NULL,         -- Human-readable label
    IS_ACTIVE              BOOLEAN NOT NULL,             -- Usage flag
    CREATED_BY             VARCHAR(100) NOT NULL,        -- Audit – created by
    CREATED_DATE           TIMESTAMP NOT NULL,           -- Audit – creation timestamp
    MODIFIED_BY            VARCHAR(100),                 -- Audit – last modified by
    MODIFIED_DATE          TIMESTAMP,                    -- Audit – last modification time
    ROWVERSION             INTEGER                       -- For optimistic concurrency
);

CREATE TABLE hms.GENDER_MASTER (
    GENDER_CODE     VARCHAR(10) PRIMARY KEY,         -- e.g., M, F, O
    GENDER_LABEL    VARCHAR(20) NOT NULL,            -- Full name: Male, Female, Other
    IS_ACTIVE       BOOLEAN NOT NULL,                -- Active flag
    CREATED_BY      VARCHAR(100) NOT NULL,           -- Audit: Created by
    CREATED_DATE    TIMESTAMP NOT NULL,              -- Audit: Created timestamp
    MODIFIED_BY     VARCHAR(100),                    -- Audit: Modified by
    MODIFIED_DATE   TIMESTAMP,                       -- Audit: Modified timestamp
    ROWVERSION      INTEGER                          -- For optimistic concurrency control
);

CREATE TABLE hms.LICENSE_TYPE_MASTER (
    LICENSE_TYPE_CODE VARCHAR(20) PRIMARY KEY,       -- e.g., LIFE, GENERAL, COMPOSITE
    LICENSE_TYPE_NAME VARCHAR(100) NOT NULL,         -- Display name, e.g., Life Insurance
    DESCRIPTION VARCHAR(255),                         -- Optional description
    IS_ACTIVE BOOLEAN NOT NULL,                       -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,                 -- Audit: created by
    CREATED_DATE TIMESTAMP NOT NULL,                  -- Audit: creation timestamp
    MODIFIED_BY VARCHAR(100),                         -- Audit: last modified by
    MODIFIED_DATE TIMESTAMP,                          -- Audit: last modified timestamp
    ROWVERSION INTEGER                                -- For optimistic concurrency/versioning
);

CREATE TABLE hms.PAYMENT_MODE_MASTER (
    PAYMENT_MODE_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., NEFT, UPI, CHEQUE, WALLET
    PAYMENT_MODE_NAME VARCHAR(100) NOT NULL,           -- Display label shown on UI
    DESCRIPTION VARCHAR(255),                          -- Optional usage notes or limitations
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,             -- Indicates if this mode is currently allowed (use NUMBER(1) for BOOLEAN)
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit field – who created the record
    CREATED_DATE TIMESTAMP NOT NULL,                     -- Audit – when record was created
    MODIFIED_BY VARCHAR(100 ),                     -- Audit – who last modified it
    MODIFIED_DATE TIMESTAMP,                             -- Audit – when it was modified
    ROWVERSION INTEGER                              -- For optimistic concurrency control
);

CREATE TABLE hms.ADDRESS_TYPE_MASTER (
    ADDRESS_TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., RES, OFF
    ADDRESS_TYPE_NAME VARCHAR(100) NOT NULL,            -- Label e.g., Residence, Office
    DESCRIPTION VARCHAR(255),                           -- Optional notes or clarifications
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,              -- BOOLEAN substitute (1 = true, 0 = false)
    CREATED_BY VARCHAR(100) NOT NULL,             -- Audit – who created it
    CREATED_DATE TIMESTAMP NOT NULL,                      -- Audit – when created
    MODIFIED_BY VARCHAR(100),                      -- Audit – who last updated
    MODIFIED_DATE TIMESTAMP,                             -- Audit – when last updated
    ROWVERSION INTEGER                               -- For optimistic locking
);

CREATE TABLE hms.EMAIL_TYPE_MASTER (
    EMAIL_TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., PERSONAL, OFFICIAL
    EMAIL_TYPE_NAME VARCHAR(100) NOT NULL,             -- Display name e.g., Personal, Official
    DESCRIPTION VARCHAR(255),                         -- Optional clarification or usage notes
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,             -- BOOLEAN substitute (1 = true, 0 = false)
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit – who created the record
    CREATED_DATE TIMESTAMP NOT NULL,                     -- Audit – when the record was created
    MODIFIED_BY VARCHAR(100),                     -- Audit – who last modified the record
    MODIFIED_DATE TIMESTAMP,                            -- Audit – when the record was modified
    ROWVERSION INTEGER                              -- For optimistic locking/versioning
);

CREATE TABLE hms.PHONE_TYPE_MASTER (
    PHONE_TYPE_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., MOBILE, LANDLINE
    PHONE_TYPE_NAME VARCHAR(100) NOT NULL,           -- Display name e.g., Mobile, Landline
    DESCRIPTION VARCHAR(255),                         -- Optional notes for internal use
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,         -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,                 -- Who created the record
    CREATED_DATE TIMESTAMPTZ NOT NULL,                -- When the record was created (with timezone)
    MODIFIED_BY VARCHAR(100),                          -- Who last modified the record
    MODIFIED_DATE TIMESTAMPTZ,                         -- When the record was last modified
    ROWVERSION INTEGER                                -- For optimistic concurrency control
);

CREATE TABLE hms.STATE_MASTER (
    STATE_CODE VARCHAR(20) PRIMARY KEY,            -- e.g., MH, KA
    STATE_NAME VARCHAR(100) NOT NULL,               -- Full state name e.g., Maharashtra
    COUNTRY_CODE VARCHAR(10),                        -- Optional FK to COUNTRY_MASTER
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,        -- Whether the state is in use
    CREATED_BY VARCHAR(100) NOT NULL,                -- Audit field
    CREATED_DATE TIMESTAMPTZ NOT NULL,               -- Audit timestamp
    MODIFIED_BY VARCHAR(100),                         -- Audit field
    MODIFIED_DATE TIMESTAMPTZ,                        -- Audit timestamp
    ROWVERSION INTEGER                                -- Version control
);

CREATE TABLE hms.STATUS_CHANGE_REASON_MASTER (
    REASON_CODE VARCHAR(20) PRIMARY KEY,           -- e.g., RESIGN, DECEASED
    REASON_NAME VARCHAR(100) NOT NULL,              -- Human-readable reason
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,        -- Whether the reason is available for use
    CREATED_BY VARCHAR(100) NOT NULL,                -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,               -- Audit
    MODIFIED_BY VARCHAR(100),                         -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                        -- Audit
    ROWVERSION INTEGER                                -- Audit / version control
);

CREATE TABLE hms.MOVEMENT_TYPE_MASTER (
    TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., TRANSFER, PROMOTION
    TYPE_NAME VARCHAR(100) NOT NULL,            -- Movement Type Description
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,   -- Whether active
    CREATED_BY VARCHAR(100) NOT NULL,           -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,          -- Audit
    MODIFIED_BY VARCHAR(100),                    -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                   -- Audit
    ROWVERSION INTEGER                           -- Audit
);

CREATE TABLE hms.SOURCE_CHANNEL_MASTER (
    SOURCE_CODE VARCHAR(20) PRIMARY KEY,      -- e.g., REFERRAL, WALKIN
    SOURCE_NAME VARCHAR(100) NOT NULL,        -- Descriptive label
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE, -- Whether in use
    CREATED_BY VARCHAR(100) NOT NULL,         -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,        -- Audit
    MODIFIED_BY VARCHAR(100),                  -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                 -- Audit
    ROWVERSION INTEGER                         -- Audit
);

CREATE TABLE hms.ACCOUNT_TYPE_MASTER (
    ACCOUNT_TYPE_CODE VARCHAR(20) PRIMARY KEY,    -- e.g., SAVINGS, CURRENT
    ACCOUNT_TYPE_NAME VARCHAR(100) NOT NULL,      -- Display label
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,     -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,             -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,            -- Audit
    MODIFIED_BY VARCHAR(100),                      -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                     -- Audit
    ROWVERSION INTEGER                             -- Audit
);

CREATE TABLE hms.TRAINING_STATUS_MASTER (
    STATUS_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., ENROLLED, COMPLETED
    STATUS_NAME VARCHAR(100) NOT NULL,           -- Description of the training status
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,     -- Whether active
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit: who created
    CREATED_DATE TIMESTAMPTZ NOT NULL,           -- Audit: when created
    MODIFIED_BY VARCHAR(100),                     -- Audit: who last modified
    MODIFIED_DATE TIMESTAMPTZ,                    -- Audit: when last modified
    ROWVERSION INTEGER                            -- Audit: version control
);


ALTER TABLE hms.User Add COLUMN password_changed_date timestamp with time zone;

CREATE TABLE IF NOT EXISTS hms."api_config"
(
    config_key VARCHAR(50) PRIMARY KEY,
    config_value VARCHAR(20) NOT NULL
);

CREATE TABLE hms."AGENT_MOVEMENT_HISTORY_AUDIT" (
    "AUDIT_ID" SERIAL PRIMARY KEY,
    "MOVEMENT_ID" BIGINT NOT NULL,
    "AGENT_ID" INT NOT NULL,
    "OLD_SUPERVISOR_CODE" INT,
    "NEW_SUPERVISOR_CODE" INT NOT NULL,
    "OLD_DESIGNATION_CODE" INT,
    "NEW_DESIGNATION_CODE" INT NOT NULL,
    "MOVEMENT_TYPE" VARCHAR(50) NOT NULL,
    "REASON_CODE" VARCHAR(20),
    "EFFECTIVE_FROM_DATE" DATE NOT NULL,
    "EFFECTIVE_TO_DATE" DATE,
    "REMARKS" VARCHAR(1000),
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP,
    "REJECTED_BY" VARCHAR(100),
    "REJECTED_DATE" TIMESTAMP,
    "STATUS" VARCHAR(20) NOT NULL,

    -- Audit metadata
    "ACTION" VARCHAR(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    "CHANGED_BY" VARCHAR(100),
    "CHANGED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Termination Request Table
CREATE TABLE hms."agent_termination_request" (
    "REQUEST_ID" SERIAL PRIMARY KEY,
    "AGENT_ID" INT NOT NULL,
    "REQUESTED_BY" VARCHAR(100) NOT NULL,
    "REQUESTED_DATE" TIMESTAMP NOT NULL,
    "REASON" TEXT,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP,
    "REJECTED_BY" VARCHAR(100),
    "REJECTED_DATE" TIMESTAMP
);

-- Audit Table
CREATE TABLE hms."agent_audit" (
    "AUDIT_ID" SERIAL PRIMARY KEY,
    "AGENT_ID" INT NOT NULL,
    "ACTION" VARCHAR(50) NOT NULL,
    "CHANGED_BY" VARCHAR(100) NOT NULL,
    "CHANGED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "OLD_STATUS" VARCHAR(20),
    "NEW_STATUS" VARCHAR(20),
    "REMARKS" TEXT
);

CREATE TABLE hms.errorMaster (
	error_id int4 NOT NULL,
	area varchar(50) NOT NULL,
    error_msg varchar(1000) NOT NULL);

CREATE UNIQUE INDEX ux_errormaster_errorid_area 
    ON hms.errorMaster(error_id, area);

CREATE TABLE hms."applog" (
    "Id" BIGSERIAL PRIMARY KEY,
    "Timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "LogLevel" VARCHAR(20) NOT NULL,
    "Message" TEXT NOT NULL,
    "Exception" TEXT NULL,
    "UserId" VARCHAR(100) NULL,
    "UserName" VARCHAR(200) NULL,
    "SourceFile" VARCHAR(500) NULL,
    "SourceLine" INT NULL,
    "SourceMember" VARCHAR(200) NULL,
    "Category" VARCHAR(200) NULL,
    "StackTrace" TEXT NULL,
    "JobName" VARCHAR(200) NULL
);

CREATE INDEX idx_applog_loglevel ON hms."applog"("LogLevel");
CREATE INDEX idx_applog_jobname  ON hms."applog"("JobName");

CREATE TABLE hms.applog_filter_policy (
  id              SERIAL PRIMARY KEY,
  minimum_level   VARCHAR(20) NOT NULL DEFAULT 'Information',
  excluded_categories TEXT[]   NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE hms.applog_filter_policy (
  id              SERIAL PRIMARY KEY,
  minimum_level   VARCHAR(20) NOT NULL DEFAULT 'Information',
  excluded_categories TEXT[]   NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

INSERT INTO hms.applog_filter_policy (minimum_level, excluded_categories)
VALUES ('Information', ARRAY['Microsoft', 'System.Net.Http']);