CREATE SCHEMA IF NOT EXISTS hms;
CREATE TABLE hms.permissions (
    permission_id   VARCHAR(30) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,
    PRIMARY KEY (permission_id)
);

DROP TABLE hms.permissions;

CREATE TABLE hms.permissions (
    permission_id   INTEGER NOT NULL PRIMARY KEY, -- numeric, not auto-generated
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms.roles (
    role_id         INTEGER NOT NULL PRIMARY KEY,
    role_name       VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    is_system_role  BOOLEAN NOT NULL,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms."user" (
    user_id         SERIAL PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    email_id        VARCHAR(150) NOT NULL,
    mobile_number   VARCHAR(20),
    password        VARCHAR(255) NOT NULL,
    is_active       BOOLEAN NOT NULL,
    is_locked       BOOLEAN NOT NULL,
    last_login_date TIMESTAMP,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);

CREATE TABLE hms.user_role_mapping (
    mapping_id      BIGINT NOT NULL PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    role_id         INTEGER NOT NULL,
    is_primary      BOOLEAN NOT NULL,
    effective_from  DATE NOT NULL,
    effective_to    DATE,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,

    CONSTRAINT fk_user
      FOREIGN KEY (user_id) REFERENCES hms.user(user_id),

    CONSTRAINT fk_role
      FOREIGN KEY (role_id) REFERENCES hms.roles(role_id)
);

CREATE TABLE hms.MENU_MASTER (
    MENU_ID          INTEGER PRIMARY KEY,
    MENU_NAME        VARCHAR(100) NOT NULL,
    PARENT_MENU_ID   INTEGER,  -- Self-referencing FK
    ROUTE_PATH       VARCHAR(255),
    DISPLAY_ORDER    INTEGER,
    IS_ACTIVE        BOOLEAN NOT NULL,
    IS_INTERNAL      BOOLEAN,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER,

    CONSTRAINT fk_parent_menu
        FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE SET NULL
);

CREATE TABLE hms.ROLE_MENU_MAPPING (
    MAPPING_ID     INTEGER PRIMARY KEY,
    ROLE_ID        INTEGER NOT NULL,
    MENU_ID        INTEGER NOT NULL,
    IS_VISIBLE     BOOLEAN NOT NULL,
    IS_ENABLED     BOOLEAN NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_menu
        FOREIGN KEY (MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.PERMISSION_MASTER (
    PERMISSION_ID    INTEGER PRIMARY KEY,
    PERMISSION_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    MODULE_NAME      VARCHAR(50),
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.ROLE_PERMISSION_MAPPING (
    ROLE_ID         INTEGER NOT NULL,
    PERMISSION_ID   INTEGER NOT NULL,
    IS_ALLOWED      BOOLEAN NOT NULL,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_permission
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES hms.PERMISSION_MASTER (PERMISSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_TYPE (
    HIERARCHY_TYPE_ID    INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION          VARCHAR(255),
    IS_ACTIVE            BOOLEAN NOT NULL,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER
);

CREATE TABLE hms.HIERARCHY_NODE (
    NODE_ID           INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID INTEGER NOT NULL,
    NODE_CODE         VARCHAR(50) NOT NULL UNIQUE,
    NODE_NAME         VARCHAR(150) NOT NULL,
    LEVEL             INTEGER,
    LOCATION_CODE     VARCHAR(20),
    BRANCH_CODE       VARCHAR(20),
    PARENT_NODE_ID    INTEGER,
    CHANNEL_CODE      VARCHAR(20),
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL

    -- Optional FKs:
    -- Add these only if LOCATION_MASTER, BRANCH_MASTER, CHANNEL_MASTER exist
    -- and their keys match the types defined below.
    
    -- , CONSTRAINT fk_location
    --     FOREIGN KEY (LOCATION_CODE)
    --     REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)

    -- , CONSTRAINT fk_branch
    --     FOREIGN KEY (BRANCH_CODE)
    --     REFERENCES hms.BRANCH_MASTER (BRANCH_CODE)

    -- , CONSTRAINT fk_channel
    --     FOREIGN KEY (CHANNEL_CODE)
    --     REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.HIERARCHY_STRUCTURE (
    STRUCTURE_ID         INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID    INTEGER NOT NULL,
    PARENT_NODE_ID       INTEGER NOT NULL,
    CHILD_NODE_ID        INTEGER NOT NULL,
    RELATIONSHIP_TYPE    VARCHAR(50),
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM       DATE NOT NULL,
    EFFECTIVE_TO         DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_child_node
        FOREIGN KEY (CHILD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_HIERARCHY_ASSIGNMENT (
    ASSIGNMENT_ID      INTEGER PRIMARY KEY,
    AGENT_ID           VARCHAR(50) NOT NULL,
    NODE_ID            INTEGER NOT NULL,
    HIERARCHY_TYPE_ID  INTEGER NOT NULL,
    IS_PRIMARY         BOOLEAN NOT NULL,
    EFFECTIVE_FROM     DATE NOT NULL,
    EFFECTIVE_TO       DATE,
    REMARKS            VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE

    -- Optional FK: Uncomment if AGENT table and AGENT_ID type match
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_HISTORY (
    HISTORY_ID            INTEGER PRIMARY KEY,
    AGENT_ID              VARCHAR(50) NOT NULL,
    HIERARCHY_TYPE_ID     INTEGER NOT NULL,
    OLD_NODE_ID           INTEGER,
    NEW_NODE_ID           INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANGE_REASON         VARCHAR(100),
    CHANGED_BY            VARCHAR(100) NOT NULL,
    CHANGED_DATE          TIMESTAMP NOT NULL,
    REMARKS               TEXT,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_node
        FOREIGN KEY (OLD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_node
        FOREIGN KEY (NEW_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE

    -- Optional: Uncomment if AGENT table exists
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.AGENT (
    AGENT_ID             INTEGER PRIMARY KEY,
    AGENT_CODE           VARCHAR(50) NOT NULL UNIQUE,
    AGENT_TYPE_CODE      VARCHAR(20),
    AGENT_SUB_TYPE_CODE  VARCHAR(20),
    AGENT_NAME           VARCHAR(150),
    BUSINESS_NAME        VARCHAR(300),
    FIRST_NAME           VARCHAR(150),
    MIDDLE_NAME          VARCHAR(150),
    LAST_NAME            VARCHAR(150),
    PREFIX               VARCHAR(20),
    SUFFIX               VARCHAR(20),
    GENDER               VARCHAR(10),
    DOB                  DATE,
    NATIONALITY          VARCHAR(40),
    MARITAL_STATUS_CODE  VARCHAR(20),
    PREFERRED_LANGUAGE   VARCHAR(22),
    CHANNEL_CODE         VARCHAR(20),
    SUB_CHANNEL_CODE     VARCHAR(20),
    DESIGNATION_CODE     VARCHAR(20),
    AGENT_LEVEL          VARCHAR(20),
    LOCATION_CODE        VARCHAR(20),
    STAFF_CODE           VARCHAR(20),
    SUPERVISOR_CODE      VARCHAR(50),
    CONTRACTED_DATE      DATE,
    AGENT_STATUS_CODE    VARCHAR(20),
    STATUS_DATE          DATE,
    IS_LICENSED          BOOLEAN NOT NULL,
    PAN_NUMBER           VARCHAR(40),
    AADHAAR_NUMBER       VARCHAR(40),
    IRDA_LICENSE_NUMBER  VARCHAR(40),
    GST_NUMBER           VARCHAR(100),
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE SET NULL

    -- Add other foreign keys as needed, for example:
    -- CONSTRAINT fk_gender FOREIGN KEY (GENDER) REFERENCES hms.GENDER_MASTER(GENDER_CODE),
    -- CONSTRAINT fk_agent_type FOREIGN KEY (AGENT_TYPE_CODE) REFERENCES hms.AGENT_TYPE_MASTER(AGENT_TYPE_CODE),
    -- etc.
);

CREATE TABLE hms.AGENT_CONTACT (
    AGENT_CONTACT_ID     INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    ADDRESS_TYPE_CODE     VARCHAR(20),
    IS_PRIMARY           BOOLEAN NOT NULL,
    ADDRESS1             VARCHAR(150),
    ADDRESS2             VARCHAR(150),
    ADDRESS3             VARCHAR(150),
    CITY                 VARCHAR(100),
    STATE_CODE           VARCHAR(20),
    PINCODE              VARCHAR(30),
    WEBSITE              VARCHAR(150),
    EMAIL_TYPE_CODE      VARCHAR(20),
    EMAIL_ID             VARCHAR(100),
    PHONE_TYPE_CODE      VARCHAR(20),
    PHONE_NO             VARCHAR(30),
    EXTENSION            VARCHAR(10),
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add foreign keys for *_CODE fields as needed, for example:
    -- , CONSTRAINT fk_address_type FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES hms.ADDRESS_TYPE_MASTER(ADDRESS_TYPE_CODE),
    -- , CONSTRAINT fk_state FOREIGN KEY (STATE_CODE) REFERENCES hms.STATE_MASTER(STATE_CODE),
    -- , CONSTRAINT fk_email_type FOREIGN KEY (EMAIL_TYPE_CODE) REFERENCES hms.EMAIL_TYPE_MASTER(EMAIL_TYPE_CODE),
    -- , CONSTRAINT fk_phone_type FOREIGN KEY (PHONE_TYPE_CODE) REFERENCES hms.PHONE_TYPE_MASTER(PHONE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_DOCUMENT (
    DOCUMENT_ID          SERIAL PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    DOCUMENT_TYPE_CODE   VARCHAR(20) NOT NULL,
    DOCUMENT_NAME        VARCHAR(255) NOT NULL,
    DOCUMENT_PATH        VARCHAR(500),
    ISSUING_AUTHORITY    VARCHAR(100),
    DOCUMENT_NUMBER      VARCHAR(100),
    ISSUE_DATE           DATE,
    EXPIRY_DATE          DATE,
    IS_VERIFIED          BOOLEAN NOT NULL,
    VERIFIED_BY          VARCHAR(50),
    VERIFIED_DATE        TIMESTAMP,
    IS_MANDATORY         BOOLEAN NOT NULL,
    UPLOAD_DATE          TIMESTAMP,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for DOCUMENT_TYPE_CODE if DOCUMENT_TYPE_MASTER exists
    -- , CONSTRAINT fk_document_type FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES hms.DOCUMENT_TYPE_MASTER (DOCUMENT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_LICENSE (
    ID                    BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    LICENSE_NO            VARCHAR(60) NOT NULL,
    LICENSE_TYPE_CODE     VARCHAR(20) NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    LICENSE_STATUS        VARCHAR(40),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for LICENSE_TYPE_CODE if LICENSE_TYPE_MASTER exists
    -- , CONSTRAINT fk_license_type FOREIGN KEY (LICENSE_TYPE_CODE) REFERENCES hms.LICENSE_TYPE_MASTER(LICENSE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_BANK_DETAILS (
    AGENT_BANK_DETAILS_ID INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    BANK_NAME            VARCHAR(100) NOT NULL,
    ACCOUNT_HOLDER_NAME  VARCHAR(100) NOT NULL,
    ACCOUNT_NUMBER       VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE         VARCHAR(20),
    IFSC_CODE            VARCHAR(20),
    BRANCH_NAME          VARCHAR(100),
    MICR_CODE            VARCHAR(20),
    IS_PREFERRED         BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Uncomment and add these foreign keys if master tables exist:
    -- , CONSTRAINT fk_account_type FOREIGN KEY (ACCOUNT_TYPE) REFERENCES hms.ACCOUNT_TYPE_MASTER(ACCOUNT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_STATUS_HISTORY (
    STATUS_HISTORY_ID  INTEGER PRIMARY KEY,
    AGENT_ID          INTEGER NOT NULL,
    STATUS_CODE       VARCHAR(20) NOT NULL,
    REASON_CODE       VARCHAR(20),
    EFFECTIVE_DATE    DATE NOT NULL,
    END_DATE          DATE,
    CHANGED_BY        VARCHAR(50) NOT NULL,
    CHANGED_DATE      TIMESTAMP NOT NULL,
    REMARKS           VARCHAR(1000),
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_status
    --    FOREIGN KEY (STATUS_CODE)
    --    REFERENCES hms.AGENT_STATUS_MASTER (STATUS_CODE),

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.STATUS_REASON_MASTER (REASON_CODE)
);

CREATE TABLE hms.AGENT_MOVEMENT_HISTORY (
    MOVEMENT_ID           BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    OLD_SUPERVISOR_CODE   INTEGER,
    NEW_SUPERVISOR_CODE   INTEGER NOT NULL,
    OLD_DESIGNATION_CODE  INTEGER,
    NEW_DESIGNATION_CODE  INTEGER NOT NULL,
    MOVEMENT_TYPE         VARCHAR(50) NOT NULL,
    REASON_CODE           VARCHAR(20),
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    REMARKS               VARCHAR(1000),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_supervisor
        FOREIGN KEY (OLD_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_supervisor
        FOREIGN KEY (NEW_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_old_designation
    --    FOREIGN KEY (OLD_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE SET NULL,

    --CONSTRAINT fk_new_designation
    --    FOREIGN KEY (NEW_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE CASCADE,

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.MOVEMENT_REASON_MASTER (REASON_CODE)
);


CREATE TABLE hms.AGENT_PAYMENT_METHOD (
    ID                   BIGINT PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    PAYMENT_MODE_CODE    VARCHAR(20) NOT NULL,
    BANK_DETAIL_ID       BIGINT,
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_payment_mode
    --    FOREIGN KEY (PAYMENT_MODE_CODE)
    --    REFERENCES hms.PAYMENT_MODE_MASTER (PAYMENT_MODE_CODE),

    --CONSTRAINT fk_bank_detail
    --    FOREIGN KEY (BANK_DETAIL_ID)
    --    REFERENCES hms.AGENT_BANK_DETAILS (ID)
    --    ON DELETE SET NULL
);

CREATE TABLE hms.AGENT_HIERARCHY (
    HIERARCHY_ID          BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    SUPERVISOR_CODE       INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANNEL_CODE          VARCHAR(20),
    DESIGNATION_CODE      VARCHAR(20),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE CASCADE,

    CONSTRAINT fk_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE),

    CONSTRAINT fk_designation
        FOREIGN KEY (DESIGNATION_CODE)
        REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)*/
);

CREATE TABLE hms.AGENT_RECRUITMENT (
    RECRUITMENT_ID     BIGINT PRIMARY KEY,
    RECRUITER_ID       INTEGER NOT NULL,
    RECRUIT_ID         INTEGER NOT NULL,
    RECRUITMENT_DATE   DATE NOT NULL,
    SOURCE_CHANNEL     VARCHAR(20),
    COMMENTS           VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_recruiter
        FOREIGN KEY (RECRUITER_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_recruit
        FOREIGN KEY (RECRUIT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_source_channel
        FOREIGN KEY (SOURCE_CHANNEL)
        REFERENCES hms.SOURCE_CHANNEL_MASTER (SOURCE_CHANNEL_CODE)*/
);


CREATE TABLE hms.AGENT_TRAINING_HISTORY (
    LEARNING_ID         BIGINT PRIMARY KEY,
    AGENT_ID            INTEGER NOT NULL,
    LEARNING_TYPE       VARCHAR(20) NOT NULL,
    LEARNING_CODE       VARCHAR(50) NOT NULL,
    LEARNING_NAME       VARCHAR(255) NOT NULL,
    ISSUING_AUTHORITY   VARCHAR(100),
    START_DATE          DATE,
    COMPLETION_DATE     DATE,
    EXPIRY_DATE         DATE,
    SCORE               NUMERIC(5,2),
    STATUS_CODE         VARCHAR(20) NOT NULL,
    DOCUMENT_ID         BIGINT,
    CREATED_BY          VARCHAR(100) NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL,
    MODIFIED_BY         VARCHAR(100),
    MODIFIED_DATE       TIMESTAMP,
    ROWVERSION          INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_learning_code
        FOREIGN KEY (LEARNING_CODE)
        REFERENCES hms.LEARNING_CATALOG_MASTER (LEARNING_CODE),

    CONSTRAINT fk_status_code
        FOREIGN KEY (STATUS_CODE)
        REFERENCES hms.TRAINING_STATUS_MASTER (STATUS_CODE),

    CONSTRAINT fk_document
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES hms.AGENT_DOCUMENT (DOCUMENT_ID)
        ON DELETE SET NULL*/
);

CREATE TABLE hms.AGENT_AUDIT_TRAIL (
    AUDIT_ID       BIGINT PRIMARY KEY,
    AGENT_ID       INTEGER NOT NULL,
    FIELD_NAME     VARCHAR(100) NOT NULL,
    OLD_VALUE      VARCHAR(255),
    NEW_VALUE      VARCHAR(255),
    CHANGED_BY     VARCHAR(100) NOT NULL,
    CHANGED_DATE   TIMESTAMP NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_LOCATION_MAPPING (
    MAPPING_ID      BIGINT PRIMARY KEY,
    AGENT_ID        INTEGER NOT NULL,
    BRANCH_CODE     VARCHAR(20),
    LOCATION_CODE   VARCHAR(20),
    IS_PRIMARY      BOOLEAN NOT NULL,
    EFFECTIVE_DATE  DATE,
    END_DATE        DATE,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_branch
        FOREIGN KEY (BRANCH_CODE)
        REFERENCES hms.BRANCH_MASTER (BRANCH_CODE),

    CONSTRAINT fk_location
        FOREIGN KEY (LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)*/
);
