export const RoutePaths = {
  DASHBOARD: '/dashboard',
  SEARCH: '/search',
  LOGIN: '/login',
  ENTITYMANAGEMENT: '/entitymanagement',
  HIERARCYTOOLS: '/hierarchytools',
  CERTIFICATIONS: '/certifications',
  PENDINGACTIONS: '/pendingactions',
  CHANNELREPORTS: '/channelreports',
  RESOURCES: '/resources',
  CMS: '/cms',
  SETTING: '/setting',
  CODEMOVEMENT: '/dashboard/code-movement',
  CERTIFICATIONUPDATE: '/dashboard/certification-update',
  TERMINATION: '/dashboard/termination',
  BULKACTION: '/dashboard/code-movement/bulk-action',
  CREATEBULK: '/dashboard/create-bulk',
  COMMISSION: '/commission',
   PROCESS_COMMISSION: '/commission/processcommission',
  HOLD_COMMISSION: '/commission/processcommission',
  ADJUST_COMMISSION: '/commission/processcommission',
  APPROVE_COMMISSION: '/commission/processcommission',
  CONFIG_COMMISSION_LIST: '/commission/configcommission-list',
  CONFIG_COMMISSION: '/commission/configcomission',
  CONFIG_COMMISSION_NEW: '/commission/configcommission-list/new-commission-creation',
  COMMISSION_HISTORY: '/commission/configcommission-list/history',
  INBOX: '/inbox',
}
export const STORAGE_KEY = 'ENCRYPTION_ENABLED'
export const NOTIFICATION_CONSTANTS = {
  SUCCESS: 'success' as const,
  ERROR: 'error' as const,
  INFO: 'info' as const,
  WARNING: 'warning' as const,
  ACTION: 'action' as const,
}

export const MASTER_DATA_KEYS = {
  BANK_ACC_TYPE: 'BankAccType',
  AGENT_CLASS: 'AgentClass',
  SALES_SUB_CHANNELS: 'SalesSubChannels',
  STATE: 'State',
  OCCUPATIONS: 'Occupations',
  MARITAL_STATUS: 'MaritalStatus',
  GENDER: 'Gender',
  EDUCATION_QUALIFICATION: 'EducationQualification',
  COUNTRY: 'Country',
  SALES_CHANNELS: 'SalesChannels',
  AGENT_TYPE_CATEGORY: 'AgentTypeCategory',
  SALUTATION: 'Salutation',
  CANDIDATE_TYPE: 'CandidateType',
  AGENT_TYPE: 'AgentType',
  COMMISSION_CLASS:"CommissionClass",
  ADDRESS_TYPE:"AddressType",
  LICENSE_TYPE:"LicenseType",
  LICENCE_STATUS:"LicenseStatus",
  VERTICAL:"Vertical",
  TRAINING_GROUP_TYPE:"TrainingGroupType",
  PAYMENT_MODE:"PaymentMode",
  SUB_CHANNELS:"SubChannel",
  DESIGNATION:"Designation",
  CHANNEL:"Channel",
  Office_Type:"Location",
  Office_Location:"Branch",
}
