export const RoutePaths = {
  DASHBOARD: '/dashboard',
  SEARCH: '/search',
  LOGIN: '/login',
  ENTITYMANAGEMENT: '/entitymanagement',
  HIERARCYTOOLS: '/hierarchytools',
  CERTIFICATIONS: '/certifications',
  PENDINGACTIONS: '/pendingactions',
  CHANNELREPORTS: '/channelreports',
  RESOURCES: '/resources',
  CMS: '/cms',
  SETTING: '/setting',
  CODEMOVEMENT: '/dashboard/code-movement',
  CERTIFICATIONUPDATE: '/dashboard/certification-update',
  TERMINATION: '/dashboard/termination',
  BULKACTION: '/dashboard/code-movement/bulk-action',
}