COPY hms.tempagentdto (
    agentcode, agentname, businessname, firstname, middlename, 
    lastname, prefix, suffix, dob, nationality, preferredlanguage, 
    supervisor_code, islicensed, maskedpannumber, aadhaar_number, irdalicensenumber, 
    gstnumber,createdby,createddate, applicationdocketno, father_husband_nm, panaadharlinkflag, sec206abflag, taxstatus, 
    stateeid, urn, additionalcomment, appointmentdate, incorporationdate, 
    cnctpersondesig, cnctpersonmobileno, cnctpersonemail, cnctpersonname, 
    cmsagenttype, servicetaxno, ulipflag, traininggrouptype, ifs, 
    refreshertrainingcompleted, ismigrated, vertical, branchcode, 
    branchname, ic36trngcompletiondate, strngcompletiondate, 
    confirmationdate, fgrockstartrainingdate, incrementdate, 
    lastpromotiondate, hrdoj, fgvaluetrngdate, hsecpolicytrngdate, 
    itsecpolicytrngdate, npstrngcompletiondate, whistleblowertrngdate, 
    govpolicytrngdate, inductiontrngdate, lastworkingdate, licenseno, 
    licensetype, licenseissuedate, licenseexpirydate, licensestatus, 
    addressline1, addressline2, addressline3, city, state, pin, 
    landmark, comments, reason, orgid, agent_class_desc, bank_acc_type_desc, 
    gender_desc, title_desc, channel_desc, sub_channel_desc, 
    occupation_desc, agent_type_cat_desc, marital_status_desc, 
    education_desc, state_desc, country_desc, designation_code_desc, 
    location_code_desc, agent_type_code_desc, agent_sub_type_code_desc, 
    candidate_type_desc, commission_class_desc, agent_type_desc, 
    nomineename, relationship, percentageshare, nomineeage, 
    accountholdername, accountnumber, ifsc, micr, bankname, 
    accbranchname, accounttype, activesince, factoringhouse, 
    preferredpaymentmode, pannumber, email, mobileno, 
    workcontactno, residencecontactno, bloodgroup, birthplace, 
    educationlevel, workprofile, annualincome, workexpmonths, 
    branch_desc, agent_status_code_desc
) 
FROM STDIN (FORMAT BINARY);


--COPY hms.tempagentdto (
--    agentid, agentcode, agentname, businessname, firstname, middlename, 
--    lastname, prefix, suffix, dob, nationality, preferredlanguage, 
--    agentlevel, staffcode, supervisor_code, contracteddate, statusdate, 
--    islicensed, maskedpannumber, aadhaar_number, irdalicensenumber, 
--    gstnumber, createdby, createddate, modifiedby, modifieddate, 
--    rowversion, applicationdocketno, father_husband_nm, employeecode, 
--    startdate, panaadharlinkflag, sec206abflag, packageid, taxstatus, 
--    stateeid, urn, additionalcomment, appointmentdate, incorporationdate, 
--    cnctpersondesig, cnctpersonmobileno, cnctpersonemail, cnctpersonname, 
--    cmsagenttype, servicetaxno, ulipflag, traininggrouptype, ifs, 
--    refreshertrainingcompleted, ismigrated, mainpartnerclientcode, 
--    agentmaincodevweid, registrationdate, vertical, branchcode, 
--    branchname, ic36trngcompletiondate, strngcompletiondate, 
--    confirmationdate, fgrockstartrainingdate, incrementdate, 
--    lastpromotiondate, hrdoj, fgvaluetrngdate, hsecpolicytrngdate, 
--    itsecpolicytrngdate, npstrngcompletiondate, whistleblowertrngdate, 
--    govpolicytrngdate, inductiontrngdate, lastworkingdate, licenseno, 
--    licensetype, licenseissuedate, licenseexpirydate, licensestatus, 
--    addressline1, addressline2, addressline3, city, state, pin, 
--    landmark, comments, reason, orgid, agent_class_desc, bank_acc_type_desc, 
--    gender_desc, title_desc, channel_desc, sub_channel_desc, 
--    occupation_desc, agent_type_cat_desc, marital_status_desc, 
--    education_desc, state_desc, country_desc, designation_code_desc, 
--    location_code_desc, agent_type_code_desc, agent_sub_type_code_desc, 
--    candidate_type_desc, commission_class_desc, agent_type_desc, 
--    nomineename, relationship, percentageshare, nomineeage, 
--    accountholdername, accountnumber, ifsc, micr, bankname, 
--    accbranchname, accounttype, activesince, factoringhouse, 
--    preferredpaymentmode, dateofbirth, pannumber, email, mobileno, 
--    workcontactno, residencecontactno, bloodgroup, birthplace, 
--    martial_status_desc, pinfo_education_desc, educationlevel, 
--    workprofile, annualincome, workexpmonths, branch_desc, 
--    agent_status_code_desc
--) 
--FROM STDIN (FORMAT BINARY);