CREATE SCHEMA IF NOT EXISTS hms;
CREATE TABLE hms.permissions (
    permission_id   VARCHAR(30) NOT NULL,
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,
    PRIMARY KEY (permission_id)
);

DROP TABLE hms.permissions;

CREATE TABLE hms.permissions (
    permission_id   INTEGER NOT NULL PRIMARY KEY, -- numeric, not auto-generated
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    module_name     VARCHAR(50),
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms.roles (
    role_id         INTEGER NOT NULL PRIMARY KEY,
    role_name       VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    is_system_role  BOOLEAN NOT NULL,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);


CREATE TABLE hms."user" (
    user_id         SERIAL PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    email_id        VARCHAR(150) NOT NULL,
    mobile_number   VARCHAR(20),
    password        VARCHAR(255) NOT NULL,
    is_active       BOOLEAN NOT NULL,
    is_locked       BOOLEAN NOT NULL,
    last_login_date TIMESTAMP,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER
);

CREATE TABLE hms.user_role_mapping (
    mapping_id      BIGINT NOT NULL PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    role_id         INTEGER NOT NULL,
    is_primary      BOOLEAN NOT NULL,
    effective_from  DATE NOT NULL,
    effective_to    DATE,
    is_active       BOOLEAN NOT NULL,
    created_by      VARCHAR(100) NOT NULL,
    created_date    TIMESTAMP NOT NULL,
    modified_by     VARCHAR(100),
    modified_date   TIMESTAMP,
    rowversion      INTEGER,

    CONSTRAINT fk_user
      FOREIGN KEY (user_id) REFERENCES hms.user(user_id),

    CONSTRAINT fk_role
      FOREIGN KEY (role_id) REFERENCES hms.roles(role_id)
);

CREATE TABLE hms.MENU_MASTER (
    MENU_ID          INTEGER PRIMARY KEY,
    MENU_NAME        VARCHAR(100) NOT NULL,
    PARENT_MENU_ID   INTEGER,  -- Self-referencing FK
    ROUTE_PATH       VARCHAR(255),
    DISPLAY_ORDER    INTEGER,
    IS_ACTIVE        BOOLEAN NOT NULL,
    IS_INTERNAL      BOOLEAN,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER,

    CONSTRAINT fk_parent_menu
        FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE SET NULL
);

CREATE TABLE hms.ROLE_MENU_MAPPING (
    MAPPING_ID     INTEGER PRIMARY KEY,
    ROLE_ID        INTEGER NOT NULL,
    MENU_ID        INTEGER NOT NULL,
    IS_VISIBLE     BOOLEAN NOT NULL,
    IS_ENABLED     BOOLEAN NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_menu
        FOREIGN KEY (MENU_ID)
        REFERENCES hms.MENU_MASTER (MENU_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.PERMISSION_MASTER (
    PERMISSION_ID    INTEGER PRIMARY KEY,
    PERMISSION_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION      VARCHAR(255),
    MODULE_NAME      VARCHAR(50),
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.ROLE_PERMISSION_MAPPING (
    ROLE_ID         INTEGER NOT NULL,
    PERMISSION_ID   INTEGER NOT NULL,
    IS_ALLOWED      BOOLEAN NOT NULL,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    CONSTRAINT fk_role
        FOREIGN KEY (ROLE_ID)
        REFERENCES hms.ROLES (ROLE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_permission
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES hms.PERMISSION_MASTER (PERMISSION_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_TYPE (
    HIERARCHY_TYPE_ID    INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_NAME  VARCHAR(100) NOT NULL,
    DESCRIPTION          VARCHAR(255),
    IS_ACTIVE            BOOLEAN NOT NULL,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER
);

CREATE TABLE hms.HIERARCHY_NODE (
    NODE_ID           INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID INTEGER NOT NULL,
    NODE_CODE         VARCHAR(50) NOT NULL UNIQUE,
    NODE_NAME         VARCHAR(150) NOT NULL,
    LEVEL             INTEGER,
    LOCATION_CODE     VARCHAR(20),
    BRANCH_CODE       VARCHAR(20),
    PARENT_NODE_ID    INTEGER,
    CHANNEL_CODE      VARCHAR(20),
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL

    -- Optional FKs:
    -- Add these only if LOCATION_MASTER, BRANCH_MASTER, CHANNEL_MASTER exist
    -- and their keys match the types defined below.
    
    -- , CONSTRAINT fk_location
    --     FOREIGN KEY (LOCATION_CODE)
    --     REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)

    -- , CONSTRAINT fk_branch
    --     FOREIGN KEY (BRANCH_CODE)
    --     REFERENCES hms.BRANCH_MASTER (BRANCH_CODE)

    -- , CONSTRAINT fk_channel
    --     FOREIGN KEY (CHANNEL_CODE)
    --     REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.HIERARCHY_STRUCTURE (
    STRUCTURE_ID         INTEGER PRIMARY KEY,
    HIERARCHY_TYPE_ID    INTEGER NOT NULL,
    PARENT_NODE_ID       INTEGER NOT NULL,
    CHILD_NODE_ID        INTEGER NOT NULL,
    RELATIONSHIP_TYPE    VARCHAR(50),
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM       DATE NOT NULL,
    EFFECTIVE_TO         DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_parent_node
        FOREIGN KEY (PARENT_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_child_node
        FOREIGN KEY (CHILD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_HIERARCHY_ASSIGNMENT (
    ASSIGNMENT_ID      INTEGER PRIMARY KEY,
    AGENT_ID           VARCHAR(50) NOT NULL,
    NODE_ID            INTEGER NOT NULL,
    HIERARCHY_TYPE_ID  INTEGER NOT NULL,
    IS_PRIMARY         BOOLEAN NOT NULL,
    EFFECTIVE_FROM     DATE NOT NULL,
    EFFECTIVE_TO       DATE,
    REMARKS            VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE

    -- Optional FK: Uncomment if AGENT table and AGENT_ID type match
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.HIERARCHY_HISTORY (
    HISTORY_ID            INTEGER PRIMARY KEY,
    AGENT_ID              VARCHAR(50) NOT NULL,
    HIERARCHY_TYPE_ID     INTEGER NOT NULL,
    OLD_NODE_ID           INTEGER,
    NEW_NODE_ID           INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANGE_REASON         VARCHAR(100),
    CHANGED_BY            VARCHAR(100) NOT NULL,
    CHANGED_DATE          TIMESTAMP NOT NULL,
    REMARKS               TEXT,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_node
        FOREIGN KEY (OLD_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_node
        FOREIGN KEY (NEW_NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)
        ON DELETE CASCADE

    -- Optional: Uncomment if AGENT table exists
    -- , CONSTRAINT fk_agent
    --     FOREIGN KEY (AGENT_ID)
    --     REFERENCES hms.AGENT (AGENT_ID)
    --     ON DELETE CASCADE
);

CREATE TABLE hms.AGENT (
    AGENT_ID             INTEGER PRIMARY KEY,
    AGENT_CODE           VARCHAR(50) NOT NULL UNIQUE,
    AGENT_TYPE_CODE      VARCHAR(20),
    AGENT_SUB_TYPE_CODE  VARCHAR(20),
    AGENT_NAME           VARCHAR(150),
    BUSINESS_NAME        VARCHAR(300),
    FIRST_NAME           VARCHAR(150),
    MIDDLE_NAME          VARCHAR(150),
    LAST_NAME            VARCHAR(150),
    PREFIX               VARCHAR(20),
    SUFFIX               VARCHAR(20),
    GENDER               VARCHAR(10),
    DOB                  DATE,
    NATIONALITY          VARCHAR(40),
    MARITAL_STATUS_CODE  VARCHAR(20),
    PREFERRED_LANGUAGE   VARCHAR(22),
    CHANNEL_CODE         VARCHAR(20),
    SUB_CHANNEL_CODE     VARCHAR(20),
    DESIGNATION_CODE     VARCHAR(20),
    AGENT_LEVEL          VARCHAR(20),
    LOCATION_CODE        VARCHAR(20),
    STAFF_CODE           VARCHAR(20),
    SUPERVISOR_CODE      VARCHAR(50),
    CONTRACTED_DATE      DATE,
    AGENT_STATUS_CODE    VARCHAR(20),
    STATUS_DATE          DATE,
    IS_LICENSED          BOOLEAN NOT NULL,
    PAN_NUMBER           VARCHAR(40),
    AADHAAR_NUMBER       VARCHAR(40),
    IRDA_LICENSE_NUMBER  VARCHAR(40),
    GST_NUMBER           VARCHAR(100),
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE SET NULL

    -- Add other foreign keys as needed, for example:
    -- CONSTRAINT fk_gender FOREIGN KEY (GENDER) REFERENCES hms.GENDER_MASTER(GENDER_CODE),
    -- CONSTRAINT fk_agent_type FOREIGN KEY (AGENT_TYPE_CODE) REFERENCES hms.AGENT_TYPE_MASTER(AGENT_TYPE_CODE),
    -- etc.
);

CREATE TABLE hms.AGENT_CONTACT (
    AGENT_CONTACT_ID     INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    ADDRESS_TYPE_CODE     VARCHAR(20),
    IS_PRIMARY           BOOLEAN NOT NULL,
    ADDRESS1             VARCHAR(150),
    ADDRESS2             VARCHAR(150),
    ADDRESS3             VARCHAR(150),
    CITY                 VARCHAR(100),
    STATE_CODE           VARCHAR(20),
    PINCODE              VARCHAR(30),
    WEBSITE              VARCHAR(150),
    EMAIL_TYPE_CODE      VARCHAR(20),
    EMAIL_ID             VARCHAR(100),
    PHONE_TYPE_CODE      VARCHAR(20),
    PHONE_NO             VARCHAR(30),
    EXTENSION            VARCHAR(10),
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add foreign keys for *_CODE fields as needed, for example:
    -- , CONSTRAINT fk_address_type FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES hms.ADDRESS_TYPE_MASTER(ADDRESS_TYPE_CODE),
    -- , CONSTRAINT fk_state FOREIGN KEY (STATE_CODE) REFERENCES hms.STATE_MASTER(STATE_CODE),
    -- , CONSTRAINT fk_email_type FOREIGN KEY (EMAIL_TYPE_CODE) REFERENCES hms.EMAIL_TYPE_MASTER(EMAIL_TYPE_CODE),
    -- , CONSTRAINT fk_phone_type FOREIGN KEY (PHONE_TYPE_CODE) REFERENCES hms.PHONE_TYPE_MASTER(PHONE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_DOCUMENT (
    DOCUMENT_ID          SERIAL PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    DOCUMENT_TYPE_CODE   VARCHAR(20) NOT NULL,
    DOCUMENT_NAME        VARCHAR(255) NOT NULL,
    DOCUMENT_PATH        VARCHAR(500),
    ISSUING_AUTHORITY    VARCHAR(100),
    DOCUMENT_NUMBER      VARCHAR(100),
    ISSUE_DATE           DATE,
    EXPIRY_DATE          DATE,
    IS_VERIFIED          BOOLEAN NOT NULL,
    VERIFIED_BY          VARCHAR(50),
    VERIFIED_DATE        TIMESTAMP,
    IS_MANDATORY         BOOLEAN NOT NULL,
    UPLOAD_DATE          TIMESTAMP,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for DOCUMENT_TYPE_CODE if DOCUMENT_TYPE_MASTER exists
    -- , CONSTRAINT fk_document_type FOREIGN KEY (DOCUMENT_TYPE_CODE) REFERENCES hms.DOCUMENT_TYPE_MASTER (DOCUMENT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_LICENSE (
    ID                    BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    LICENSE_NO            VARCHAR(60) NOT NULL,
    LICENSE_TYPE_CODE     VARCHAR(20) NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    LICENSE_STATUS        VARCHAR(40),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Add FK for LICENSE_TYPE_CODE if LICENSE_TYPE_MASTER exists
    -- , CONSTRAINT fk_license_type FOREIGN KEY (LICENSE_TYPE_CODE) REFERENCES hms.LICENSE_TYPE_MASTER(LICENSE_TYPE_CODE)
);

CREATE TABLE hms.AGENT_BANK_DETAILS (
    AGENT_BANK_DETAILS_ID INTEGER PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    BANK_NAME            VARCHAR(100) NOT NULL,
    ACCOUNT_HOLDER_NAME  VARCHAR(100) NOT NULL,
    ACCOUNT_NUMBER       VARCHAR(50) NOT NULL,
    ACCOUNT_TYPE         VARCHAR(20),
    IFSC_CODE            VARCHAR(20),
    BRANCH_NAME          VARCHAR(100),
    MICR_CODE            VARCHAR(20),
    IS_PREFERRED         BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    -- Uncomment and add these foreign keys if master tables exist:
    -- , CONSTRAINT fk_account_type FOREIGN KEY (ACCOUNT_TYPE) REFERENCES hms.ACCOUNT_TYPE_MASTER(ACCOUNT_TYPE_CODE)
);

CREATE TABLE hms.AGENT_STATUS_HISTORY (
    STATUS_HISTORY_ID  INTEGER PRIMARY KEY,
    AGENT_ID          INTEGER NOT NULL,
    STATUS_CODE       VARCHAR(20) NOT NULL,
    REASON_CODE       VARCHAR(20),
    EFFECTIVE_DATE    DATE NOT NULL,
    END_DATE          DATE,
    CHANGED_BY        VARCHAR(50) NOT NULL,
    CHANGED_DATE      TIMESTAMP NOT NULL,
    REMARKS           VARCHAR(1000),
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_status
    --    FOREIGN KEY (STATUS_CODE)
    --    REFERENCES hms.AGENT_STATUS_MASTER (STATUS_CODE),

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.STATUS_REASON_MASTER (REASON_CODE)
);

CREATE TABLE hms.AGENT_MOVEMENT_HISTORY (
    MOVEMENT_ID           BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    OLD_SUPERVISOR_CODE   INTEGER,
    NEW_SUPERVISOR_CODE   INTEGER NOT NULL,
    OLD_DESIGNATION_CODE  INTEGER,
    NEW_DESIGNATION_CODE  INTEGER NOT NULL,
    MOVEMENT_TYPE         VARCHAR(50) NOT NULL,
    REASON_CODE           VARCHAR(20),
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    REMARKS               VARCHAR(1000),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_old_supervisor
        FOREIGN KEY (OLD_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE SET NULL,

    CONSTRAINT fk_new_supervisor
        FOREIGN KEY (NEW_SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_old_designation
    --    FOREIGN KEY (OLD_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE SET NULL,

    --CONSTRAINT fk_new_designation
    --    FOREIGN KEY (NEW_DESIGNATION_CODE)
    --    REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)
    --    ON DELETE CASCADE,

    --CONSTRAINT fk_reason
    --    FOREIGN KEY (REASON_CODE)
    --    REFERENCES hms.MOVEMENT_REASON_MASTER (REASON_CODE)
);


CREATE TABLE hms.AGENT_PAYMENT_METHOD (
    ID                   BIGINT PRIMARY KEY,
    AGENT_ID             INTEGER NOT NULL,
    PAYMENT_MODE_CODE    VARCHAR(20) NOT NULL,
    BANK_DETAIL_ID       BIGINT,
    IS_ACTIVE            BOOLEAN NOT NULL,
    EFFECTIVE_FROM_DATE  DATE NOT NULL,
    EFFECTIVE_TO_DATE    DATE,
    CREATED_BY           VARCHAR(100) NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    MODIFIED_BY          VARCHAR(100),
    MODIFIED_DATE        TIMESTAMP,
    ROWVERSION           INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    --CONSTRAINT fk_payment_mode
    --    FOREIGN KEY (PAYMENT_MODE_CODE)
    --    REFERENCES hms.PAYMENT_MODE_MASTER (PAYMENT_MODE_CODE),

    --CONSTRAINT fk_bank_detail
    --    FOREIGN KEY (BANK_DETAIL_ID)
    --    REFERENCES hms.AGENT_BANK_DETAILS (ID)
    --    ON DELETE SET NULL
);

CREATE TABLE hms.AGENT_HIERARCHY (
    HIERARCHY_ID          BIGINT PRIMARY KEY,
    AGENT_ID              INTEGER NOT NULL,
    SUPERVISOR_CODE       INTEGER NOT NULL,
    EFFECTIVE_FROM_DATE   DATE NOT NULL,
    EFFECTIVE_TO_DATE     DATE,
    CHANNEL_CODE          VARCHAR(20),
    DESIGNATION_CODE      VARCHAR(20),
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_supervisor
        FOREIGN KEY (SUPERVISOR_CODE)
        REFERENCES hms.AGENT (AGENT_CODE)
        ON DELETE CASCADE,

    CONSTRAINT fk_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE),

    CONSTRAINT fk_designation
        FOREIGN KEY (DESIGNATION_CODE)
        REFERENCES hms.DESIGNATION_MASTER (DESIGNATION_CODE)*/
);

CREATE TABLE hms.AGENT_RECRUITMENT (
    RECRUITMENT_ID     BIGINT PRIMARY KEY,
    RECRUITER_ID       INTEGER NOT NULL,
    RECRUIT_ID         INTEGER NOT NULL,
    RECRUITMENT_DATE   DATE NOT NULL,
    SOURCE_CHANNEL     VARCHAR(20),
    COMMENTS           VARCHAR(1000),
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_recruiter
        FOREIGN KEY (RECRUITER_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_recruit
        FOREIGN KEY (RECRUIT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_source_channel
        FOREIGN KEY (SOURCE_CHANNEL)
        REFERENCES hms.SOURCE_CHANNEL_MASTER (SOURCE_CHANNEL_CODE)*/
);


CREATE TABLE hms.AGENT_TRAINING_HISTORY (
    LEARNING_ID         BIGINT PRIMARY KEY,
    AGENT_ID            INTEGER NOT NULL,
    LEARNING_TYPE       VARCHAR(20) NOT NULL,
    LEARNING_CODE       VARCHAR(50) NOT NULL,
    LEARNING_NAME       VARCHAR(255) NOT NULL,
    ISSUING_AUTHORITY   VARCHAR(100),
    START_DATE          DATE,
    COMPLETION_DATE     DATE,
    EXPIRY_DATE         DATE,
    SCORE               NUMERIC(5,2),
    STATUS_CODE         VARCHAR(20) NOT NULL,
    DOCUMENT_ID         BIGINT,
    CREATED_BY          VARCHAR(100) NOT NULL,
    CREATED_DATE        TIMESTAMP NOT NULL,
    MODIFIED_BY         VARCHAR(100),
    MODIFIED_DATE       TIMESTAMP,
    ROWVERSION          INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_learning_code
        FOREIGN KEY (LEARNING_CODE)
        REFERENCES hms.LEARNING_CATALOG_MASTER (LEARNING_CODE),

    CONSTRAINT fk_status_code
        FOREIGN KEY (STATUS_CODE)
        REFERENCES hms.TRAINING_STATUS_MASTER (STATUS_CODE),

    CONSTRAINT fk_document
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES hms.AGENT_DOCUMENT (DOCUMENT_ID)
        ON DELETE SET NULL*/
);

CREATE TABLE hms.AGENT_AUDIT_TRAIL (
    AUDIT_ID       BIGINT PRIMARY KEY,
    AGENT_ID       INTEGER NOT NULL,
    FIELD_NAME     VARCHAR(100) NOT NULL,
    OLD_VALUE      VARCHAR(255),
    NEW_VALUE      VARCHAR(255),
    CHANGED_BY     VARCHAR(100) NOT NULL,
    CHANGED_DATE   TIMESTAMP NOT NULL,
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_DATE   TIMESTAMP NOT NULL,
    MODIFIED_BY    VARCHAR(100),
    MODIFIED_DATE  TIMESTAMP,
    ROWVERSION     INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE
);

CREATE TABLE hms.AGENT_LOCATION_MAPPING (
    MAPPING_ID      BIGINT PRIMARY KEY,
    AGENT_ID        INTEGER NOT NULL,
    BRANCH_CODE     VARCHAR(20),
    LOCATION_CODE   VARCHAR(20),
    IS_PRIMARY      BOOLEAN NOT NULL,
    EFFECTIVE_DATE  DATE,
    END_DATE        DATE,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    CONSTRAINT fk_agent
        FOREIGN KEY (AGENT_ID)
        REFERENCES hms.AGENT (AGENT_ID)
        ON DELETE CASCADE

    /*CONSTRAINT fk_branch
        FOREIGN KEY (BRANCH_CODE)
        REFERENCES hms.BRANCH_MASTER (BRANCH_CODE),

    CONSTRAINT fk_location
        FOREIGN KEY (LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)*/
);

CREATE TABLE hms.ORG_USER_MAPPING (
    MAPPING_ID         BIGINT PRIMARY KEY,
    USER_ID            INTEGER NOT NULL,
    NODE_ID            INTEGER NOT NULL,
    HIERARCHY_TYPE_ID  INTEGER NOT NULL,
    IS_PRIMARY         BOOLEAN NOT NULL,
    EFFECTIVE_FROM     DATE,
    EFFECTIVE_TO       DATE,
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER,

    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
        REFERENCES hms.USER (USER_ID),

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID),

    CONSTRAINT fk_hierarchy_type
        FOREIGN KEY (HIERARCHY_TYPE_ID)
        REFERENCES hms.HIERARCHY_TYPE (HIERARCHY_TYPE_ID)
);

CREATE TABLE hms.USER_ACCESS_LOG (
    LOG_ID            BIGINT PRIMARY KEY,
    USER_ID           INTEGER NOT NULL,
    LOGIN_TIMESTAMP   TIMESTAMP NOT NULL,
    LOGOUT_TIMESTAMP  TIMESTAMP,
    IP_ADDRESS        VARCHAR(50),
    DEVICE_INFO       VARCHAR(255),
    SESSION_ID        VARCHAR(100),
    STATUS            VARCHAR(20) NOT NULL, -- Expected values: 'SUCCESS', 'FAILURE'
    FAILURE_REASON    VARCHAR(255),
    CREATED_DATE      TIMESTAMP NOT NULL,

    CONSTRAINT fk_user
        FOREIGN KEY (USER_ID)
        REFERENCES hms.USER (USER_ID)
);

CREATE TABLE hms.HIERARCHY_ORG_UNIT (
    ORG_UNIT_ID     BIGINT PRIMARY KEY,
    NODE_ID         BIGINT NOT NULL,
    REGION_CODE     VARCHAR(20),
    ZONE_CODE       VARCHAR(20),
    BRANCH_CODE     VARCHAR(20),
    LOCATION_CODE   VARCHAR(20),
    IS_ACTIVE       BOOLEAN NOT NULL,
    CREATED_BY      VARCHAR(100) NOT NULL,
    CREATED_DATE    TIMESTAMP NOT NULL,
    MODIFIED_BY     VARCHAR(100),
    MODIFIED_DATE   TIMESTAMP,
    ROWVERSION      INTEGER,

    CONSTRAINT fk_node
        FOREIGN KEY (NODE_ID)
        REFERENCES hms.HIERARCHY_NODE (NODE_ID)

    /*CONSTRAINT fk_region
        FOREIGN KEY (REGION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE),

    CONSTRAINT fk_zone
        FOREIGN KEY (ZONE_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE),

    CONSTRAINT fk_branch
        FOREIGN KEY (BRANCH_CODE)
        REFERENCES hms.BRANCH_MASTER (BRANCH_CODE),

    CONSTRAINT fk_location
        FOREIGN KEY (LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)*/
);


CREATE TABLE hms.CHANNEL_MASTER (
    CHANNEL_CODE     VARCHAR(20) PRIMARY KEY,
    CHANNEL_NAME     VARCHAR(100) NOT NULL,
    DESCRIPTION      TEXT,
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);



CREATE SEQUENCE hms.designation_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 9008
	CACHE 1
	NO CYCLE; 

CREATE TABLE hms.designation_master (
    designation_id int8 DEFAULT nextval('hms.designation_id_seq'::regclass) not null PRIMARY KEY,
    designation_code   VARCHAR(20) not null unique,
    designation_name   VARCHAR(100) NOT NULL,
    channel_code       VARCHAR(20),
    designation_level  INTEGER,
    is_active          BOOLEAN NOT NULL,
    created_by         VARCHAR(100) NOT NULL,
    created_date       TIMESTAMP NOT NULL,
    modified_by        VARCHAR(100),
    modified_date      TIMESTAMP,
    rowversion         INTEGER,

    CONSTRAINT fk_channel_code
        FOREIGN KEY (channel_code)
        REFERENCES hms.channel_master (channel_code)
);

CREATE TABLE hms.ROLE_MASTER (
    ROLE_ID          INTEGER PRIMARY KEY,
    ROLE_NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION      TEXT,
    IS_SYSTEM_ROLE   BOOLEAN NOT NULL,
    IS_ACTIVE        BOOLEAN NOT NULL,
    CREATED_BY       VARCHAR(100) NOT NULL,
    CREATED_DATE     TIMESTAMP NOT NULL,
    MODIFIED_BY      VARCHAR(100),
    MODIFIED_DATE    TIMESTAMP,
    ROWVERSION       INTEGER
);

CREATE TABLE hms.AGENT_TYPE_MASTER (
    AGENT_TYPE_CODE         VARCHAR(20) PRIMARY KEY,
    AGENT_TYPE_NAME         VARCHAR(100) NOT NULL,
    CHANNEL_CODE            VARCHAR(20),
    REGULATORY_CLASS        VARCHAR(50),
    IS_DISTRIBUTION_PARTNER BOOLEAN NOT NULL,
    IS_ACTIVE               BOOLEAN NOT NULL,
    CREATED_BY              VARCHAR(100) NOT NULL,
    CREATED_DATE            TIMESTAMP NOT NULL,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DATE           TIMESTAMP,
    ROWVERSION              INTEGER,

    CONSTRAINT fk_agent_type_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

CREATE TABLE hms.AGENT_SUB_TYPE_MASTER (
    AGENT_SUB_TYPE_CODE   VARCHAR(20) PRIMARY KEY,
    AGENT_SUB_TYPE_NAME   VARCHAR(100) NOT NULL,
    AGENT_TYPE_CODE       VARCHAR(20),
    IS_ACTIVE             BOOLEAN NOT NULL,
    CREATED_BY            VARCHAR(100) NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    MODIFIED_BY           VARCHAR(100),
    MODIFIED_DATE         TIMESTAMP,
    ROWVERSION            INTEGER,

    CONSTRAINT fk_agent_sub_type_to_type
        FOREIGN KEY (AGENT_TYPE_CODE)
        REFERENCES hms.AGENT_TYPE_MASTER (AGENT_TYPE_CODE)
);

CREATE TABLE hms.LOCATION_MASTER (
    LOCATION_CODE          VARCHAR(20) PRIMARY KEY,
    LOCATION_NAME          VARCHAR(100) NOT NULL,
    LOCATION_TYPE          VARCHAR(20) NOT NULL,
    PARENT_LOCATION_CODE   VARCHAR(20),
    IS_ACTIVE              BOOLEAN NOT NULL,
    CREATED_BY             VARCHAR(100) NOT NULL,
    CREATED_DATE           TIMESTAMP NOT NULL,
    MODIFIED_BY            VARCHAR(100),
    MODIFIED_DATE          TIMESTAMP,
    ROWVERSION             INTEGER,

    CONSTRAINT fk_location_parent
        FOREIGN KEY (PARENT_LOCATION_CODE)
        REFERENCES hms.LOCATION_MASTER (LOCATION_CODE)
);

CREATE TABLE hms.BRANCH_MASTER (
    BRANCH_CODE       VARCHAR(20) PRIMARY KEY,
    BRANCH_NAME       VARCHAR(100) NOT NULL,
    REGION            VARCHAR(50),
    CHANNEL_CODE      VARCHAR(20),
    HEAD_AGENT_ID     VARCHAR(50),
    ADDRESS           TEXT,
    PHONE_NUMBER      VARCHAR(20),
    EMAIL_ID          VARCHAR(100),
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,

    CONSTRAINT fk_branch_channel
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE),

    CONSTRAINT fk_branch_head_agent
        FOREIGN KEY (HEAD_AGENT_ID)
        REFERENCES hms.AGENT (AGENT_CODE)
);

CREATE TABLE hms.DOCUMENT_TYPE_MASTER (
    DOCUMENT_TYPE_ID        BIGINT PRIMARY KEY,
    DOCUMENT_TYPE_CODE      VARCHAR(20),
    DOCUMENT_TYPE_NAME      VARCHAR(100),
    IS_MANDATORY            BOOLEAN,
    APPLICABLE_AGENT_TYPE   VARCHAR(50),
    STATUS                  VARCHAR(10),
    CREATED_BY              VARCHAR(100),
    CREATED_DATE            TIMESTAMP,
    MODIFIED_BY             VARCHAR(100),
    MODIFIED_DATE           TIMESTAMP,
    ROWVERSION              INTEGER,

    CONSTRAINT fk_document_agent_type
        FOREIGN KEY (APPLICABLE_AGENT_TYPE)
        REFERENCES hms.AGENT_TYPE_MASTER (AGENT_TYPE_CODE)
);

CREATE TABLE hms.LEARNING_CATALOG_MASTER (
    LEARNING_CODE      VARCHAR(50) PRIMARY KEY,
    LEARNING_NAME      VARCHAR(255) NOT NULL,
    LEARNING_TYPE      VARCHAR(20) NOT NULL, -- TRAINING / CERTIFICATION
    DURATION           NUMERIC(4,1),          -- e.g., 2.5 hours
    IS_MANDATORY       BOOLEAN NOT NULL,
    STATUS             VARCHAR(10) NOT NULL,  -- Active / Inactive
    CREATED_BY         VARCHAR(100) NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    MODIFIED_BY        VARCHAR(100),
    MODIFIED_DATE      TIMESTAMP,
    ROWVERSION         INTEGER                -- Versioning control
);

CREATE TABLE hms.AGENT_STATUS_MASTER (
    STATUS_CODE     VARCHAR(20) PRIMARY KEY,         -- e.g., ACTIVE, TERMINATED
    STATUS_NAME     VARCHAR(100) NOT NULL,           -- e.g., "Active", "Terminated"
    IS_ACTIVE       BOOLEAN NOT NULL,                -- Indicates if status is in use
    CREATED_BY      VARCHAR(100) NOT NULL,           -- Audit field
    CREATED_DATE    TIMESTAMP NOT NULL,              -- Audit timestamp
    MODIFIED_BY     VARCHAR(100),                    -- Optional modifier
    MODIFIED_DATE   TIMESTAMP,                       -- Optional timestamp
    ROWVERSION      INTEGER                          -- Optional versioning field
);

CREATE TABLE hms.STATUS_REASON_MASTER (
    REASON_CODE     VARCHAR(20) PRIMARY KEY,           -- e.g., RESIGNATION, DECEASED
    REASON_NAME     VARCHAR(100) NOT NULL,             -- Descriptive label
    STATUS_CODE     VARCHAR(20),                       -- FK to AGENT_STATUS_MASTER.STATUS_CODE
    IS_ACTIVE       BOOLEAN NOT NULL,                  -- Indicates if active
    CREATED_BY      VARCHAR(100) NOT NULL,             -- Audit: creator
    CREATED_DATE    TIMESTAMP NOT NULL,                -- Audit: creation timestamp
    MODIFIED_BY     VARCHAR(100),                      -- Audit: who last modified
    MODIFIED_DATE   TIMESTAMP,                         -- Audit: last modification timestamp
    ROWVERSION      INTEGER,                           -- For version control
    CONSTRAINT fk_status_code
        FOREIGN KEY (STATUS_CODE)
        REFERENCES hms.AGENT_STATUS_MASTER (STATUS_CODE)
);

CREATE TABLE hms.MOVEMENT_REASON_MASTER (
    REASON_CODE     VARCHAR(20) PRIMARY KEY,       -- e.g., PROMOTION, TRANSFER
    REASON_NAME     VARCHAR(100) NOT NULL,         -- Descriptive label
    IS_ACTIVE       BOOLEAN NOT NULL,              -- Usage flag
    CREATED_BY      VARCHAR(100) NOT NULL,         -- Audit – creator
    CREATED_DATE    TIMESTAMP NOT NULL,            -- Audit – creation time
    MODIFIED_BY     VARCHAR(100),                  -- Audit – last modified by
    MODIFIED_DATE   TIMESTAMP,                     -- Audit – last modified timestamp
    ROWVERSION      INTEGER                        -- Version control
);

CREATE TABLE hms.MARITAL_STATUS_MASTER (
    MARITAL_STATUS_CODE   VARCHAR(20) PRIMARY KEY,      -- e.g., SINGLE, MARRIED
    MARITAL_STATUS_NAME   VARCHAR(50) NOT NULL,         -- Human-readable label
    IS_ACTIVE              BOOLEAN NOT NULL,             -- Usage flag
    CREATED_BY             VARCHAR(100) NOT NULL,        -- Audit – created by
    CREATED_DATE           TIMESTAMP NOT NULL,           -- Audit – creation timestamp
    MODIFIED_BY            VARCHAR(100),                 -- Audit – last modified by
    MODIFIED_DATE          TIMESTAMP,                    -- Audit – last modification time
    ROWVERSION             INTEGER                       -- For optimistic concurrency
);

CREATE TABLE hms.GENDER_MASTER (
    GENDER_CODE     VARCHAR(10) PRIMARY KEY,         -- e.g., M, F, O
    GENDER_LABEL    VARCHAR(20) NOT NULL,            -- Full name: Male, Female, Other
    IS_ACTIVE       BOOLEAN NOT NULL,                -- Active flag
    CREATED_BY      VARCHAR(100) NOT NULL,           -- Audit: Created by
    CREATED_DATE    TIMESTAMP NOT NULL,              -- Audit: Created timestamp
    MODIFIED_BY     VARCHAR(100),                    -- Audit: Modified by
    MODIFIED_DATE   TIMESTAMP,                       -- Audit: Modified timestamp
    ROWVERSION      INTEGER                          -- For optimistic concurrency control
);

CREATE TABLE hms.LICENSE_TYPE_MASTER (
    LICENSE_TYPE_CODE VARCHAR(20) PRIMARY KEY,       -- e.g., LIFE, GENERAL, COMPOSITE
    LICENSE_TYPE_NAME VARCHAR(100) NOT NULL,         -- Display name, e.g., Life Insurance
    DESCRIPTION VARCHAR(255),                         -- Optional description
    IS_ACTIVE BOOLEAN NOT NULL,                       -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,                 -- Audit: created by
    CREATED_DATE TIMESTAMP NOT NULL,                  -- Audit: creation timestamp
    MODIFIED_BY VARCHAR(100),                         -- Audit: last modified by
    MODIFIED_DATE TIMESTAMP,                          -- Audit: last modified timestamp
    ROWVERSION INTEGER                                -- For optimistic concurrency/versioning
);

CREATE TABLE hms.PAYMENT_MODE_MASTER (
    PAYMENT_MODE_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., NEFT, UPI, CHEQUE, WALLET
    PAYMENT_MODE_NAME VARCHAR(100) NOT NULL,           -- Display label shown on UI
    DESCRIPTION VARCHAR(255),                          -- Optional usage notes or limitations
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,             -- Indicates if this mode is currently allowed (use NUMBER(1) for BOOLEAN)
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit field – who created the record
    CREATED_DATE TIMESTAMP NOT NULL,                     -- Audit – when record was created
    MODIFIED_BY VARCHAR(100 ),                     -- Audit – who last modified it
    MODIFIED_DATE TIMESTAMP,                             -- Audit – when it was modified
    ROWVERSION INTEGER                              -- For optimistic concurrency control
);

CREATE TABLE hms.ADDRESS_TYPE_MASTER (
    ADDRESS_TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., RES, OFF
    ADDRESS_TYPE_NAME VARCHAR(100) NOT NULL,            -- Label e.g., Residence, Office
    DESCRIPTION VARCHAR(255),                           -- Optional notes or clarifications
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,              -- BOOLEAN substitute (1 = true, 0 = false)
    CREATED_BY VARCHAR(100) NOT NULL,             -- Audit – who created it
    CREATED_DATE TIMESTAMP NOT NULL,                      -- Audit – when created
    MODIFIED_BY VARCHAR(100),                      -- Audit – who last updated
    MODIFIED_DATE TIMESTAMP,                             -- Audit – when last updated
    ROWVERSION INTEGER                               -- For optimistic locking
);

CREATE TABLE hms.EMAIL_TYPE_MASTER (
    EMAIL_TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., PERSONAL, OFFICIAL
    EMAIL_TYPE_NAME VARCHAR(100) NOT NULL,             -- Display name e.g., Personal, Official
    DESCRIPTION VARCHAR(255),                         -- Optional clarification or usage notes
    IS_ACTIVE INTEGER DEFAULT 1 NOT NULL,             -- BOOLEAN substitute (1 = true, 0 = false)
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit – who created the record
    CREATED_DATE TIMESTAMP NOT NULL,                     -- Audit – when the record was created
    MODIFIED_BY VARCHAR(100),                     -- Audit – who last modified the record
    MODIFIED_DATE TIMESTAMP,                            -- Audit – when the record was modified
    ROWVERSION INTEGER                              -- For optimistic locking/versioning
);

CREATE TABLE hms.PHONE_TYPE_MASTER (
    PHONE_TYPE_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., MOBILE, LANDLINE
    PHONE_TYPE_NAME VARCHAR(100) NOT NULL,           -- Display name e.g., Mobile, Landline
    DESCRIPTION VARCHAR(255),                         -- Optional notes for internal use
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,         -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,                 -- Who created the record
    CREATED_DATE TIMESTAMPTZ NOT NULL,                -- When the record was created (with timezone)
    MODIFIED_BY VARCHAR(100),                          -- Who last modified the record
    MODIFIED_DATE TIMESTAMPTZ,                         -- When the record was last modified
    ROWVERSION INTEGER                                -- For optimistic concurrency control
);

CREATE TABLE hms.STATE_MASTER (
    STATE_CODE VARCHAR(20) PRIMARY KEY,            -- e.g., MH, KA
    STATE_NAME VARCHAR(100) NOT NULL,               -- Full state name e.g., Maharashtra
    COUNTRY_CODE VARCHAR(10),                        -- Optional FK to COUNTRY_MASTER
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,        -- Whether the state is in use
    CREATED_BY VARCHAR(100) NOT NULL,                -- Audit field
    CREATED_DATE TIMESTAMPTZ NOT NULL,               -- Audit timestamp
    MODIFIED_BY VARCHAR(100),                         -- Audit field
    MODIFIED_DATE TIMESTAMPTZ,                        -- Audit timestamp
    ROWVERSION INTEGER                                -- Version control
);

CREATE TABLE hms.STATUS_CHANGE_REASON_MASTER (
    REASON_CODE VARCHAR(20) PRIMARY KEY,           -- e.g., RESIGN, DECEASED
    REASON_NAME VARCHAR(100) NOT NULL,              -- Human-readable reason
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,        -- Whether the reason is available for use
    CREATED_BY VARCHAR(100) NOT NULL,                -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,               -- Audit
    MODIFIED_BY VARCHAR(100),                         -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                        -- Audit
    ROWVERSION INTEGER                                -- Audit / version control
);

CREATE TABLE hms.MOVEMENT_TYPE_MASTER (
    TYPE_CODE VARCHAR(20) PRIMARY KEY,          -- e.g., TRANSFER, PROMOTION
    TYPE_NAME VARCHAR(100) NOT NULL,            -- Movement Type Description
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,   -- Whether active
    CREATED_BY VARCHAR(100) NOT NULL,           -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,          -- Audit
    MODIFIED_BY VARCHAR(100),                    -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                   -- Audit
    ROWVERSION INTEGER                           -- Audit
);

CREATE TABLE hms.SOURCE_CHANNEL_MASTER (
    SOURCE_CODE VARCHAR(20) PRIMARY KEY,      -- e.g., REFERRAL, WALKIN
    SOURCE_NAME VARCHAR(100) NOT NULL,        -- Descriptive label
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE, -- Whether in use
    CREATED_BY VARCHAR(100) NOT NULL,         -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,        -- Audit
    MODIFIED_BY VARCHAR(100),                  -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                 -- Audit
    ROWVERSION INTEGER                         -- Audit
);

CREATE TABLE hms.ACCOUNT_TYPE_MASTER (
    ACCOUNT_TYPE_CODE VARCHAR(20) PRIMARY KEY,    -- e.g., SAVINGS, CURRENT
    ACCOUNT_TYPE_NAME VARCHAR(100) NOT NULL,      -- Display label
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,     -- Active flag
    CREATED_BY VARCHAR(100) NOT NULL,             -- Audit
    CREATED_DATE TIMESTAMPTZ NOT NULL,            -- Audit
    MODIFIED_BY VARCHAR(100),                      -- Audit
    MODIFIED_DATE TIMESTAMPTZ,                     -- Audit
    ROWVERSION INTEGER                             -- Audit
);

CREATE TABLE hms.TRAINING_STATUS_MASTER (
    STATUS_CODE VARCHAR(20) PRIMARY KEY,         -- e.g., ENROLLED, COMPLETED
    STATUS_NAME VARCHAR(100) NOT NULL,           -- Description of the training status
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,     -- Whether active
    CREATED_BY VARCHAR(100) NOT NULL,            -- Audit: who created
    CREATED_DATE TIMESTAMPTZ NOT NULL,           -- Audit: when created
    MODIFIED_BY VARCHAR(100),                     -- Audit: who last modified
    MODIFIED_DATE TIMESTAMPTZ,                    -- Audit: when last modified
    ROWVERSION INTEGER                            -- Audit: version control
);


ALTER TABLE hms.User Add COLUMN password_changed_date timestamp with time zone;

CREATE TABLE IF NOT EXISTS hms."api_config"
(
    config_key VARCHAR(50) PRIMARY KEY,
    config_value VARCHAR(20) NOT NULL
);

CREATE TABLE hms."AGENT_MOVEMENT_HISTORY_AUDIT" (
    "AUDIT_ID" SERIAL PRIMARY KEY,
    "MOVEMENT_ID" BIGINT NOT NULL,
    "AGENT_ID" INT NOT NULL,
    "OLD_SUPERVISOR_CODE" INT,
    "NEW_SUPERVISOR_CODE" INT NOT NULL,
    "OLD_DESIGNATION_CODE" INT,
    "NEW_DESIGNATION_CODE" INT NOT NULL,
    "MOVEMENT_TYPE" VARCHAR(50) NOT NULL,
    "REASON_CODE" VARCHAR(20),
    "EFFECTIVE_FROM_DATE" DATE NOT NULL,
    "EFFECTIVE_TO_DATE" DATE,
    "REMARKS" VARCHAR(1000),
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP,
    "REJECTED_BY" VARCHAR(100),
    "REJECTED_DATE" TIMESTAMP,
    "STATUS" VARCHAR(20) NOT NULL,

    -- Audit metadata
    "ACTION" VARCHAR(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    "CHANGED_BY" VARCHAR(100),
    "CHANGED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Termination Request Table
CREATE TABLE hms."agent_termination_request" (
    "REQUEST_ID" SERIAL PRIMARY KEY,
    "AGENT_ID" INT NOT NULL,
    "REQUESTED_BY" VARCHAR(100) NOT NULL,
    "REQUESTED_DATE" TIMESTAMP NOT NULL,
    "REASON" TEXT,
    "STATUS" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP,
    "REJECTED_BY" VARCHAR(100),
    "REJECTED_DATE" TIMESTAMP
);

-- Audit Table
CREATE TABLE hms."agent_audit" (
    "AUDIT_ID" SERIAL PRIMARY KEY,
    "AGENT_ID" INT NOT NULL,
    "ACTION" VARCHAR(50) NOT NULL,
    "CHANGED_BY" VARCHAR(100) NOT NULL,
    "CHANGED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "OLD_STATUS" VARCHAR(20),
    "NEW_STATUS" VARCHAR(20),
    "REMARKS" TEXT
);

CREATE TABLE hms.errorMaster (
	error_id int4 NOT NULL,
	area varchar(50) NOT NULL,
    error_msg varchar(1000) NOT NULL);

CREATE UNIQUE INDEX ux_errormaster_errorid_area 
    ON hms.errorMaster(error_id, area);

CREATE TABLE hms."applog" (
    "Id" BIGSERIAL PRIMARY KEY,
    "Timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "LogLevel" VARCHAR(20) NOT NULL,
    "Message" TEXT NOT NULL,
    "Exception" TEXT NULL,
    "UserId" VARCHAR(100) NULL,
    "UserName" VARCHAR(200) NULL,
    "SourceFile" VARCHAR(500) NULL,
    "SourceLine" INT NULL,
    "SourceMember" VARCHAR(200) NULL,
    "Category" VARCHAR(200) NULL,
    "StackTrace" TEXT NULL,
    "JobName" VARCHAR(200) NULL
);

CREATE INDEX idx_applog_loglevel ON hms."applog"("LogLevel");
CREATE INDEX idx_applog_jobname  ON hms."applog"("JobName");

CREATE TABLE hms.applog_filter_policy (
  id              SERIAL PRIMARY KEY,
  minimum_level   VARCHAR(20) NOT NULL DEFAULT 'Information',
  excluded_categories TEXT[]   NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE hms.applog_filter_policy (
  id              SERIAL PRIMARY KEY,
  minimum_level   VARCHAR(20) NOT NULL DEFAULT 'Information',
  excluded_categories TEXT[]   NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

INSERT INTO hms.applog_filter_policy (minimum_level, excluded_categories)
VALUES ('Information', ARRAY['Microsoft', 'System.Net.Http']);

CREATE SCHEMA applogs;
CREATE TABLE applogs."applog" (
    "Id" BIGSERIAL PRIMARY KEY,
    "Timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "LogLevel" VARCHAR(20) NOT NULL,
    "Message" TEXT NOT NULL,
    "Exception" TEXT NULL,
    "UserId" VARCHAR(100) NULL,
    "UserName" VARCHAR(200) NULL,
    "SourceFile" VARCHAR(500) NULL,
    "SourceLine" INT NULL,
    "SourceMember" VARCHAR(200) NULL,
    "Category" VARCHAR(200) NULL,
    "StackTrace" TEXT NULL,
    "JobName" VARCHAR(200) NULL
);
CREATE INDEX idx_applog_loglevel ON applogs."applog"("LogLevel");
CREATE INDEX idx_applog_jobname  ON applogs."applog"("JobName");


CREATE TABLE applogs.applog_filter_policy (
  id              SERIAL PRIMARY KEY,
  minimum_level   VARCHAR(20) NOT NULL DEFAULT 'Information',
  excluded_categories TEXT[]   NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

DROP TABLE hms.applog;
DROP TABLE hms.applog_filter_policy;



-- Index for searching by agent_name (case-insensitive)
CREATE INDEX idx_agent_name ON hms.agent (LOWER(agent_name));

-- Index for searching by email (case-insensitive)
CREATE INDEX idx_agent_email ON hms.agent (LOWER(email));

-- Index for searching by mobile no (exact match)
CREATE INDEX idx_agent_mobileno ON hms.agent (mobileno);

-- Index for searching by PAN (exact match)
CREATE INDEX idx_agent_pan ON hms.agent (pan_number);

-- Index for searching by Aadhaar (exact match)
CREATE INDEX idx_agent_aadhaar ON hms.agent (aadhaar_number);

-- Index for searching by IRDA license (exact match)
CREATE INDEX idx_agent_irda ON hms.agent (irda_license_number);

-- Index for searching by GST number (exact match)
CREATE INDEX idx_agent_gst ON hms.agent (gst_number);

-- Optional: Index to speed up ordering by created_date (useful if frequently sorted by date)
CREATE INDEX idx_agent_created_date ON hms.agent (created_date DESC);

CREATE TABLE hms."Address" (
    "AddressID" BIGINT PRIMARY KEY,
    "AddressType" INTEGER NOT NULL DEFAULT 0,
    "RefKey" INTEGER NOT NULL DEFAULT 0,
    "RefType" INTEGER,
    "AddressLine1" VARCHAR(255) NOT NULL,
    "AddressLine2" VARCHAR(255),
    "AddressLine3" VARCHAR(255),
    "City" VARCHAR(100) NOT NULL,
    "State" VARCHAR(100),
    "Country" VARCHAR(100),
    "PIN" VARCHAR(20),
    "Landmark" VARCHAR(255)
);

ALTER TABLE hms."Address"
ADD CONSTRAINT uq_address_refkey_reftype_addresstype
UNIQUE ("RefKey", "RefType", "AddressType");


CREATE TABLE hms."BankAccount" (
    "Id" SERIAL PRIMARY KEY,
    "RefKey" INTEGER NOT NULL DEFAULT 0,
    "RefType" INTEGER NOT NULL DEFAULT 1,
    "AccountHolderName" VARCHAR(200) NOT NULL,
    "AccountNumber" VARCHAR(50) NOT NULL,
    "IFSC" VARCHAR(20) NOT NULL,
    "MICR" VARCHAR(20) NOT NULL,
    "BankName" VARCHAR(200),
    "BranchName" VARCHAR(200),
    "AccountType" INTEGER NOT NULL DEFAULT 1,
    "ActiveSince" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "FactoringHouse" VARCHAR(200),
    "PreferredPaymentMode" INTEGER NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX "IX_BankAccount_RefKey_RefType"
ON hms."BankAccount" ("RefKey", "RefType");


CREATE TABLE hms."Nominee"
(
    "NomineeID"       SERIAL PRIMARY KEY,
    "RefKey"          INTEGER NOT NULL,
    "RefType"    INTEGER,
    "NomineeName"     VARCHAR(255) NOT NULL,
    "Relationship"    VARCHAR(255) NOT NULL,
    "PercentageShare" NUMERIC(5,2) NOT NULL,
    "IsActive"        BOOLEAN DEFAULT TRUE,
    "NomineeAge"      BIGINT NOT NULL
);


CREATE UNIQUE INDEX "IX_Nominee_RefKey_RefType"
ON hms."Nominee" ("RefKey", "RefType");

CREATE TABLE hms."PersonalInfo"
(
    "PersonalInfoId" SERIAL PRIMARY KEY,
    "RefKey" INTEGER NOT NULL,
    "RefType" INTEGER,
    "DateOfBirth" DATE,
    "PanNumber" VARCHAR(20) null,
    "Email" VARCHAR(255) null,
    "MobileNo" VARCHAR(20) null,
    "WorkContactNo" VARCHAR(20) null,
    "ResidenceContactNo" VARCHAR(20) null,
    "BloodGroup" VARCHAR(10),
    "BirthPlace" VARCHAR(100),
    "MartialStatus" INTEGER,     -- enum stored as int
    "EducationCode" INTEGER,
    "EducationLevel" VARCHAR(200)  null,
    "WorkProfile" VARCHAR(200) null,
    "AnnualIncome" NUMERIC(18,2),
    "WorkExpMonths" INTEGER
);

CREATE UNIQUE INDEX "IX_PersonalInfo_RefKey_RefType"
ON hms."PersonalInfo" ("RefKey", "RefType");

CREATE TABLE hms.FileProcessingTasks (
    Id SERIAL NOT NULL PRIMARY KEY,
    FilePath VARCHAR(500) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    CreatedBy VARCHAR(100) NOT NULL,
    
    -- FileInfo Properties
    FileName VARCHAR(255) NOT NULL,                        -- .NET FileInfo.Name
    FileExtension VARCHAR(50) NOT NULL,                    -- .NET FileInfo.Extension
    FileSize BIGINT NULL,                                  -- .NET FileInfo.Length (in bytes)
    IsReadOnly BOOLEAN NULL,                               -- .NET FileInfo.IsReadOnly
    
    FileCreationTime TIMESTAMP WITHOUT TIME ZONE NULL,     -- .NET FileInfo.CreationTimeUtc
    FileLastWriteTime TIMESTAMP WITHOUT TIME ZONE NULL,    -- .NET FileInfo.LastWriteTimeUtc
    
    -- Numeric fields for tracking row counts
    TotalRows INTEGER NULL,
    RowsProcessed INTEGER NULL,
    RowsRejected INTEGER NULL,
    
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    StartedAt TIMESTAMP WITHOUT TIME ZONE NULL,
    CompletedAt TIMESTAMP WITHOUT TIME ZONE NULL,
    ErrorMessage TEXT NULL
);

-- Optional index for faster polling
CREATE INDEX IX_FileProcessingTasks_Status_CreatedAt
    ON hms.FileProcessingTasks (Status, CreatedAt);

create table hms.Subscriber(
	SubscriberId SERIAL NOT NULL PRIMARY KEY,
	SubscriberName VARCHAR(500) NOT NULL	
);

create table hms.Organisation(
	OrgId SERIAL NOT NULL PRIMARY KEY,
	SubscriberId INTEGER NOT NULL,
	OrgName VARCHAR(500) NOT NULL,
	CONSTRAINT fk_SubscriberId
	FOREIGN KEY (SubscriberId) REFERENCES hms.Subscriber(SubscriberId)
);

CREATE INDEX IX_Organisation_SubscriberId
    ON hms.Organisation (SubscriberId);

create schema app_subscription


CREATE TABLE app_subscription.subscriber (
	subscriberid serial4 NOT NULL,
	subscribername varchar(500) NOT NULL,
	CONSTRAINT subscriber_pkey PRIMARY KEY (subscriberid)
);


CREATE TABLE app_subscription.organisation (
	orgid serial4 NOT NULL,
	subscriberid int4 NOT NULL,
	orgname varchar(500) NOT NULL,
	CONSTRAINT organisation_pkey PRIMARY KEY (orgid)
);
CREATE INDEX ix_organisation_subscriberid ON app_subscription.organisation USING btree (subscriberid);

ALTER TABLE app_subscription.organisation ADD CONSTRAINT fk_subscriberid FOREIGN KEY (subscriberid) REFERENCES app_subscription.subscriber(subscriberid);
ALTER TABLE hms.organisation DROP CONSTRAINT fk_subscriberid;
ALTER TABLE hms."user" DROP CONSTRAINT fks_user_orgid;
DROP TABLE hms.organisation;
DROP TABLE hms.subscriber;

ALTER TABLE hms."user" ADD CONSTRAINT fk_user_orgid FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid);

create table hmsmaster.KeyValueEntries
(
	orgid int4 NOT NULL,
	EntryCategory int not null,
	EntryIdentity int not null,
	EntryDesc int not null,
	EntryParentID int null,
	ActiveStatus boolean null
);


CREATE TABLE hms.tempagentdto (
    AgentId VARCHAR,
    AgentCode VARCHAR,
    AgentTypeCode VARCHAR,
    AgentSubTypeCode VARCHAR,
    AgentName VARCHAR,
    BusinessName VARCHAR,
    FirstName VARCHAR,
    MiddleName VARCHAR,
    LastName VARCHAR,
    Prefix VARCHAR,
    Suffix VARCHAR,
    Gender VARCHAR,
    DOB VARCHAR,
    Nationality VARCHAR,
    MaritalStatusCode VARCHAR,
    PreferredLanguage VARCHAR,
    ChannelCode VARCHAR,
    SubChannelCode VARCHAR,
    DesignationCode VARCHAR,
    Designation VARCHAR,
    AgentLevel VARCHAR,
    LocationCode VARCHAR,
    StaffCode VARCHAR,
    Supervisor_Id VARCHAR,
    ContractedDate VARCHAR,
    AgentStatusCode VARCHAR,
    StatusDate VARCHAR,
    IsLicensed VARCHAR,
    MaskedPanNumber VARCHAR,
    aadhaar_number VARCHAR,
    IrdaLicenseNumber VARCHAR,
    GstNumber VARCHAR,
    CreatedBy VARCHAR,
    CreatedDate VARCHAR,
    ModifiedBy VARCHAR,
    ModifiedDate VARCHAR,
    RowVersion VARCHAR,
    IsActive VARCHAR,
    CandidateType VARCHAR,
    ApplicationDocketNo VARCHAR,
    Title VARCHAR,
    Father_Husband_Nm VARCHAR,
    Channel_Name VARCHAR,
    Sub_Channel VARCHAR,
    EmployeeCode VARCHAR,
    StartDate VARCHAR,
    PanAadharLinkFlag VARCHAR,
    Sec206abFlag VARCHAR,
    PackageID VARCHAR,
    CommissionClass VARCHAR,
    TaxStatus VARCHAR,
    StateEid VARCHAR,
    OccupationCode VARCHAR,
    Occupation VARCHAR,
    URN VARCHAR,
    AdditionalComment VARCHAR,
    AppointmentDate VARCHAR,
    IncorporationDate VARCHAR,
    CnctPersonDesig VARCHAR,
    CnctPersonMobileNo VARCHAR,
    CnctPersonEmail VARCHAR,
    CnctPersonName VARCHAR,
    AgentTypeCategory VARCHAR,
    AgentClassification VARCHAR,
    CMSAgentType VARCHAR,
    ServiceTaxNo VARCHAR,
    UlipFlag VARCHAR,
    TrainingGroupType VARCHAR,
    Ifs VARCHAR,
    RefresherTrainingCompleted VARCHAR,
    IsMigrated VARCHAR,
    MainPartnerClientCode VARCHAR,
    AgentMaincodevwEid VARCHAR,
    RegistrationDate VARCHAR,
    Vertical VARCHAR,
    BranchCode VARCHAR,
    BranchName VARCHAR,
    Ic36TrngCompletionDate VARCHAR,
    STrngCompletionDate VARCHAR,
    ConfirmationDate VARCHAR,
    FgRockstarTrainingDate VARCHAR,
    IncrementDate VARCHAR,
    LastPromotionDate VARCHAR,
    HRDoj VARCHAR,
    FgValueTrngDate VARCHAR,
    HSecPolicyTrngDate VARCHAR,
    ItSecPolicyTrngDate VARCHAR,
    NpsTrngCompletionDate VARCHAR,
    WhistleBlowerTrngDate VARCHAR,
    GovPolicyTrngDate VARCHAR,
    InductionTrngDate VARCHAR,
    LastWorkingDate VARCHAR,
    LicenseNo VARCHAR,
    LicenseType VARCHAR,
    LicenseIssueDate VARCHAR,
    LicenseExpiryDate VARCHAR,
    LicenseStatus VARCHAR,
    addressline1 varchar,
    aaddressline2 varchar,
    addressline3 varchar,
    city varchar,
    state varchar,
    country varchar,
    pin varchar,
    landmark varchar
);




-- DROP FUNCTION hms.get_agentsearch(varchar, varchar, int8, int8, varchar, varchar);

CREATE OR REPLACE FUNCTION hms.get_agentsearch(p_searchcondition character varying DEFAULT NULL::character varying
                                               , p_zone character varying DEFAULT NULL::character varying, p_page_number bigint DEFAULT 1
                                               , p_page_size bigint DEFAULT 10, p_sort_column character varying DEFAULT 'agent_id'::character varying
                                               , p_sort_direction character varying DEFAULT 'ASC'::character varying)
 RETURNS TABLE(agentid integer, agentcode character varying, agenttypecode character varying, agentsubtypecode character varying
               , agentname character varying, businessname character varying, firstname character varying, middlename character varying
               , lastname character varying, prefix character varying, suffix character varying, gender character varying, dob date
               , nationality character varying, maritalstatuscode character varying, preferredlanguage character varying, channelcode character varying
               , subchannelcode character varying, designationcode character varying, agentlevel character varying, locationcode character varying
               , staffcode character varying, contracteddate date, agentstatuscode character varying, statusdate date, islicensed boolean
               , pannumber character varying, aadhaar_number character varying, irdalicensenumber character varying, gstnumber character varying
               , createdby character varying, createddate timestamp without time zone, modifiedby character varying, modifieddate timestamp without time zone
               , rowversion integer, supervisor_id integer, isactive boolean, email character varying, mobileno character varying)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        a.agent_id as AgentId, a.agent_code as AgentCode, a.agent_type_code as AgentTypeCode, 
		a.agent_sub_type_code as AgentSubTypeCode,
        a.agent_name as AgentName, a.business_name as BusinessName, 
		a.first_name as FirstName, a.middle_name as MiddleName,
        a.last_name as LastName, a.prefix as Prefix, a.suffix as Suffix, a.gender as Gender,
        a.dob as DOB, a.nationality as Nationality, a.martial_status as MaritalStatus,
		a.preferred_language as PreferredLanguage,
        a.channel as channel, a.subchannel as subchannel, 
		a.designation_code as DesignationCode,
        a.agent_level as AgentLevel, a.location_code as LocationCode, a.staff_code as StaffCode,
		a.contracted_date as ContractedDate,
        a.agent_status_code as AgentStatusCode, a.status_date as StatusDate, 
		a.is_licensed as IsLicensed,
        a.pan_number as PanNumber, a.aadhaar_number as aadhaar_number, a.irda_license_number as IrdaLicenseNumber,
        a.gst_number as GstNumber, a.created_by as CreatedBy, a.created_date as CreatedDate, a.modified_by as ModifiedBy,
        a.modified_date as ModifiedDate, a.rowversion as RowVersion, a.supervisor_id as Supervisor_Id, a.is_active as IsActive,
        a.email, a.mobileno
    FROM hms.agent a
	WHERE (p_SearchCondition IS NULL OR a.agent_code ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.agent_name ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.email ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.mobileno ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.pan_number ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.aadhaar_number ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.irda_license_number ILIKE '%' || p_SearchCondition || '%')
          or (p_SearchCondition IS NULL OR a.gst_number ILIKE '%' || p_SearchCondition || '%')
		  ORDER BY
        CASE 
            WHEN p_sort_column = 'agent_id' AND upper(p_sort_direction) = 'ASC' THEN a.agent_id
            ELSE NULL
        END ASC,
        CASE 
            WHEN p_sort_column = 'agent_id' AND upper(p_sort_direction) = 'DESC' THEN a.agent_id
            ELSE NULL
        END DESC,
        CASE 
            WHEN p_sort_column = 'agent_name' AND upper(p_sort_direction) = 'ASC' THEN a.agent_name
            ELSE NULL
        END ASC,
        CASE 
            WHEN p_sort_column = 'agent_name' AND upper(p_sort_direction) = 'DESC' THEN a.agent_name
            ELSE NULL
        END DESC,
        CASE 
            WHEN p_sort_column = 'email' AND upper(p_sort_direction) = 'ASC' THEN a.email
            ELSE NULL
        END ASC,
        CASE 
            WHEN p_sort_column = 'email' AND upper(p_sort_direction) = 'DESC' THEN a.email
            ELSE NULL
        END DESC
    OFFSET ((p_page_number - 1) * p_page_size)::INT
    LIMIT p_page_size::INT;
END;
$function$
;

create schema comss;

CREATE TABLE comss.commission_cycle (
    cycleId SERIAL PRIMARY KEY,
    cycleCode VARCHAR(100) NOT NULL,
    orgId INT NOT NULL,
    commissionType VARCHAR(50) NOT NULL,
    countOfEntities NUMERIC DEFAULT 0,
    avgCommission NUMERIC DEFAULT 0,
    Nb_Revenue NUMERIC,
    Nb_Commission NUMERIC,

    CONSTRAINT fk_cycle_org
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId)
);


CREATE TABLE comss.entity_commission (
    cycleId INT NOT NULL,
    orgId INT NOT NULL,
    agent_id INT NOT NULL,
    submittedOn DATE,
    submittedBy INT,
    commissionAmount NUMERIC,
    status VARCHAR(50),

    CONSTRAINT fk_ent_comm_cycle 
        FOREIGN KEY (cycleId) REFERENCES comss.commission_cycle(cycleId),

    CONSTRAINT fk_ent_comm_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId),

    CONSTRAINT fk_ent_comm_agent 
        FOREIGN KEY (agent_id) REFERENCES hms.agent(agent_id),

    CONSTRAINT fk_ent_comm_user 
        FOREIGN KEY (submittedBy) REFERENCES hms.user(user_id)
);

CREATE TABLE comss.performance_snapshots (
    snapshotId SERIAL PRIMARY KEY,
    orgId INT NOT NULL,
    periodFrom DATE NOT NULL,
    periodTo DATE NOT NULL,
    commissionBudget NUMERIC,
    commissionActual NUMERIC,

    CONSTRAINT fk_perf_org
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId)
);

CREATE TABLE comss.individual_commission (
    individualCommissionId SERIAL PRIMARY KEY,
    orgId INT  NULL,
    agent_id INT null,
    agent_name varchar(200),
    agent_code varchar(200),
	submittedOn DATE,
    submittedBy INT,
    status VARCHAR(50),
     CONSTRAINT fk_ent_comm_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId),

    CONSTRAINT fk_ent_comm_agent 
        FOREIGN KEY (agent_id) REFERENCES hms.agent(agent_id),

    CONSTRAINT fk_ent_comm_user 
        FOREIGN KEY (submittedBy) REFERENCES hms.user(user_id)
);

CREATE TABLE comss.adhoc_commission (
    adhocCommissionId SERIAL PRIMARY KEY,
    orgId INT  NULL,
    branchId INT  NULL,
    requestId int null,
    submittedOn DATE,
    submittedBy INT,

    CONSTRAINT fk_ent_comm_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId),

    CONSTRAINT fk_ent_comm_user 
        FOREIGN KEY (submittedBy) REFERENCES hms.user(user_id)
);


CREATE TABLE comss.currentbusscycle (
	currentBussCycleId SERIAL PRIMARY KEY,
	orgId INT  NULL,	
	cycle varchar(100) NULL,
	revenue numeric(18,2),
	commission numeric(18,2),,
	revCommPerct numeric(10,4)
);

create table comss.onholdpayouts (
onhold_payout_id 		SERIAL primary key,
orgId 				  int null, 
agent_id              INT NOT null,
payout_amount         NUMERIC(18,2) NOT null,
hold_reason_desc      VARCHAR(200),
hold_date             DATE NOT null,
release_date          DATE null,
hold_status           VARCHAR(30),
);

CREATE TABLE comss.commission_config (
    commission_config_id serial PRIMARY KEY,
    orgId int null,
    commission_name VARCHAR(255) NOT NULL,
    trigger_cycle varchar(200),
    run_from DATE NOT NULL,
    run_to DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SCHEMA IF NOT EXISTS scheduler;

CREATE TABLE IF NOT EXISTS scheduler.job_config
(
    job_config_id        SERIAL PRIMARY KEY,
    job_name             TEXT NOT NULL,
    job_type             TEXT NOT NULL, -- e.g. "CommissionProcess", "Cleanup"
    enabled              BOOLEAN NOT NULL DEFAULT TRUE,
    trigger_type         TEXT NOT NULL, -- "Cron", "Interval", "OneTime"
    cron_expression      TEXT NULL,     -- when trigger_type = 'Cron'
    interval_seconds     INTEGER NULL,  -- when trigger_type = 'Interval'
    start_at             TIMESTAMPTZ NULL,
    end_at               TIMESTAMPTZ NULL,
    parameters           JSONB NULL,    -- free-form job parameters (optional)
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NULL
);

-- DROP SCHEMA insu_core;

CREATE SCHEMA IF NOT EXISTS insu_core ;

-- DROP TABLE insu_core.policy;

CREATE TABLE insu_core.ins_policy (
	policyref serial4 NOT NULL,
	orgid int4 NOT NULL,
	policyno varchar(20) NULL,
	policysuffix varchar(10) NULL,
	riskstartdt date NULL,
	riskenddt date NULL,
	policyterm int4 NULL,
	prempayingterm int4 NULL,
	proposerclientid varchar(10) NULL,
	lifeinsuredclientid varchar(10) NULL,
	agent_id int4 NULL,
	CONSTRAINT policy_pkey PRIMARY KEY (policyref)
);


ALTER TABLE insu_core.ins_policy ADD CONSTRAINT fk_pol_agent FOREIGN KEY (agent_id) REFERENCES hms.agent(agent_id) ON DELETE CASCADE;
ALTER TABLE insu_core.ins_policy ADD CONSTRAINT fk_pol_org FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid);

-- DROP TABLE insu_core.premium_collected;
CREATE TABLE insu_core.premium_collected (
	premiucollid serial4 NOT NULL,
	orgid int4 NOT NULL,
	policyref int4 NULL,
	premium_received_dt date NULL,
	premium_type int4 NULL,
	premium_amt numeric NULL,
	CONSTRAINT premiucollid_pkey PRIMARY KEY (premiucollid)
);

ALTER TABLE insu_core.premium_collected ADD CONSTRAINT fk_prem_org 
            FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid);
--drop table scheduler.job_exe_hist

create table scheduler.job_exe_hist(
	job_exe_hist_id SERIAL primary key,
	job_config_id int4 not null,
	started_at TIMESTAMPTZ not null default now(),
	finished_at TIMESTAMPTZ  default now(),
	exe_status varchar(10) not null,/*CREATED > STARTED > PROCESSING > FAILURE OR FINISHED*/
	download_lnk varchar(1000) null, /*when the user clicks on the link the API will check if the file is available*/
	/*if the file is not available it will recreate the data from Commission Calculation Table and download the file*/
	/*file will be saved server at path <orgId>/<job_config_id>/job_exe_hist_id/commission_extract.xlsx*/
	orgId int not null,

	constraint fk_job_hist_cfg
        foreign key (job_config_id) references scheduler.job_config(job_config_id),
        
    constraint fk_job_hist_org 
        foreign key (orgId) references app_subscription.organisation(orgId)
);

CREATE TABLE insu_core.tmp_ins_policy (
	tmp_ins_policyid 		 SERIAL primary key,
    orgid                     varchar(20)  NOT NULL,
    policyno                  varchar(20)  NOT NULL,
    policysuffix              varchar(10)  NOT NULL,
    riskstartdt               varchar(20)  NULL,
    riskenddt                 varchar(20)  NULL,
    policyterm                varchar(10)  NULL,
    prempayingterm            varchar(10)  NULL,
    proposerclientid           varchar(20)  NULL,
    lifeinsuredclientid        varchar(20)  NULL,
    agent_id                  varchar(20)  NULL,
    isstaffpolicy              varchar(10)  NULL,
    policysourcecode           varchar(10)  NULL,
    insuredpan                varchar(20)  NULL,
    proposerpan               varchar(20)  NULL,
    insureddob                varchar(20)  NULL,
    proposerdob               varchar(20)  NULL,
    logindt                   varchar(20)  NULL,
    insuredgender              varchar(10)  NULL,
    proposergender             varchar(10)  NULL,
    maturityageinmonths        varchar(10)  NULL,
    modalbasepremium           varchar(20)  NULL,
    modalbaseriderpremium      varchar(20)  NULL,
    comments                  varchar(100)  NULL,
    reason                    varchar(100)  NULL,
    created_at                timestamp  DEFAULT now()
);

CREATE UNIQUE INDEX uq_ins_policy_org_polno_suffix
ON insu_core.ins_policy (orgid, policyno, policysuffix);

--drop table insu_core.customer
create table insu_core.customer(
	clientid serial4 NOT NULL,
	orgid int4 NOT NULL,
	pas_clientid varchar(10) null,
	isstaff bool default false,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ null,
    dob DATE null,
    gender int null,
    constraint fk_pas_cust_org 
        foreign key (orgId) references app_subscription.organisation(orgId)
);

--drop table comss.comm_rate
create table comss.comm_rate(
	comm_rate serial4 NOT NULL,
	orgid int4 NOT NULL,
	prod_code varchar(10) null,
	comm_rate_from DATE null,
	comm_rate_to DATE null,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	created_by VARCHAR(100),
    updated_at TIMESTAMPTZ null,
    updated_by VARCHAR(100),
    constraint fk_pas_comm_org 
        foreign key (orgId) references app_subscription.organisation(orgId)
);

--drop table comss.comm_calc_rslt
create table comss.comm_calc_rslt(
	comm_calc_rslt_id serial4 NOT NULL,
	orgid int4 NOT NULL,
	prod_code varchar(10) null,
    constraint fk_comm_rslt_org 
        foreign key (orgId) references app_subscription.organisation(orgId)
);

--drop table scheduler.job_extns;

CREATE TABLE scheduler.job_extns (
    job_config_id int4 NOT NULL,
    orgId int NOT NULL,
    comments varchar(500),
    filter varchar(10000),

    -- Unique constraint ensures one extension per job config
    CONSTRAINT uq_job_config_id UNIQUE (job_config_id),

    CONSTRAINT fk_job_hist_cfg
        FOREIGN KEY (job_config_id) REFERENCES scheduler.job_config(job_config_id),
        
    CONSTRAINT fk_job_hist_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId)
);

--drop table comss.comm_job_exe_dtls;

CREATE TABLE comss.comm_job_exe_dtls (
    comm_job_exe_dtls_id serial4 NOT NULL,
    job_exe_hist_id int4 NOT NULL,
    orgId int NOT NULL,
    agent_id int not null,
    premiucollid  int not null,
    premium_amt int not null,
    formula varchar(10000),
    comm_amt int4 not null default 0, 
    logs varchar(10000),
    CONSTRAINT fk_job_exe_hist
        FOREIGN KEY (job_exe_hist_id) REFERENCES scheduler.job_exe_hist(job_exe_hist_id),
    
    CONSTRAINT fk_job_hist_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId),
    
    CONSTRAINT fk_agnt_id
        FOREIGN KEY (agent_id) REFERENCES hms.agent(agent_id),
    
    CONSTRAINT fk_prem_coll_id
        FOREIGN KEY (premiucollid) REFERENCES insu_core.premium_collected(premiucollid)      
);
--drop table scheduler.job_exe_logs

create table scheduler.job_exe_logs(
    job_exe_log_id serial4 NOT NULL,
    orgId int NOT NULL,
    job_exe_hist_id int4 NOT NULL,
    created_on TIMESTAMP NOT null default now(),
    exe_logs varchar(10000),
    CONSTRAINT fk_job_exe_log
        FOREIGN KEY (job_exe_hist_id) REFERENCES scheduler.job_exe_hist(job_exe_hist_id),
    
    CONSTRAINT fk_job_log_org 
        FOREIGN KEY (orgId) REFERENCES app_subscription.organisation(orgId)
);

create index idx_exe_logs on scheduler.job_exe_logs(orgId,job_exe_hist_id);
create table insu_core.tmp_premium_collected (
	tmp_premium_coll_id SERIAL primary key,
    orgid varchar(20) not null,
    policyref varchar(20) not null,
    premium_received_dt varchar(20) null,
    premium_type varchar(20) null,
    premium_amt varchar(20) null,
    prem_coll_yr varchar(20) null,
    prem_coll_qtr varchar(20) null,
    prem_coll_fin_yr varchar(20) null,
    comments varchar(20) null,
    reason varchar(200) null,
    created_at timestamp default now()
);

CREATE SEQUENCE hms.geo_hierarchy_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 9008
	CACHE 1
	NO CYCLE;

-- DROP TABLE hms.geo_hierarchy;
CREATE TABLE hms.geo_hierarchy (
	geo_hierarchy_id int8 DEFAULT nextval('hms.geo_hierarchy_id_seq'::regclass) NOT NULL,
	channel_code varchar(20) NOT NULL,
	designation_code varchar(20) NOT NULL,
	created_by varchar(100) NOT NULL,
	created_date timestamp NOT NULL,
	modified_by varchar(100) NULL,
	modified_date timestamp NULL,
	hierarchy_path public.ltree NULL,
	orgid int4 NULL,
	CONSTRAINT geo_hierarchy_pkey PRIMARY KEY (geo_hierarchy_id)
);

-- hms.agent_hierarchy foreign keys
ALTER TABLE hms.geo_hierarchy 
ADD CONSTRAINT fk_channel_code 
FOREIGN KEY (channel_code) 
REFERENCES hms.channel_master (channel_code) ON DELETE CASCADE;

-- Drop the old one first to avoid confusion
DROP FUNCTION IF EXISTS hms.get_geo_hierarchy_by_channel(text, bigint);

CREATE OR REPLACE FUNCTION hms.get_geo_hierarchy_by_channel(p_channel_code text, p_orgid bigint)
 RETURNS jsonb
 LANGUAGE sql
AS $function$
WITH RECURSIVE hierarchy_cte AS (
    -- Step 1: Get the path from hms schema
    SELECT 
        gh.hierarchy_path,
        string_to_array(gh.hierarchy_path::TEXT, '.') AS labels
    FROM hms.geo_hierarchy gh
    WHERE gh.channel_code = p_channel_code AND gh.orgid = p_orgid::int
),
json_tree AS (
    -- Step 2: Leaf node (Agent)
    SELECT 
        array_length(labels, 1) AS lvl,
        jsonb_build_object(
            'designationId', dm.designation_id,
            'designationName', dm.designation_name,
            'designationCode', dm.designation_code,
            'parentLocation', NULL -- Matches DTO Property Name
        ) AS node,
        labels
    FROM hierarchy_cte h
    -- Note: Join with hmsmaster schema
    JOIN hmsmaster.designation_master dm ON dm.designation_id = h.labels[array_length(h.labels, 1)]::int8

    UNION ALL

    -- Step 3: Recursive parents
    SELECT 
        j.lvl - 1,
        jsonb_build_object(
            'designationId', dm.designation_id,
            'designationName', dm.designation_name,
            'designationCode', dm.designation_code,
            'parentLocation', j.node -- Matches DTO Property Name
        ) AS node,
        j.labels
    FROM json_tree j
    JOIN hmsmaster.designation_master dm ON dm.designation_id = j.labels[j.lvl - 1]::int8
    WHERE j.lvl > 1
)
SELECT jsonb_agg(node)
FROM json_tree
WHERE lvl = 1;
$function$;
ALTER TABLE hms.geo_hierarchy 
ADD CONSTRAINT fk_designation_code 
FOREIGN KEY (designation_code) 
REFERENCES hms.designation_master (designation_code) ON DELETE CASCADE;

CREATE TABLE hms.SUBCHANNEL_MASTER (
    SUBCHANNEL_CODE   VARCHAR(20) PRIMARY KEY,
    CHANNEL_CODE      VARCHAR(20) NOT NULL,
    SUBCHANNEL_NAME   VARCHAR(100) NOT NULL,
    DESCRIPTION       TEXT,
    IS_ACTIVE         BOOLEAN NOT NULL,
    CREATED_BY        VARCHAR(100) NOT NULL,
    CREATED_DATE      TIMESTAMP NOT NULL,
    MODIFIED_BY       VARCHAR(100),
    MODIFIED_DATE     TIMESTAMP,
    ROWVERSION        INTEGER,
    orgid             int4 NULL,
    CONSTRAINT fk_channel_code
        FOREIGN KEY (CHANNEL_CODE)
        REFERENCES hms.CHANNEL_MASTER (CHANNEL_CODE)
);

--drop table hmsmaster.financialperiod

CREATE TABLE hmsmaster.financialperiod (
	periodid serial4 NOT NULL,
	orgid int4 NULL,
	effectivefrom date NULL,
	effectiveto date NULL,
	tds_thresholdlimit int4 DEFAULT 0 NULL,
	tds_standardrate numeric DEFAULT 0 NULL,
	nopanrate numeric DEFAULT 0 NULL,
	CONSTRAINT financialperiod_pkey PRIMARY KEY (periodid)
);

-- hmsmaster.financialperiod foreign keys

ALTER TABLE hmsmaster.financialperiod 
ADD CONSTRAINT fk_fin_period_org 
FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid);

CREATE INDEX uqOrgID ON hmsmaster.financialperiod(orgid);

-- comss.adhoc_commission_adhoccommissionid_seq definition

-- DROP SEQUENCE comss.adhoc_commission_adhoccommissionid_seq;

CREATE SEQUENCE comss.agent_period_comms_id_seq
	MINVALUE 0
	NO MAXVALUE
	START 1
	NO CYCLE;

--drop table comss.comms_ledger

CREATE TABLE comss.comms_ledger (
	agent_period_comms_id  int8 DEFAULT nextval('comss.agent_period_comms_id_seq'::regclass) NOT NULL,
	orgid int4 NULL,
	agent_id int4 not null,
	job_exe_hist_id int4 not null ,
	EntryDate timestamp NULL,
	FinPeriodFrom date NULL,
	FinPeriodTo date NULL,
	trans_type varchar(20) not null default 0,
	trans_amt decimal not null default 0,
	bal_comm_amt decimal not null default 0
);

ALTER TABLE comss.comms_ledger 
ADD CONSTRAINT fk_comm_ledger_org 
FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid);

ALTER TABLE comss.comms_ledger 
ADD CONSTRAINT fk_comm_ledger_exe_hist 
FOREIGN KEY (job_exe_hist_id) REFERENCES scheduler.job_exe_hist(job_exe_hist_id);

CREATE INDEX uqOrgID ON comss.comms_ledger (orgid,agent_id, EntryDate,FinPeriodFrom,FinPeriodTo);

CREATE SEQUENCE hmsmaster.location_master_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE hmsmaster.location_master (
    location_master_id  int8 DEFAULT nextval('hmsmaster.location_master_id_seq'::regclass) NOT NULL,
    channel_id int8 not null,
    sub_channel_id int8 not null,
    orgid int4 NULL,
	location_code varchar(20) NOT NULL,
	location_desc varchar(20) NOT NULL,
	is_active bool NOT NULL,
	created_by varchar(100) NOT NULL,
	created_date timestamp NOT NULL,
	modified_by varchar(100) NULL,
	modified_date timestamp NULL,
	rowversion int4 NULL,
	CONSTRAINT location_master_pkey PRIMARY KEY (location_master_id),
	CONSTRAINT uq_loc unique (orgid,channel_id,sub_channel_id,location_code),
	CONSTRAINT fk_location_channel FOREIGN KEY (channel_id) REFERENCES hmsmaster.channel_master(channel_id),
	CONSTRAINT fk_location_subchannel FOREIGN KEY (sub_channel_id) REFERENCES hmsmaster.subchannel_master(sub_channel_id),
	CONSTRAINT fk_location_org FOREIGN KEY (orgid) references  app_subscription.organisation(orgid)
);

CREATE SEQUENCE comss.fy_period_comms_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE comss.comms_fy_ledger (
	fy_period_comms_id  int8 DEFAULT nextval('comss.fy_period_comms_id_seq'::regclass) NOT NULL,
	orgid int4 NULL,
	agent_id int4 not null,
	EntryDate timestamp NULL,
	FinPeriodFrom date NULL,
	FinPeriodTo date NULL,
	bal_comm_amt decimal not null default 0
);

CREATE SEQUENCE hmsmaster.channel_branch_heirarchy_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;


CREATE TABLE hmsmaster.channel_branch_heirarchy (
	channel_location_heirarchy_id int8 DEFAULT nextval('hmsmaster.channel_branch_heirarchy_id_seq'::regclass) NOT NULL,
	orgid int4 NULL,
	channel_id int8 not null,
	sub_channel_id int8 null,
	hierarchy_path public.ltree NULL, -- reference to hmsmaster.branch_master.branch_id
	created_by varchar(100) NOT NULL,
	created_date timestamp NOT NULL,
	modified_by varchar(100) NULL,
	modified_date timestamp NULL,
	effective_from_date date NOT NULL,
	effective_to_date date NULL,
	--level_criteria varchar(1000) null, -- Zone	Region	Area	Branch	Unit
	CONSTRAINT fk_loc_org FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid) ON DELETE cascade,
	CONSTRAINT fk_loc_channel FOREIGN KEY (channel_id) REFERENCES hmsmaster.channel_master(channel_id) ON DELETE cascade,
	CONSTRAINT fk_loc_subchannel FOREIGN KEY (sub_channel_id) REFERENCES hmsmaster.subchannel_master(sub_channel_id) ON DELETE cascade
);

--DROP SEQUENCE hmsmaster.branch_id_seq
CREATE SEQUENCE hmsmaster.branch_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
--drop table hmsmaster.branch_master 
create table hmsmaster.branch_master ( 
	branch_id int8 default nextval('hmsmaster.branch_id_seq'::regclass) not null,
	orgid int4 null,
	branch_code varchar(20) not null, 
	branch_name varchar(100) not null, 
	address text null, 
	state int4 null,
	phone_number varchar(20) null, 
	email_id varchar(100) null, 
	is_active bool not null, 
	location_master_id int8 null, --reference to hmsmaster.channel_location_heirarchy.level_criteria
	created_by varchar(100) not null, 
	created_date timestamp not null, 
	modified_by varchar(100) null, 
	modified_date timestamp null,
	rowversion int4 null, 
	constraint branch_master_pkey primary key (branch_id),
	constraint branch_uq unique (orgid,branch_code),
	CONSTRAINT fk_brmst_orgid FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid),
	CONSTRAINT fk_brmst_loc FOREIGN KEY (location_master_id) REFERENCES hmsmaster.location_master(location_master_id)
);

-- DROP FUNCTION hms.get_geo_hierarchy_by_channel(int8, int8, int8, int8);

CREATE OR REPLACE FUNCTION hms.get_geo_hierarchy_by_channel(p_channel_id bigint, p_subchannel_id bigint, p_orgid bigint, p_branch_id bigint)
 RETURNS jsonb
 LANGUAGE sql
AS $function$
WITH RECURSIVE hierarchy_cte AS (
    -- Step 1: Get the path from hms schema
    SELECT 
        gh.hierarchy_path,
        string_to_array(gh.hierarchy_path::TEXT, '.') AS labels
    FROM hmsmaster.channel_branch_heirarchy gh
    WHERE gh.channel_id = p_channel_id 
          AND (p_subchannel_id IS NULL OR gh.sub_channel_id = p_subchannel_id)
          AND gh.orgid = p_orgid::int
          AND gh.hierarchy_path ~ ('*.' || p_branch_id::text || '.*')::lquery
),
json_tree AS (
    -- Step 2: Leaf node (Agent)
    SELECT 
        array_length(labels, 1) AS lvl,
        jsonb_build_object(
            'branchMasterID', bm.branch_id ,
            'branchCode', bm.branch_code,
            'branchName', bm.branch_name,
            'locationCode', lm.location_code,
            'locationDesc',lm.location_desc,
            'parentLocation', NULL -- Matches DTO Property Name
        ) AS node,
        labels
    FROM hierarchy_cte h
    -- Note: Join with hmsmaster schema
    JOIN hmsmaster.branch_master bm ON bm.branch_id = h.labels[array_length(h.labels, 1)]::int8
    JOIN hmsmaster.location_master lm on bm.location_master_id = lm.location_master_id

    UNION ALL

    -- Step 3: Recursive parents
    SELECT 
        j.lvl - 1,
        jsonb_build_object(
            'branchMasterID', bm.branch_id ,
            'branchCode', bm.branch_code,
            'branchName', bm.branch_name,
            'locationCode', lm.location_code,
            'locationDesc',lm.location_desc,
            'parentLocation', j.node -- Matches DTO Property Name
        ) AS node,
        j.labels
    FROM json_tree j
    JOIN hmsmaster.branch_master bm ON bm.branch_id = j.labels[j.lvl - 1]::int8
    JOIN hmsmaster.location_master lm on bm.location_master_id = lm.location_master_id
    WHERE j.lvl > 1
)
SELECT jsonb_agg(node)
FROM json_tree
WHERE lvl = 1;
$function$
;

CREATE TABLE IF NOT EXISTS hms.temp_manager_update (
    temp_manager_update_id bigserial PRIMARY KEY,
    agent_code varchar(50) NOT NULL,
    supervisor_code varchar(50) NOT NULL,
    effective_date_of_change date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Pending',
    orgid int NOT NULL
);

CREATE TABLE hms.temp_status_update (
    temp_status_update_id bigserial PRIMARY KEY,
    agent_code              varchar(50)  NOT NULL,
    status                  varchar(50)  NOT NULL,
    business_effective_date date         NOT NULL,
    processing_status       varchar(20)  NOT NULL DEFAULT 'Pending',
    comments                varchar(20),
    reason                  text,
    orgid                   int          NOT NULL
);
CREATE SEQUENCE hmsmaster.uicontrolmenu_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

--drop table hmsmaster.uicontrol_master;
create table hmsmaster.uicontrol_master ( 
	uicontrolmenu_id int8,
	ui_object_name varchar(50) not null,
	ui_object_type varchar(50) not null default 'not provided',
	constraint pk_uicontrol_master primary key (uicontrolmenu_id)
);

CREATE SEQUENCE hmsmaster.uicontrol_hierarchy_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

--DROP TABLE hmsmaster.uicontrol_hierarchy;
CREATE TABLE hmsmaster.uicontrol_hierarchy (
	hierarchy_id int8 DEFAULT nextval('hmsmaster.uicontrol_hierarchy_id_seq'::regclass) NOT NULL,
	uicontrolmenu_id int8 not null,
	hierarchy_path public.ltree null,
	constraint pk_uicontrol_hierarchy primary key (hierarchy_id),
	constraint control_heirarchy_uq unique (hierarchy_path),
	CONSTRAINT fk_uictrlh FOREIGN KEY (uicontrolmenu_id) REFERENCES hmsmaster.uicontrol_master(uicontrolmenu_id)
);

CREATE SEQUENCE hmsmaster.org_uicontrol_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

--drop table hmsmaster.org_uicontrol;
create table hmsmaster.org_uicontrol(
	org_uicontrol_id int8 default nextval('hmsmaster.org_uicontrol_id_seq'::regclass) not null,
	orgid int4 not null,
	hierarchy_id int8 not null ,
	role_id int8 not null,
	allow_edit bool not null default false,
	render_control bool null default false,
	access_granted_on timestamp ,
	access_granted_by int4 ,
	CONSTRAINT fk_uictrl_orgid FOREIGN KEY (orgid) REFERENCES app_subscription.organisation(orgid),
	CONSTRAINT fk_uictrl_master FOREIGN KEY (hierarchy_id) REFERENCES hmsmaster.uicontrol_hierarchy(hierarchy_id),
	CONSTRAINT fk_uictrl_role FOREIGN KEY (role_id) REFERENCES hms.roles(role_id),
	CONSTRAINT fk_uictrl_user FOREIGN KEY (access_granted_by) REFERENCES hms."user"(user_id)
);


-- DROP FUNCTION hms.get_ui_control_hierarchy(int4);
CREATE OR REPLACE FUNCTION hms.get_ui_control_hierarchy(p_orgId integer, p_showall bool default true)
 RETURNS jsonb
 LANGUAGE sql
AS $function$
WITH RECURSIVE hierarchy AS (
    -- Step 1: get all paths and convert to array for index-based access
    SELECT
        uch.hierarchy_path,
        uch.hierarchy_id,
        string_to_array(uch.hierarchy_path::TEXT, '.') AS labels
    FROM hmsmaster.uicontrol_hierarchy uch
),
json_tree AS (
    -- Step 2: Anchor - Start from the deepest node (the leaf)
    SELECT
        array_length(labels, 1) AS lvl,
        labels[array_length(labels,1)]::INT AS control_id,
        h.hierarchy_id, -- Expose this so the recursive step can see it
        jsonb_build_object(
            'menuID', ouh.uicontrolmenu_id,
            'menuName', cm.ui_object_name,
            'menuType', cm.ui_object_type,
            'allowEdit', ocm.allow_edit,
            'renderControl', ocm.render_control,
            'accessGrantedOn', ocm.access_granted_on,
            'accessGrantedBy', ocm.access_granted_by,
            'hierarchyId', h.hierarchy_id,
            'childControl', NULL
        ) AS node,
        labels
    FROM hierarchy h
    JOIN hmsmaster.uicontrol_hierarchy ouh ON ouh.uicontrolmenu_id = labels[array_length(labels,1)]::INT
    JOIN hmsmaster.uicontrol_master cm on ouh.uicontrolmenu_id = cm.uicontrolmenu_id
    LEFT JOIN hmsmaster.org_uicontrol ocm on h.hierarchy_id = ocm.hierarchy_id and ocm.orgid = p_orgId
    -- Filter based on p_showall logic
    WHERE (p_showall = true OR ocm.render_control = true)

    UNION ALL

    -- Step 3: Recursive - Build parents and nest the previous 'node' as 'childControl'
    SELECT
        j.lvl - 1,
        labels[j.lvl - 1]::INT AS control_id,
        j.hierarchy_id, -- Pass the leaf's hierarchy_id up the chain
        jsonb_build_object(
            'menuID', cm.uicontrolmenu_id,
            'menuName', cm.ui_object_name,
            'menuType', cm.ui_object_type,
            'allowEdit', ocm.allow_edit,
            'renderControl', ocm.render_control,
            'accessGrantedOn', ocm.access_granted_on,
            'accessGrantedBy', ocm.access_granted_by,
            'hierarchyId', j.hierarchy_id,
            'childControl', j.node -- Nesting the child here
        ) AS node,
        labels
    FROM json_tree j
    JOIN hmsmaster.uicontrol_master cm ON cm.uicontrolmenu_id = labels[j.lvl - 1]::INT
    LEFT JOIN hmsmaster.org_uicontrol ocm on j.hierarchy_id = ocm.hierarchy_id and ocm.orgid = p_orgId
    WHERE j.lvl > 1
    AND (p_showall = true OR ocm.render_control = true)
)
-- Step 4: Final output - Only take the top-level nodes (lvl 1)
SELECT jsonb_agg(node)
FROM json_tree
WHERE lvl = 1;
$function$;

CREATE TABLE hms.temp_designation_update (
    temp_designation_update_id bigserial PRIMARY KEY,
    agent_code              varchar(50)  NOT NULL,
    designation             varchar(100) NOT NULL,
    business_effective_date date         NOT NULL,
    processing_status       varchar(20)  NOT NULL DEFAULT 'Pending',
    comments                varchar(20),
    reason                  text,
    orgid                   int          NOT NULL
);


CREATE TABLE hms.temp_location_update (
    temp_location_id   bigserial PRIMARY KEY,
    agent_code         varchar(50)  NOT NULL,
    location_type      varchar(50),
    location_code      varchar(20)  NOT NULL,
    current_channel    varchar(100) NOT NULL,
    current_subchannel varchar(100) NOT NULL,
    status             varchar(50)  NOT NULL DEFAULT 'Pending',
    orgid              int          NOT NULL,
    comment            varchar(20),
    reason             text,

    CONSTRAINT fk_temp_location_agent_org_lookup
        FOREIGN KEY (agent_code, orgid) 
        REFERENCES hms.agent (agent_code, orgid),
        
   CONSTRAINT fk_temp_location_org
        FOREIGN KEY (orgid) 
        REFERENCES app_subscription.organisation (orgid)
);
